#!/bin/sh

DEFAULT_SETTINGS="/etc/default/live-helper"

# Checking depends
dpkg -l debootstrap cdebootstrap

# Checking suggests
dpkg -l dosfstools genisoimage memtest86+ memtest86 mtools parted squashfs-tools genext2fs mtd-tools sudo fakeroot syslinux grub uuid-runtime

if [ -e "${DEFAULT_SETTINGS}" ]; then
	echo "Contents of ${DEFAULT_SETTINGS}:"
	cat "${DEFAULT_SETTINGS}"
else
	echo "${DEFAULT_SETTINGS} does not exist."
fi
