#!/bin/sh

# lh_binary_local-includes(1) - copy files into binary
# Copyright (C) 2006-2009 Daniel Baumann <daniel@debian.org>
#
# live-helper comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
# This is free software, and you are welcome to redistribute it
# under certain conditions; see COPYING for details.

set -e

# Including common functions
. "${LH_BASE:-/usr/share/live-helper}"/live-helper.sh

# Setting static variables
DESCRIPTION="$(Echo 'copy files into binary')"
HELP=""
USAGE="${PROGRAM} [--force]"

Arguments "${@}"

# Reading configuration files
Read_conffiles config/all config/common config/bootstrap config/chroot config/binary config/source
Set_defaults

Echo_message "Begin copying binary local includes..."

# Requiring stage file
Require_stagefile .stage/config .stage/bootstrap

# Checking stage file
Check_stagefile .stage/binary_local-includes

# Checking lock file
Check_lockfile .lock

# Creating lock file
Create_lockfile .lock

if Find_files config/binary_local-includes/
then
	# Copying includes
	cd config/binary_local-includes
	find . | cpio -dmpu --no-preserve-owner "${OLDPWD}"/binary
	cd "${OLDPWD}"

	# Removing symlinks
	if [ "${LH_BINARY_IMAGES}" = "usb-hdd" ]
	then
		find binary -type l | xargs rm -f
	fi

	# Creating stage file
	Create_stagefile .stage/binary_local-includes
fi
