#!/bin/sh

# lh(1) - generic live-helper wrapper
# Copyright (C) 2006-2010 Daniel Baumann <daniel@debian.org>
#
# live-helper comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
# This is free software, and you are welcome to redistribute it
# under certain conditions; see COPYING for details.

set -e

# Including common functions
. "${LH_BASE:-/usr/share/live-helper}"/live-helper.sh

# Setting static variables
DESCRIPTION="$(Echo 'utility to build Debian Live systems')"
HELP="FIXME"
USAGE="FIXME"

case "${1}" in
	-h|--help)
		if [ -x "$(which man 2>/dev/null)" ]
		then
			man lh
			exit 0
		else
			${0} --usage
			exit 0
		fi
		;;

	""|-u|--usage)
		Usage
		;;

	-v|--version)
		Version
		;;

	*)
		COMMAND="${1}"
		shift

		if [ -x "${LH_BASE}/helpers/${COMMAND}" ]
		then
			LH=1 exec "${LH_BASE}/helpers/${COMMAND}" "${@}"
		elif [ -x /usr/share/live-helper/helpers/${COMMAND} ]
		then
			LH=1 exec /usr/share/live-helper/helpers/"${COMMAND}" "${@}"
		elif [ -x "$(which ${COMMAND} 2>/dev/null)" ]
		then
			LH=1 exec "${COMMAND}" "${@}"
		else
			Echo_error "no such helper"
			exit 1
		fi
		;;
esac
