#!/bin/sh

# live-helper(1) - utility to build Debian Live systems
# Copyright (C) 2006-2007 Daniel Baumann <daniel@debian.org>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
# On Debian systems, the complete text of the GNU General Public License
# can be found in /usr/share/common-licenses/GPL-3 file.

set -e

# Including common functions
LH_BASE="${LH_BASE:-/usr/share/live-helper}"

for FUNCTION in "${LH_BASE}"/functions/*.sh
do
	. "${FUNCTION}"
done

# Setting static variables
DESCRIPTION="utility to build Debian Live systems"
HELP="FIXME"
USAGE="FIXME"

case "${1}" in
	-h|--help)
		Help
		;;

	-u|--usage)
		Usage
		;;

	-v|--version)
		Version
		;;

	*)
		if [ ! -z "$(whereis lh_${1})" ]
		then
			exec lh_"${1}" $(echo ${@} | sed -e "s|${1}||")
		else
			Echo_error "no such helper"
			exit 1
		fi
		;;
esac
