#!/bin/sh

# lh_binary_linuximage(1) - install linux-image into binary

set -e

# Source common functions
for FUNCTION in /usr/share/live-helper/functions/*.sh
do
	. ${FUNCTION}
done

# Reading configuration files
Read_conffile config/common
Read_conffile config/image
Set_defaults

# Requiring stage file
Require_stagefile .stage/bootstrap

# Checking lock file
Check_lockfile .lock

# Creating lock file
Create_lockfile .lock

# Checking stage file
Check_stagefile .stage/binary_linuximage

# Removing initrd backup files
rm -f chroot/boot/initrd*bak*

# Setting destination directory
case "${LIVE_BINARY_IMAGE}" in
	iso)
		DESTDIR="binary/isolinux"
		;;

	net)
		DESTDIR="tftpboot"
		;;

	usb|hdd)
		DESTDIR="binary"
		;;
esac

# Creating directory
if [ ! -d "${DESTDIR}" ]
then
	mkdir -p "${DESTDIR}"
fi

# Installing linux-image
cp chroot/boot/vmlinuz* "${DESTDIR}"/vmlinuz
cp chroot/boot/initrd.img* "${DESTDIR}"/initrd.gz

# Creating stage file
Create_stagefile .stage/binary_linuximage
