#!/bin/sh

# lh_bootstrap_copy(1) - bootstrap by copying the host system
# Copyright (C) 2006-2008 Daniel Baumann <daniel@debian.org>
#
# live-helper comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
# This is free software, and you are welcome to redistribute it
# under certain conditions; see COPYING for details.

set -e

# Including common functions
LH_BASE="${LH_BASE:-/usr/share/live-helper}"

for FUNCTION in "${LH_BASE}"/functions/*.sh
do
	. "${FUNCTION}"
done

# Setting static variables
DESCRIPTION="bootstrap by copying the host system"
HELP=""
USAGE="${PROGRAM} [--force]"

Arguments "${@}"

# Reading configuration files
Read_conffile config/all config/common config/bootstrap config/chroot config/binary config/source
Set_defaults

if [ "${LH_BOOTSTRAP}" != "copy" ]
then
	exit 0
fi

# Check architecture
Check_crossarchitecture

Echo_message "Begin bootstrapping system..."

# Ensure that a system is built as root
lh_testroot

# Checking stage file
Check_stagefile .stage/bootstrap

# Checking lock file
Check_lockfile .lock

# Creating lock file
Create_lockfile .lock

# Copying host system
cd chroot
tar c / --exclude /proc --exclude /sys "$(dirname ${PWD})" | tar xv
cd ..

# Creating stage file
Create_stagefile .stage/bootstrap
