#!/bin/sh

# lh_binary_usb(1) - build binary image
# Copyright (C) 2006-2007 Daniel Baumann <daniel@debian.org>
#
# live-helper comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
# This is free software, and you are welcome to redistribute it
# under certain conditions; see COPYING for details.

set -e

# Source common functions
for FUNCTION in /usr/share/live-helper/functions/*.sh
do
	. ${FUNCTION}
done

# Set static variables
DESCRIPTION="build binary image"
HELP=""
USAGE="${PROGRAM} [--force]"

Arguments "${@}"

# Reading configuration files
Read_conffile config/common
Read_conffile config/bootstrap
Read_conffile config/image
Set_defaults

for IMAGE in ${LIVE_BINARY_IMAGE}
do
	if [ "${IMAGE}" = "usb" ]
	then
		# Requiring stage file
		Require_stagefile .stage/bootstrap
		Require_stagefile .stage/chroot_proc

		# Checking lock file
		Check_lockfile .lock

		# Creating lock file
		Create_lockfile .lock

		# Checking stage file
		Check_stagefile .stage/binary_usb

		if [ ! -f chroot/sbin/mkdosfs ]
		then
			PACKAGES="${PACKAGES} dosfstools"
		fi

		if [ ! -f chroot/usr/bin/mtools ]
		then
			PACKAGES="${PACKAGES} mtools"
		fi

		if [ ! -f chroot/sbin/parted ]
		then
			PACKAGES="${PACKAGES} parted"
		fi

		if [ ! -f chroot/usr/bin/syslinux ]
		then
			PACKAGES="${PACKAGES} syslinux"
		fi

		if [ -n "${PACKAGES}" ]
		then
			# Installing packages
			case "${LH_APT}" in
				apt|apt-get)
					Chroot "apt-get install --yes ${PACKAGES}"
					;;

				aptitude)
					Chroot "aptitude install --assume-yes ${PACKAGES}"
					;;
			esac
		fi

		# Remove old binary
		if [ -f binary.img ]
		then
			rm -f binary.img
		fi

		# Everything which comes here needs to be cleaned up,
		DU_DIM="`du -ms binary | cut -f1`"
		REAL_DIM="`expr ${DU_DIM} + ${DU_DIM} / 20`" # Just 5% more to be sure, need something more sophistcated here...
		dd if=/dev/zero of=binary.img bs=1024k count=${REAL_DIM}
		FREELO="`${LH_LOSETUP} -f`"
		if [ ! -b chroot/${FREELO} ]
		then
			MAKEDEV="true"

			mv chroot/dev chroot/dev.tmp
			find /dev | cpio -dmpu chroot
		fi

		echo "!!! The following error/warning messages can be ignored !!!"
		lh_losetup $FREELO binary.img 0
		Chroot "parted -s ${FREELO} mklabel msdos" || true
		Chroot "parted -s ${FREELO} mkpartfs primary fat16 0.0 100%" || true
		Chroot "parted -s ${FREELO} set 1 boot on" || true
		Chroot "parted -s ${FREELO} set 1 lba off" || true
		cat chroot/usr/lib/syslinux/mbr.bin > ${FREELO}
		${LH_LOSETUP} -d ${FREELO}

		lh_losetup $FREELO binary.img 1
		Chroot "mkfs.msdos -n DEBIAN_LIVE ${FREELO}"
		mkdir -p binary.tmp
		mount ${FREELO} binary.tmp
		cp -r binary/* binary.tmp
		umount binary.tmp
		rmdir binary.tmp
		Chroot "syslinux ${FREELO}"
		${LH_LOSETUP} -d ${FREELO}
		echo "!!! The above error/warning messages can be ignored !!!"

		if [ -n "${MAKEDEV}" ]
		then
			rm -f chroot/dev
			mv chroot/dev.tmp chroot/dev
		fi

		if [ -n "${PACKAGES}" ]
		then
			# Removing packages
			case "${LH_APT}" in
				apt|apt-get)
					Chroot "apt-get remove --purge --yes ${PACKAGES}"
					;;

				aptitude)
					Chroot "aptitude purge --assume-yes ${PACKAGES}"
					;;
			esac
		fi

		# Creating stage file
		Create_stagefile .stage/binary_usb
	fi
done
