#!/bin/sh

# lh_bootstrap(1) - bootstrap a Debian system
# Copyright (C) 2006-2007 Daniel Baumann <daniel@debian.org>
#
# live-helper comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
# This is free software, and you are welcome to redistribute it
# under certain conditions; see COPYING for details.

set -e

# Source common functions
for FUNCTION in /usr/share/live-helper/functions/*.sh
do
	. ${FUNCTION}
done

# Set static variables
DESCRIPTION="bootstrap a Debian system"
HELP=""
USAGE="${PROGRAM} [--force]"

Arguments "${@}"

if [ "${FORCE}" = "true" ]
then
	OPTIONS="${OPTIONS} --force"
fi

# Reading configuration files
Read_conffile config/common
Set_defaults

# Bootstrapping system
lh_bootstrap_"${LH_BOOTSTRAP}" "${OPTIONS}"
