#!/bin/sh

# lh_bootstrap_debootstrap(1) - bootstrap a Debian system with debootstrap(8)
# Copyright (C) 2006-2007 Daniel Baumann <daniel@debian.org>
#
# live-helper comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
# This is free software, and you are welcome to redistribute it
# under certain conditions; see COPYING for details.

set -e

# Including common functions
LH_BASE="${LH_BASE:-/usr/share/live-helper}"

for FUNCTION in "${LH_BASE}"/functions/*.sh
do
	. "${FUNCTION}"
done

# Setting static variables
DESCRIPTION="bootstrap a Debian system with debootstrap(8)"
HELP=""
USAGE="${PROGRAM} [--force]"

Arguments "${@}"

# Reading configuration files
Read_conffile config/common
Read_conffile config/bootstrap
Read_conffile config/chroot
Read_conffile config/binary
Read_conffile config/source
Read_conffile "${LH_CONFIG}"
Set_defaults

if [ "${LH_BOOTSTRAP}" != "debootstrap" ]
then
	exit 0
fi

# Check architecture
Check_crossarchitecture

Echo_message "Begin bootstrapping system..."

Check_package /usr/sbin/debootstrap debootstrap

# Ensure that a system is built as root
lh_testroot

# Checking stage file
Check_stagefile .stage/bootstrap
Check_stagefile .stage/bootstrap_cache.restore

# Checking lock file
Check_lockfile .lock

# Creating lock file
Create_lockfile .lock

# Creating chroot directory
mkdir -p chroot

# Setting debootstrap options
if [ -n "${LH_ARCHITECTURE}" ]
then
	DEBOOTSTRAP_OPTIONS="${DEBOOTSTRAP_OPTIONS} --arch ${LH_ARCHITECTURE}"
fi

if [ -n "${LH_BOOTSTRAP_CONFIG}" ]
then
	LH_DEBOOTSTRAP_SCRIPT="/usr/lib/debootstrap/scripts/${LH_BOOTSTRAP_CONFIG}"
fi

if [ -n "${LH_BOOTSTRAP_INCLUDE}" ]
then
	DEBOOTSTRAP_OPTIONS="${DEBOOTSTRAP_OPTIONS} --include=${LH_BOOTSTRAP_INCLUDE}"
fi

if [ -n "${LH_BOOTSTRAP_EXCLUDE}" ]
then
	DEBOOTSTRAP_OPTIONS="${DEBOOTSTRAP_OPTIONS} --exclude=${LH_BOOTSTRAP_EXCLUDE}"
fi

if [ "${LH_VERBOSE}" = "true" ]
then
	DEBOOTSTRAP_OPTIONS="${DEBOOTSTRAP_OPTIONS} --verbose"
fi

if [ -x "/usr/sbin/debootstrap" ]
then
	if [ "${LH_CACHE_PACKAGES}" = "enabled" ]
	then
		if [ -d cache/packages_bootstrap ]
		then
			mkdir -p chroot/var/cache/apt/archives
			cp cache/packages_bootstrap/*.deb chroot/var/cache/apt/archives
		fi

		# Executing debootstrap (download-only)
		${LH_ROOT_COMMAND} debootstrap ${DEBOOTSTRAP_OPTIONS} --download-only "${LH_DISTRIBUTION}" chroot "${LH_MIRROR_BOOTSTRAP}" "${LH_DEBOOTSTRAP_SCRIPT}"

		if [ -n "${LH_ROOT_COMMAND}" ]
		then
			${LH_ROOT_COMMAND} chown -R $(whoami):$(whoami) chroot
		fi

		# Removing old cache
		if [ -d cache/packages_bootstrap ]
		then
			rm -f cache/packages_bootstrap/*.deb
		fi

		# Saving new cache
		mkdir -p cache/packages_bootstrap

		cp chroot/var/cache/apt/archives/*.deb cache/packages_bootstrap
	fi

	# Executing debootstrap (regular run)
	${LH_ROOT_COMMAND} debootstrap ${DEBOOTSTRAP_OPTIONS} "${LH_DISTRIBUTION}" chroot "${LH_MIRROR_BOOTSTRAP}" "${LH_DEBOOTSTRAP_SCRIPT}"

	if [ -n "${LH_ROOT_COMMAND}" ]
	then
		${LH_ROOT_COMMAND} chown -R $(whoami):$(whoami) chroot
	fi

	# Removing bootstrap cache
	rm -f chroot/var/cache/apt/archives/*.deb

	# Creating stage file
	Create_stagefile .stage/bootstrap
else
	Echo_error "Can't process file /usr/bin/debootstrap (FIXME)"
	exit 1
fi
