#!/bin/sh

# lh_binary_linux-image(1) - install linux-image into binary
# Copyright (C) 2006-2007 Daniel Baumann <daniel@debian.org>
#
# live-helper comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
# This is free software, and you are welcome to redistribute it
# under certain conditions; see COPYING for details.

set -e

# Source common functions
for FUNCTION in /usr/share/live-helper/functions/*.sh
do
	. ${FUNCTION}
done

# Set static variables
DESCRIPTION="install linux-image into binary"
HELP=""
USAGE="${PROGRAM} [--force]"

Arguments "${@}"

Echo_debug "Init ${PROGRAM}"

# Reading configuration files
Read_conffile config/common
Read_conffile config/bootstrap
Read_conffile config/chroot
Read_conffile config/binary
Read_conffile config/source
Set_defaults

Breakpoint "binary_linux-image: Init"

# Requiring stage file
Require_stagefile .stage/bootstrap

# Checking stage file
Check_stagefile .stage/binary_linux-image

# Checking lock file
Check_lockfile .lock

# Creating lock file
Create_lockfile .lock

# Removing initrd backup files
rm -f chroot/boot/initrd*bak*

# Setting destination directory
case "${LIVE_BINARY_IMAGES}" in
	iso)
		DESTDIR="binary/live"
		;;

	net)
		DESTDIR="tftpboot"
		;;

	usb-hdd|hdd)
		# Workaround for syslinux (<< 3.36) which doesn't support long file/path names
		if [ "${LIVE_DISTRIBUTION}" = "etch" ] || [ "${LIVE_DISTRIBUTION}" = "lenny" ]
		then
			if [ "${LIVE_BOOTLOADER}" = "syslinux" ]
			then
				DESTDIR="binary"
			else
				DESTDIR="binary/live"
			fi
		else
			DESTDIR="binary/live"
		fi
		;;
esac

# Temporary check for broken syslinux
if [ "${LIVE_BINARY_IMAGES}" = "iso" ]
then
	# Assemble multi-arch
	if [ -n "${MULTIARCH}" ]
	then
		case "${LIVE_ARCHITECTURE}" in
			amd64)
				DESTDIR="${DESTDIR}.amd"
				;;

			i386)
				DESTDIR="${DESTDIR}.386"
				;;

			powerpc)
				DESTDIR="${DESTDIR}.ppc"
				;;
		esac
	fi
fi

# Creating directory
if [ ! -d "${DESTDIR}" ]
then
	mkdir -p "${DESTDIR}"
fi

# Installing linux-image
cp chroot/boot/vmlinuz* "${DESTDIR}"
cp chroot/boot/initrd.img* "${DESTDIR}"

# Creating stage file
Create_stagefile .stage/binary_linux-image
