#!/bin/sh

# lh_binary_hdd(1) - build harddisk binary image

set -e

# Source common functions
for FUNCTION in /usr/share/live-helper/functions/*.sh
do
	. ${FUNCTION}
done

# Reading configuration files
Read_conffile config/common
Read_conffile config/bootstrap
Read_conffile config/image
Set_defaults

# Requiring stage file
Require_stagefile .stage/bootstrap

# Checking lock file
Check_lockfile .lock

# Creating lock file
Create_lockfile .lock

# Checking stage file
Check_stagefile .stage/binary_hdd

for IMAGE in ${LIVE_BINARY_IMAGE}
do
	if [ "${IMAGE}" = "hdd" ]
	then
		# Remove old binary
		if [ -f binary-hdd.tar.gz ]
		then
			rm -f binary-hdd.tar.gz
		fi

		tar cfz binary-hdd.tar.gz binary

		# Creating stage file
		Create_stagefile .stage/binary_hdd
	fi
done
