#!/bin/sh

# lh_binary_net(1) - build netboot binary image
# Copyright (C) 2006-2007 Daniel Baumann <daniel@debian.org>
#
# live-helper comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
# This is free software, and you are welcome to redistribute it
# under certain conditions; see COPYING for details.

set -e

# Source common functions
for FUNCTION in /usr/share/live-helper/functions/*.sh
do
	. ${FUNCTION}
done

# Set static variables
DESCRIPTION="build netboot binary image"
HELP=""
USAGE="${PROGRAM} [--force]"

Arguments "${@}"

Echo_debug "Init ${PROGRAM}"

# Reading configuration files
Read_conffile config/common
Read_conffile config/bootstrap
Read_conffile config/chroot
Read_conffile config/binary
Read_conffile config/source
Set_defaults

Breakpoint "binary_net: Init"

for IMAGE in ${LIVE_BINARY_IMAGE}
do
	if [ "${IMAGE}" = "net" ]
	then
		# Requiring stage file
		Require_stagefile .stage/bootstrap

		# Checking stage file
		Check_stagefile .stage/binary_net

		# Checking lock file
		Check_lockfile .lock

		# Creating lock file
		Create_lockfile .lock

		# Remove old binary
		if [ -f binary-net.tar.gz ]
		then
			rm -f binary-net.tar.gz
		fi

		# Creating image file
		if [ "`basename ${LIVE_SERVER_PATH}`" = "chroot" ]
		then
			mv chroot chroot.tmp
		fi

		mv binary "`basename ${LIVE_SERVER_PATH}`"

		cd ..
		tar cfz binary-net.tar.gz "`basename ${OLDPWD}`/`basename ${LIVE_SERVER_PATH}`" "`basename ${OLDPWD}`/tftpboot"
		mv binary-net.tar.gz "${OLDPWD}"
		cd "${OLDPWD}"

		mv "`basename ${LIVE_SERVER_PATH}`" binary

		if [ "`basename ${LIVE_SERVER_PATH}`" = "chroot" ]
		then
			mv chroot.tmp chroot
		fi

		# Creating stage file
		Create_stagefile .stage/binary_net
	fi
done
