#!/bin/sh

# lh_image(1) - building the images

# Building root filesystem
lh_binary_rootfs
lh_binary_manifest
lh_binary_encryption

# Configuring chroot
lh_chroot_proc install
lh_chroot_sysfs install
lh_chroot_hosts install
lh_chroot_resolv install
lh_chroot_sources install

# Prepare images
lh_binary_linuximage
lh_binary_memtest86
lh_binary_syslinux
lh_binary_includes
lh_binary_localincludes
lh_binary_md5sum

# Building images
lh_binary_hdd
lh_binary_iso
lh_binary_net
lh_binary_usb

# Deconfiguring chroot
rm -f .stage/chroot_sources
lh_chroot_resolv remove
lh_chroot_hosts remove
lh_chroot_sysfs remove
lh_chroot_proc remove
