#!/bin/sh

# lh_binary_hdd(1) - build harddisk binary image
# Copyright (C) 2006-2007 Daniel Baumann <daniel@debian.org>
#
# live-helper comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
# This is free software, and you are welcome to redistribute it
# under certain conditions; see COPYING for details.

set -e

# Including common functions
LH_BASE="${LH_BASE:-/usr/share/live-helper}"

for FUNCTION in "${LH_BASE}"/functions/*.sh
do
	. "${FUNCTION}"
done

# Setting static variables
DESCRIPTION="build harddisk binary image"
HELP=""
USAGE="${PROGRAM} [--force]"

Arguments "${@}"

# Reading configuration files
Read_conffile config/common
Read_conffile config/bootstrap
Read_conffile config/chroot
Read_conffile config/binary
Read_conffile config/source
Set_defaults

if ! echo "${LIVE_BINARY_IMAGES}" | grep -qs hdd
then
	exit 0
fi

Echo_message "Begin building binary harddisk image..."

# Requiring stage file
Require_stagefile .stage/bootstrap

# Checking stage file
Check_stagefile .stage/binary_hdd

# Checking lock file
Check_lockfile .lock

# Creating lock file
Create_lockfile .lock

# Remove old binary
rm -f binary-hdd.tar.gz

tar cfz binary-hdd.tar.gz binary

# Creating stage file
Create_stagefile .stage/binary_hdd
