#!/bin/sh

# lh_bootstrap_cdebootstrap(1) - bootstrap a Debian system with cdebootstrap(1)
# Copyright (C) 2006-2007 Daniel Baumann <daniel@debian.org>
#
# live-helper comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
# This is free software, and you are welcome to redistribute it
# under certain conditions; see COPYING for details.

set -e

# Source common functions
for FUNCTION in /usr/share/live-helper/functions/*.sh
do
	. ${FUNCTION}
done

# Set static variables
DESCRIPTION="bootstrap a Debian system with cdebootstrap(1)"
HELP=""
USAGE="${PROGRAM} [--force]"

Arguments "${@}"

# Ensure that a system is built as root
lh_testroot

Echo_debug "Init ${PROGRAM}"

# Reading configuration files
Read_conffile config/common
Read_conffile config/bootstrap
Read_conffile config/chroot
Read_conffile config/binary
Read_conffile config/source
Set_defaults

Breakpoint "bootstrap_cdeboostrap: Init"

if [ "${LH_BOOTSTRAP}" != "cdebootstrap" ]
then
	exit 0
fi

# Checking stage file
Check_stagefile .stage/bootstrap

# Checking lock file
Check_lockfile .lock

# Creating lock file
Create_lockfile .lock

# Creating chroot directory
if [ ! -d chroot ]
then
	mkdir -p chroot
fi

# Setting cdebootstrap options
if [ -n "${LIVE_ARCHITECTURE}" ]
then
	CDEBOOTSTRAP_OPTIONS="${CDEBOOTSTRAP_OPTIONS} --arch=${LIVE_ARCHITECTURE}"
fi

if [ -n "${LIVE_BOOTSTRAP_CONFIG}" ]
then
	CDEBOOTSTRAP_OPTIONS="${CDEBOOTSTRAP_OPTIONS} --suite-config=${LIVE_BOOTSTRAP_CONFIG}"
fi

if [ "${LIVE_PACKAGES_LISTS}" != "minimal" ] && [ "${LIVE_PACKAGES_LISTS}" != "mini" ]
then
	CDEBOOTSTRAP_OPTIONS="${CDEBOOTSTRAP_OPTIONS} --flavour=standard"
else
	CDEBOOTSTRAP_OPTIONS="${CDEBOOTSTRAP_OPTIONS} --flavour=minimal"
fi

if [ "${LH_DEBUG}" = "true" ]
then
	CDEBOOTSTRAP_OPTIONS="${CDEBOOTSTRAP_OPTIONS} --debug"
fi

if [ "${LH_QUIET}" = "true" ]
then
	CDEBOOTSTRAP_OPTIONS="${CDEBOOTSTRAP_OPTIONS} --quiet"
fi

if [ "${LH_VERBOSE}" = "true" ]
then
	CDEBOOTSTRAP_OPTIONS="${CDEBOOTSTRAP_OPTIONS} --verbose"
fi

if [ -x "/usr/bin/cdebootstrap" ]
then
	for STAGE in ${LH_CACHE_STAGES}
	do
		if [ "${STAGE}" = "bootstrap" ] && [ -d cache/stages_bootstrap ]
		then
			# Restore old cache
			${LH_ROOT_COMMAND} cp -a cache/stages_bootstrap/* chroot

			if [ -n "${LH_ROOT_COMMAND}" ]
			then
				${LH_ROOT_COMMAND} chown -R `whoami`:`whoami` chroot
			fi

			# Creating stage file
			Create_stagefile .stage/bootstrap

			exit 0
		fi
	done

	if [ "${LH_CACHE_PACKAGES}" = "enabled" ]
	then
		if [ -d cache/packages_bootstrap ]
		then
			mkdir -p chroot/var/cache/bootstrap
			cp cache/packages_bootstrap/*.deb chroot/var/cache/bootstrap
		fi

		# Executing cdebootstrap (download-only)
		${LH_ROOT_COMMAND} cdebootstrap ${CDEBOOTSTRAP_OPTIONS} --download-only "${LIVE_DISTRIBUTION}" chroot "${LIVE_MIRROR_BOOTSTRAP}"

		if [ -n "${LH_ROOT_COMMAND}" ]
		then
			${LH_ROOT_COMMAND} chown -R `whoami`:`whoami` chroot
		fi

		# Removing old cache
		if [ -d cache/packages_bootstrap ]
		then
			rm -f cache/packages_bootstrap/*.deb
		fi

		# Saving new cache
		if [ ! -d cache/packages_bootstrap ]
		then
			mkdir -p cache/packages_bootstrap
		fi

		cp chroot/var/cache/bootstrap/*.deb cache/packages_bootstrap
	fi

	# Executing cdebootstrap (regular run)
	${LH_ROOT_COMMAND} cdebootstrap ${CDEBOOTSTRAP_OPTIONS} "${LIVE_DISTRIBUTION}" chroot "${LIVE_MIRROR_BOOTSTRAP}"

	if [ -n "${LH_ROOT_COMMAND}" ]
	then
		${LH_ROOT_COMMAND} chown -R `whoami`:`whoami` chroot
	fi

	# Remove cdebootstrap-helper-diverts (needed at least for minimal flavours)
	if [ "${LIVE_BOOTSTRAP_FLAVOUR}" = "minimal" ] || [ "${LIVE_BOOTSTRAP_FLAVOUR}" = "mini" ]
	then
		Chroot "dpkg -P cdebootstrap-helper-diverts"
	fi

	# Deconfiguring cdebootstrap configurations
	rm -f chroot/etc/apt/sources.list
	rm -f chroot/etc/hosts
	rm -f chroot/etc/resolv.conf

	# Removing bootstrap cache
	rm -rf chroot/var/cache/bootstrap

	# Saving new cache
	for STAGE in ${LH_CACHE_STAGES}
	do
		if [ "${STAGE}" = "bootstrap" ]
		then
			if [ -d cache/stages_bootstrap ]
			then
				rm -rf cache/stages_bootstrap
			fi

			if [ ! -d cache ]
			then
				mkdir cache
			fi

			${LH_ROOT_COMMAND} cp -a chroot cache/stages_bootstrap

			if [ -n "${LH_ROOT_COMMAND}" ]
			then
				${LH_ROOT_COMMAND} chown -R `whoami`:`whoami` cache/stages_bootstrap
			fi
		fi
	done

	# Creating stage file
	Create_stagefile .stage/bootstrap
else
	Echo_error "Can't process file /usr/bin/cdebootstrap (FIXME)"
	exit 1
fi
