#!/bin/sh

# lh_binary_local-hooks(1) - execute local hooks in binary
# Copyright (C) 2006-2008 Daniel Baumann <daniel@debian.org>
#
# live-helper comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
# This is free software, and you are welcome to redistribute it
# under certain conditions; see COPYING for details.

set -e

# Including common functions
LH_BASE="${LH_BASE:-/usr/share/live-helper}"

for FUNCTION in "${LH_BASE}"/functions/*.sh
do
	. "${FUNCTION}"
done

# Setting static variables
DESCRIPTION="execute local hooks in binary"
HELP=""
USAGE="${PROGRAM} [--force]"

Arguments "${@}"

# Reading configuration files
Read_conffile config/all config/common config/bootstrap config/chroot config/binary config/source
Set_defaults

Echo_message "Begin executing local hooks..."

# Requiring stage file
Require_stagefile .stage/bootstrap

# Checking stage file
Check_stagefile .stage/binary_local-hooks

# Checking lock file
Check_lockfile .lock

# Creating lock file
Create_lockfile .lock

# Processing local-hooks
if ls config/binary_local-hooks/* > /dev/null 2>&1
then
	for HOOK in config/binary_local-hooks/*
	do
		# Making hook executable
		if [ ! -x "${HOOK}" ]
		then
			chmod +x "${HOOK}"
		fi

		# Executing hook
		./"${HOOK}"
	done

	# Creating stage file
	Create_stagefile .stage/binary_local-hooks
fi
