#!/bin/sh

# lh_binary_md5sum(1) - create binary md5sums
# Copyright (C) 2006-2007 Daniel Baumann <daniel@debian.org>
#
# live-helper comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
# This is free software, and you are welcome to redistribute it
# under certain conditions; see COPYING for details.

set -e

# Source common functions
for FUNCTION in /usr/share/live-helper/functions/*.sh
do
	. ${FUNCTION}
done

# Set static variables
DESCRIPTION="create binary md5sums"
HELP=""
USAGE="${PROGRAM} [--force]"

Arguments "${@}"

Echo_debug "Init ${PROGRAM}"

# Reading configuration files
Read_conffile config/bootstrap
Read_conffile config/chroot
Read_conffile config/common
Read_conffile config/image
Set_defaults

Breakpoint "binary_md5sum: Init"

# Requiring stage file
Require_stagefile .stage/bootstrap

# Checking lock file
Check_lockfile .lock

# Creating lock file
Create_lockfile .lock

# Checking stage file
Check_stagefile .stage/binary_md5sum

# Remove old md5sums
if [ -f binary/md5sum.txt ]
then
	rm -f binary/md5sum.txt
fi

# Calculating md5sums
cd binary
find . -type f -print0 | xargs -0 md5sum > md5sum.txt
cd "${OLDPWD}"

# Creating stage file
Create_stagefile .stage/binary_md5sum
