#!/bin/sh

# lh_binary_win32-loader(1) - copy win32-loader into binary
# Copyright (C) 2006-2009 Daniel Baumann <daniel@debian.org>
#
# live-helper comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
# This is free software, and you are welcome to redistribute it
# under certain conditions; see COPYING for details.

set -e

# Including common functions
. "${LH_BASE:-/usr/share/live-helper}"/functions.sh

# Setting static variables
DESCRIPTION="$(Echo 'copy win32-loader into binary')"
HELP=""
USAGE="${PROGRAM} [--force]"

Arguments "${@}"

# Reading configuration files
Read_conffiles config/all config/common config/bootstrap config/chroot config/binary config/source
Set_defaults

Echo_message "Begin copying win32-loader..."

# Requiring stage file
Require_stagefile .stage/config .stage/bootstrap

# Checking stage file
Check_stagefile .stage/binary_win32-loader

# Checking lock file
Check_lockfile .lock

# Creating lock file
Create_lockfile .lock

if [ "${LH_WIN32_LOADER}" = "enabled" ] && [ "${LH_DISTRIBUTION}" != "etch" ]
then
	case "${LH_ARCHITECTURE}" in
		amd64|i386)
			# Checking depends
			Check_package chroot/usr/lib/win32-loader/win32-loader.exe win32-loader

			# Restoring cache
			Restore_cache cache/packages_binary

			# Installing depends
			Install_package

			# Copying win32-loader
			cp chroot/usr/lib/win32-loader/* binary
			mv binary/win32-loader.exe binary/setup.exe

			# Saving cache
			Save_cache cache/packages_binary

			# Removing depends
			Remove_package
			;;

		*)
			Echo_warning "win32-loader inclusion is enabled but not compatible with your architecture, ignoring."
			;;
	esac
fi

# Creating stage file
Create_stagefile .stage/binary_win32-loader
