#!/bin/sh

# lh_binary_includes(1) - copy files into binary
# Copyright (C) 2006-2007 Daniel Baumann <daniel@debian.org>
#
# live-helper comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
# This is free software, and you are welcome to redistribute it
# under certain conditions; see COPYING for details.

set -e

# Source common functions
for FUNCTION in /usr/share/live-helper/functions/*.sh
do
	. ${FUNCTION}
done

# Set static variables
DESCRIPTION="copy files into binary"
HELP=""
USAGE="${PROGRAM} [--force]"

Arguments "${@}"

# Reading configuration files
Read_conffile config/common
Read_conffile config/chroot
Read_conffile config/image
Set_defaults

# Requiring stage file
Require_stagefile .stage/bootstrap

# Checking lock file
Check_lockfile .lock

# Creating lock file
Create_lockfile .lock

# Checking stage file
Check_stagefile .stage/binary_includes

# Check includes
if [ ! -d "${LIVE_INCLUDES}" ]
then
	if [ -d ../"${LIVE_INCLUDES}" ]
	then
		LIVE_INCLUDES="../${LIVE_INCLUDES}"
	else
		Echo_error "user specified includes not accessible in ${LIVE_INCLUDES}"
		exit 1
	fi
fi

if ls "${LIVE_INCLUDES}"/common/* &> /dev/null
then
	cd "${LIVE_INCLUDES}"/common
	find . | cpio -dmpu "${OLDPWD}"/binary
	cd "${OLDPWD}"
fi

if ls "${LIVE_INCLUDES}"/"${LIVE_BINARY_IMAGE}"/* &> /dev/null
then
	cd "${LIVE_INCLUDES}"/"${LIVE_BINARY_IMAGE}"
	find . | cpio -dmpu "${OLDPWD}"/binary
	cd "${OLDPWD}"
fi

# Creating stage file
Create_stagefile .stage/binary_includes
