#!/bin/sh

# lh_bootstrap_copy(1) - bootstrap by copying the host system
# Copyright (C) 2006-2007 Daniel Baumann <daniel@debian.org>
#
# live-helper comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
# This is free software, and you are welcome to redistribute it
# under certain conditions; see COPYING for details.

set -e

# Including common functions
LH_BASE="${LH_BASE:-/usr/share/live-helper}"

for FUNCTION in "${LH_BASE}"/functions/*.sh
do
	. "${FUNCTION}"
done

# Setting static variables
DESCRIPTION="bootstrap by copying the host system"
HELP=""
USAGE="${PROGRAM} [--force]"

Arguments "${@}"

# Reading configuration files
Read_conffile config/common
Read_conffile config/bootstrap
Read_conffile config/chroot
Read_conffile config/binary
Read_conffile config/source
Read_conffile "${LH_CONFIG}"
Set_defaults

if [ "${LH_BOOTSTRAP}" != "copy" ]
then
	exit 0
fi

Echo_message "Begin bootstrapping system..."

# Ensure that a system is built as root
lh_testroot

# Checking stage file
Check_stagefile .stage/bootstrap

# Checking lock file
Check_lockfile .lock

# Creating lock file
Create_lockfile .lock

# Copying host system
find / ! -name /proc ! -name /sys ! -name "$(dirname ${PWD})"  | xargs cp -a chroot

# Creating stage file
Create_stagefile .stage/bootstrap
