#!/bin/sh

# lh_build(1) - build a Debian Live system
# Copyright (C) 2006-2008 Daniel Baumann <daniel@debian.org>
#
# live-helper comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
# This is free software, and you are welcome to redistribute it
# under certain conditions; see COPYING for details.

set -e

# Including common functions
LH_BASE="${LH_BASE:-/usr/share/live-helper}"

for FUNCTION in "${LH_BASE}"/functions/*.sh
do
	. "${FUNCTION}"
done

# Setting static variables
DESCRIPTION="build a Debian Live system"
HELP=""
USAGE="${PROGRAM} [--force]"

Arguments "${@}"

if [ ! -d config ]
then
	Echo_warning "No config/ directory; using defaults for all options"
fi

if [ "$(pwd)" = "/" ]
then
	Echo_error "Cannot build live image from the root directory (/)"
	exit 1
fi

if echo $(pwd) | grep -qs " "
then
	Echo_error "Cannot build live image from a directory containing spaces"
	exit 1
fi

# Reading configuration files
Read_conffile config/all config/common config/bootstrap config/chroot config/binary config/source
Set_defaults

# Checking defaults
Check_defaults

# Bootstrapping system
lh_bootstrap ${*}

# Customizing chroot
lh_chroot ${*}

# Building binary images
lh_binary ${*}

# Building source images
lh_source ${*}
