#!/bin/sh

# lh_binary_virtual-hdd(1) - build binary virtual-hdd image
# Copyright (C) 2006-2009 Daniel Baumann <daniel@debian.org>
#
# live-helper comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
# This is free software, and you are welcome to redistribute it
# under certain conditions; see COPYING for details.

set -e

# Including common functions
. "${LH_BASE:-/usr/share/live-helper}"/live-helper.sh

# Setting static variables
DESCRIPTION="$(Echo 'build binary image')"
HELP=""
USAGE="${PROGRAM} [--force]"

Arguments "${@}"

# Reading configuration files
Read_conffiles config/all config/common config/bootstrap config/chroot config/binary config/source
Set_defaults

if ! In_list virtual-hdd "${LH_BINARY_IMAGES}"
then
	exit 0
fi

Echo_message "Begin building binary virtual-hdd image..."

# Requiring stage file
Require_stagefile .stage/config .stage/bootstrap .stage/chroot_proc

# Checking stage file
Check_stagefile .stage/binary_virtual-hdd

# Checking lock file
Check_lockfile .lock

# Creating lock file
Create_lockfile .lock

if [ "${LH_CHROOT_BUILD}" = "enabled" ]
then
	case "${LH_BINARY_FILESYSTEM}" in
		ext2|ext3)
			Check_package chroot/sbin/mkfs.ext2 e2fsprogs
			;;
	esac
fi

# Restoring cache
Restore_cache cache/packages_binary

# Installing depends
Install_package

# Remove old binary
if [ -f binary-virtual.img ]
then
	rm -f binary-virtual.img
fi

Echo_message "Creating virtual disk image..."
dd if=/dev/zero of=binary-virtual.img bs=1024k count=0 seek=${LH_VIRTUAL_ROOT_SIZE}

if [ "${LH_CHROOT_BUILD}" = "enabled" ]
then
	mv binary-virtual.img chroot

	case "${LH_BINARY_FILESYSTEM}" in
		ext2)
			Chroot chroot "mkfs.ext2 -F binary-virtual.img"
			;;

		ext3)
			Chroot chroot "mkfs.ext3 -F binary-virtual.img"
			;;
	esac

	mv chroot/binary-virtual.img ./
else
	case "${LH_BINARY_FILESYSTEM}" in
		ext2)
			mkfs.ext2 -F binary-virtual.img
			;;

		ext3)
			mkfs.ext3 -F binary-virtual.img
			;;
	esac
fi

mkdir -p binary.tmp
${LH_ROOT_COMMAND} mount -o loop binary-virtual.img binary.tmp
cp -a binary/ binary.tmp

${LH_ROOT_COMMAND} umount binary.tmp
rmdir binary.tmp

# Saving cache
Save_cache cache/packages_binary

# Removing depends
Remove_package

# Creating stage file
Create_stagefile .stage/binary_virtual-hdd
