#!/bin/sh

# lh_binary_linuximage(1) - install linux-image into binary
# Copyright (C) 2006-2007 Daniel Baumann <daniel@debian.org>
#
# live-helper comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
# This is free software, and you are welcome to redistribute it
# under certain conditions; see COPYING for details.

set -e

# Source common functions
for FUNCTION in /usr/share/live-helper/functions/*.sh
do
	. ${FUNCTION}
done

# Set static variables
DESCRIPTION="install linux-image into binary"
HELP=""
USAGE="${PROGRAM} [--force]"

Arguments "${@}"

# Reading configuration files
Read_conffile config/common
Read_conffile config/bootstrap
Read_conffile config/chroot
Read_conffile config/image
Set_defaults

# Requiring stage file
Require_stagefile .stage/bootstrap

# Checking lock file
Check_lockfile .lock

# Creating lock file
Create_lockfile .lock

# Checking stage file
Check_stagefile .stage/binary_linuximage

# Removing initrd backup files
rm -f chroot/boot/initrd*bak*

# Setting destination directory
case "${LIVE_BINARY_IMAGE}" in
	iso)
		DESTDIR="binary/live"
		;;

	net)
		DESTDIR="tftpboot"
		;;

	usb|hdd)
		DESTDIR="binary"
		;;
esac

# Temporary check for broken syslinux
if [ "${LIVE_BINARY_IMAGE}" = "iso" ]
then
	case "${LIVE_ARCHITECTURE}" in
		i386)
			DESTDIR="${DESTDIR}.386"
			;;
	esac
fi

# Creating directory
if [ ! -d "${DESTDIR}" ]
then
	mkdir -p "${DESTDIR}"
fi

# Installing linux-image
cp chroot/boot/vmlinuz* "${DESTDIR}"
cp chroot/boot/initrd.img* "${DESTDIR}"

# Creating stage file
Create_stagefile .stage/binary_linuximage
