#!/bin/sh

# lh_binary_localincludes(1) - copy files into binary

set -e

# Source common functions
for FUNCTION in /usr/share/live-helper/functions/*.sh
do
	. ${FUNCTION}
done

# Reading configuration files
Read_conffile config/common
Read_conffile config/chroot
Set_defaults

# Requiring stage file
Require_stagefile .stage/bootstrap

# Checking lock file
Check_lockfile .lock

# Creating lock file
Create_lockfile .lock

# Checking stage file
Check_stagefile .stage/binary_localincludes

if ls config/binary_localincludes/* &> /dev/null
then
	# Copying includes
	cd config/binary_localincludes
	find . | cpio -dmpu ../../binary
	cd "${OLDPWD}"

	# Creating stage file
	Create_stagefile .stage/binary_localincludes
fi
