#!/bin/sh

# lh_binary_tar(1) - build harddisk binary image
# Copyright (C) 2006-2009 Daniel Baumann <daniel@debian.org>
#
# live-helper comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
# This is free software, and you are welcome to redistribute it
# under certain conditions; see COPYING for details.

set -e

# Including common functions
. "${LH_BASE:-/usr/share/live-helper}"/live-helper.sh

# Setting static variables
DESCRIPTION="$(Echo 'build harddisk binary image')"
HELP=""
USAGE="${PROGRAM} [--force]"

Arguments "${@}"

# Reading configuration files
Read_conffiles config/all config/common config/bootstrap config/chroot config/binary config/source
Set_defaults

if ! In_list tar "${LH_BINARY_IMAGES}"
then
	exit 0
fi

Echo_message "Begin building binary harddisk image..."

# Requiring stage file
Require_stagefile .stage/config .stage/bootstrap

# Checking stage file
Check_stagefile .stage/binary_tar

# Checking lock file
Check_lockfile .lock

# Creating lock file
Create_lockfile .lock

# Remove old binary
rm -f binary.tar.gz

tar cf binary-tar.tar binary
gzip ${GZIP_OPTIONS} binary-tar.tar

# Creating stage file
Create_stagefile .stage/binary_tar
