#!/bin/sh

# lh_bootstrap_debootstrap(1) - bootstrap a Debian system with debootstrap(8)
# Copyright (C) 2006-2007 Daniel Baumann <daniel@debian.org>
#
# live-helper comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
# This is free software, and you are welcome to redistribute it
# under certain conditions; see COPYING for details.

set -e

# Source common functions
for FUNCTION in /usr/share/live-helper/functions/*.sh
do
	. ${FUNCTION}
done

# Set static variables
DESCRIPTION="bootstrap a Debian system with debootstrap(8)"
HELP=""
USAGE="${PROGRAM} [--force]"

Arguments "${@}"

# Ensure that a system is built as root
lh_testroot

# Starting helper
Echo_debug "Init ${PROGRAM}"

# Reading configuration files
Read_conffile config/common
Read_conffile config/bootstrap
Set_defaults

if [ "${LH_BOOTSTRAP}" != "debootstrap" ]
then
	exit 0
fi

# Checking stage file
Check_stagefile .stage/bootstrap

# Checking lock file
Check_lockfile .lock

# Creating lock file
Create_lockfile .lock

# Creating chroot directory
if [ ! -d chroot ]
then
	mkdir -p chroot
fi

# Setting debootstrap options
if [ -n "${LIVE_ARCHITECTURE}" ]
then
	DEBOOTSTRAP_OPTIONS="${DEBOOTSTRAP_OPTIONS} --arch ${LIVE_ARCHITECTURE}"
fi

if [ -n "${LIVE_BOOTSTRAP_CONFIG}" ]
then
	LIVE_DEBOOTSTRAP_SCRIPT="/usr/lib/debootstrap/scripts/${LIVE_BOOTSTRAP_CONFIG}"
fi

if [ "${VERBOSE}" = "true" ]
then
	DEBOOTSTRAP_OPTIONS="${DEBOOTSTRAP_OPTIONS} --verbose"
fi

if [ -x "/usr/sbin/debootstrap" ]
then
	if [ "${LH_CACHE}" = "enabled" ]
	then
		# Restore old cache
		if [ -d cache/chroot_bootstrap ]
		then
			cp -a cache/chroot_bootstrap/* chroot

			# Creating stage file
			Create_stagefile .stage/bootstrap

			exit 0
		fi

		if [ -d cache/bootstrap ]
		then
			mkdir -p chroot/var/cache/apt/archives
			cp cache/bootstrap/*.deb chroot/var/cache/apt/archives
		fi

		# Executing debootstrap (download-only)
		debootstrap ${DEBOOTSTRAP_OPTIONS} --download-only "${LIVE_DISTRIBUTION}" chroot "${LIVE_MIRROR_BUILD}" "${LIVE_DEBOOTSTRAP_SCRIPT}"

		# Removing old cache
		if [ -d cache/bootstrap ]
		then
			rm -f cache/bootstrap/*.deb
		fi

		# Saving new cache
		if [ ! -d cache/bootstrap ]
		then
			mkdir -p cache/bootstrap
		fi

		cp chroot/var/cache/apt/archives/*.deb cache/bootstrap
	fi

	# Executing debootstrap (regular run)
	debootstrap ${DEBOOTSTRAP_OPTIONS} "${LIVE_DISTRIBUTION}" chroot "${LIVE_MIRROR_BUILD}" "${LIVE_DEBOOTSTRAP_SCRIPT}"

	# Removing bootstrap cache
	rm -rf chroot/var/cache/apt/archives/*.deb

	# Saving new cache
	if [ "${LH_CACHE}" = "enabled" ]
	then
		if [ -d cache/chroot_bootstrap ]
		then
			rm -rf cache/chroot_bootstrap
		fi

		cp -a chroot cache/chroot_bootstrap
	fi

	# Creating stage file
	Create_stagefile .stage/bootstrap
else
	echo "E: Can't process file /usr/bin/debootstrap (FIXME)"
	exit 1
fi
