#!/bin/sh

# lh_bootstrap_cdebootstrap(1) - bootstrap a Debian system with cdebootstrap(1)
# Copyright (C) 2006-2009 Daniel Baumann <daniel@debian.org>
#
# live-helper comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
# This is free software, and you are welcome to redistribute it
# under certain conditions; see COPYING for details.

set -e

# Including common functions
. "${LH_BASE:-/usr/share/live-helper}"/live-helper.sh

# Setting static variables
DESCRIPTION="$(Echo 'bootstrap a Debian system with cdebootstrap(1)')"
HELP=""
USAGE="${PROGRAM} [--force]"

Arguments "${@}"

# Reading configuration files
Read_conffiles config/all config/common config/bootstrap config/chroot config/binary config/source
Set_defaults

if [ "${LH_BOOTSTRAP}" != "cdebootstrap" ] && [ "${LH_BOOTSTRAP}" != "cdebootstrap-static" ]
then
	exit 0
fi

# Check architecture
Check_crossarchitecture

Echo_message "Begin bootstrapping system..."

Check_package /usr/bin/${LH_BOOTSTRAP} cdebootstrap

# Ensure that a system is built as root
lh testroot

# Checking stage file
Check_stagefile .stage/bootstrap
Check_stagefile .stage/bootstrap_cache.restore

# Checking lock file
Check_lockfile .lock

# Creating lock file
Create_lockfile .lock

# Creating chroot directory
mkdir -p chroot

# Setting cdebootstrap options
if [ -n "${LH_ARCHITECTURE}" ]
then
	CDEBOOTSTRAP_OPTIONS="${CDEBOOTSTRAP_OPTIONS} --arch=${LH_ARCHITECTURE}"
fi

if [ -n "${LH_BOOTSTRAP_CONFIG}" ]
then
	CDEBOOTSTRAP_OPTIONS="${CDEBOOTSTRAP_OPTIONS} --suite-config=${LH_BOOTSTRAP_CONFIG}"
fi

if [ -n "${LH_BOOTSTRAP_INCLUDE}" ]
then
	CDEBOOTSTRAP_OPTIONS="${CDEBOOTSTRAP_OPTIONS} --include=$(echo ${LH_BOOTSTRAP_INCLUDE} | sed 's|  *|,|g')"
fi

if [ -n "${LH_BOOTSTRAP_EXCLUDE}" ]
then
	CDEBOOTSTRAP_OPTIONS="${CDEBOOTSTRAP_OPTIONS} --exclude=$(echo ${LH_BOOTSTRAP_EXCLUDE} | sed 's|  *|,|g')"
fi

if [ -n "${LH_BOOTSTRAP_KEYRING}" ]
then
	CDEBOOTSTRAP_OPTIONS="${CDEBOOTSTRAP_OPTIONS} --keyring=${LH_BOOTSTRAP_KEYRING}"
fi

if [ -z "${LH_BOOTSTRAP_FLAVOUR}" ]
then
	case "${LH_PACKAGES_LISTS}" in
		stripped|minimal)
			CDEBOOTSTRAP_OPTIONS="${CDEBOOTSTRAP_OPTIONS} --flavour=minimal"
			;;
		*)
			CDEBOOTSTRAP_OPTIONS="${CDEBOOTSTRAP_OPTIONS} --flavour=standard"
			;;
	esac
else
	case "${LH_BOOTSTRAP_FLAVOUR}" in
		stripped|minimal)
			CDEBOOTSTRAP_OPTIONS="${CDEBOOTSTRAP_OPTIONS} --flavour=minimal"
			;;

		*)
			CDEBOOTSTRAP_OPTIONS="${CDEBOOTSTRAP_OPTIONS} --flavour=${LH_BOOTSTRAP_FLAVOUR}"
			;;
	esac
fi

if [ "${_DEBUG}" = "enabled" ]
then
	CDEBOOTSTRAP_OPTIONS="${CDEBOOTSTRAP_OPTIONS} --debug"
fi

if [ "${_QUIET}" = "enabled" ]
then
	CDEBOOTSTRAP_OPTIONS="${CDEBOOTSTRAP_OPTIONS} --quiet"
fi

if [ "${_VERBOSE}" = "enabled" ]
then
	CDEBOOTSTRAP_OPTIONS="${CDEBOOTSTRAP_OPTIONS} --verbose"
fi

if [ "${LH_APT_SECURE}" = "disabled" ]
then
	CDEBOOTSTRAP_OPTIONS="${CDEBOOTSTRAP_OPTIONS} --allow-unauthenticated"
fi

if [ -x "/usr/bin/cdebootstrap" ] || [ -x "/usr/bin/cdebootstrap-static" ]
then
	if [ "${LH_CACHE_PACKAGES}" = "enabled" ]
	then
		if [ -d cache/packages_bootstrap ]
		then
			mkdir -p chroot/var/cache/bootstrap
			cp cache/packages_bootstrap/*.deb chroot/var/cache/bootstrap
		fi

		Echo_breakage "Running ${LH_BOOTSTRAP} (download-only)... "
		${LH_ROOT_COMMAND} ${LH_BOOTSTRAP} ${CDEBOOTSTRAP_OPTIONS} --download-only "${LH_DISTRIBUTION}" chroot "${LH_MIRROR_BOOTSTRAP}"

		if [ -n "${LH_ROOT_COMMAND}" ]
		then
			${LH_ROOT_COMMAND} chown -R $(whoami):$(whoami) chroot
		fi

		# Removing old cache
		if [ -d cache/packages_bootstrap ]
		then
			rm -f cache/packages_bootstrap/*.deb
		fi

		# Saving new cache
		mkdir -p cache/packages_bootstrap

		cp chroot/var/cache/bootstrap/*.deb cache/packages_bootstrap
	fi

	Echo_breakage "Running ${LH_BOOTSTRAP}... "
	${LH_ROOT_COMMAND} ${LH_BOOTSTRAP} ${CDEBOOTSTRAP_OPTIONS} "${LH_DISTRIBUTION}" chroot "${LH_MIRROR_BOOTSTRAP}"

	if [ -n "${LH_ROOT_COMMAND}" ]
	then
		${LH_ROOT_COMMAND} chown -R $(whoami):$(whoami) chroot
	fi

	# Remove cdebootstrap-helper-diverts (needed at least for minimal flavours)
	case "${LH_PACKAGES_LISTS}" in
		stripped|minimal)
			Chroot chroot "dpkg -P cdebootstrap-helper-diverts"
			;;
	esac

	# Deconfiguring cdebootstrap configurations
	rm -f chroot/etc/apt/sources.list
	rm -f chroot/etc/hosts
	rm -f chroot/etc/resolv.conf

	# Removing bootstrap cache
	rm -rf chroot/var/cache/bootstrap

	# Creating stage file
	Create_stagefile .stage/bootstrap
else
	Echo_error "Can't process file /usr/bin/${LH_BOOTSTRAP} (FIXME)"
	exit 1
fi
