#!/bin/sh

# lh_binary_md5sum(1) - create binary md5sums
# Copyright (C) 2006-2007 Daniel Baumann <daniel@debian.org>
#
# live-helper comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
# This is free software, and you are welcome to redistribute it
# under certain conditions; see COPYING for details.

set -e

# Including common functions
LH_BASE="${LH_BASE:-/usr/share/live-helper}"

for FUNCTION in "${LH_BASE}"/functions/*.sh
do
	. "${FUNCTION}"
done

# Setting static variables
DESCRIPTION="create binary md5sums"
HELP=""
USAGE="${PROGRAM} [--force]"

Arguments "${@}"

# Reading configuration files
Read_conffile config/common
Read_conffile config/bootstrap
Read_conffile config/chroot
Read_conffile config/binary
Read_conffile config/source
Set_defaults

Echo_message "Begin creating binary md5sum.txt..."

# Requiring stage file
Require_stagefile .stage/bootstrap

# Checking stage file
Check_stagefile .stage/binary_md5sum

# Checking lock file
Check_lockfile .lock

# Creating lock file
Create_lockfile .lock

# Remove old md5sums
if [ -f binary/md5sum.txt ]
then
	rm -f binary/md5sum.txt
fi

# Calculating md5sums
cd binary
find . -type f | sort | grep -v 'isolinux/isolinux.bin' | grep -v 'boot/grub/stage2_eltorito' | xargs md5sum > ../md5sum.txt

cat > md5sum.txt << EOF
This file contains the list of md5 checksums of all files on this medium.

You can verify them automatically with the 'integrity-check' boot parameter,
or, manually with: 'md5sum -c md5sum.txt'.


EOF

cat ../md5sum.txt >> md5sum.txt
rm -f ../md5sum.txt

cd "${OLDPWD}"

# Creating stage file
Create_stagefile .stage/binary_md5sum
