#!/bin/sh

# lh_chroot_local-packages(1) - install local packages into chroot
# Copyright (C) 2006-2007 Daniel Baumann <daniel@debian.org>
#
# live-helper comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
# This is free software, and you are welcome to redistribute it
# under certain conditions; see COPYING for details.

set -e

# Including common functions
LH_BASE="${LH_BASE:-/usr/share/live-helper}"

for FUNCTION in "${LH_BASE}"/functions/*.sh
do
	. "${FUNCTION}"
done

# Setting static variables
DESCRIPTION="install local packages into chroot"
HELP=""
USAGE="${PROGRAM} [--force]"

Arguments "${@}"

# Reading configuration files
Read_conffile config/common
Read_conffile config/bootstrap
Read_conffile config/chroot
Read_conffile config/binary
Read_conffile config/source
Read_conffile "${LH_CONFIG}"
Set_defaults

Echo_message "Begin installing local packages..."

# Requiring stage file
Require_stagefile .stage/bootstrap

# Checking stage file
Check_stagefile .stage/chroot_local-packages

# Checking lock file
Check_lockfile .lock

# Creating lock file
Create_lockfile .lock

if ls config/chroot_local-packages/*.deb > /dev/null 2>&1
then
	# Restoring cache
	Restore_cache cache/packages_local-packages

	# Copying packages
	if ls config/chroot_local-packages/*_"${LH_ARCHITECTURE}".deb > /dev/null 2>&1
	then
		cp config/chroot_local-packages/*_"${LH_ARCHITECTURE}".deb chroot/root
	fi

	if ls config/chroot_local-packages/*_all.deb > /dev/null 2>&1
	then
		cp config/chroot_local-packages/*_all.deb chroot/root
	fi

	# Installing packages
        Chroot "find /root -name *.deb" > chroot/root/local-packages
	Chroot "xargs --arg-file=/root/local-packages dpkg -i" || true

	# Cleaning dependencies
	Apt install -f

	# Removing package files
	rm -f chroot/root/*.deb
	rm -f chroot/root/local-packages

	# Saving cache
	Save_cache cache/packages_local-packages

	# Creating stage file
	Create_stagefile .stage/chroot_local-packages
fi
