#!/bin/sh

# lh_chroot_linuximage(1) - manage /etc/kernel-img.conf

set -e

# Source common functions
for FUNCTION in /usr/share/live-helper/functions/*.sh
do
	. ${FUNCTION}
done

# Reading configuration files
Read_conffile config/common
Read_conffile config/chroot
Set_defaults

# Requiring stage file
Require_stagefile .stage/bootstrap

# Checking lock file
Check_lockfile .lock

# Creating lock file
Create_lockfile .lock

case "${1}" in
	install)
		# Checking stage file
		Check_stagefile .stage/chroot_linuximage

		if [ -f chroot/etc/kernel-img.conf ]
		then
			# Saving kernel-img.conf
			cp chroot/etc/kernel-img.conf chroot/etc/kernel-img.conf.old
		fi

		# Configuring kernel-img.conf
		echo "do_initrd = Yes"  >> chroot/etc/kernel-img.conf

		# Creating stage file
		Create_stagefile .stage/chroot_linuximage

		# Installing linux-image, modules and casper
		case "${LH_APT}" in
			apt|apt-get)
				Chroot "apt-get install --yes ${LIVE_KERNEL_PACKAGES}"
				;;

			aptitude)
				Chroot "aptitude install --assume-yes ${LIVE_KERNEL_PACKAGES}"
				;;
		esac
		;;

	remove)
		if [ -f chroot/etc/kernel-img.conf.old ]
		then
			# Restoring kernel-img.conf file
			mv chroot/etc/kernel-img.conf.old chroot/etc/kernel-img.conf
		else
			# Removing kernel-img.conf file
			rm -f chroot/etc/kernel-img.conf
		fi

		# Removing stage file
		rm -f .stage/chroot_linuximage
		;;

	*)
		echo "Usage: ${0} {install|remove}"
		exit 1
		;;
esac
