#!/bin/sh

# lh_chroot_hooks(1) - execute hooks in chroot
# Copyright (C) 2006-2007 Daniel Baumann <daniel@debian.org>
#
# live-helper comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
# This is free software, and you are welcome to redistribute it
# under certain conditions; see COPYING for details.

set -e

# Source common functions
for FUNCTION in /usr/share/live-helper/functions/*.sh
do
	. ${FUNCTION}
done

# Set static variables
DESCRIPTION="execute hooks in chroot"
HELP=""
USAGE="${PROGRAM} [--force]"

Arguments "${@}"

Echo_debug "Init ${PROGRAM}"

# Reading configuration files
Read_conffile config/common
Read_conffile config/bootstrap
Read_conffile config/chroot
Read_conffile config/binary
Read_conffile config/source
Set_defaults

Breakpoint "chroot_hooks: Init"

# Requiring stage file
Require_stagefile .stage/bootstrap

# Checking stage file
Check_stagefile .stage/chroot_hooks

# Checking lock file
Check_lockfile .lock

# Creating lock file
Create_lockfile .lock

# Processing hooks
for HOOK in ${LIVE_PACKAGES_LISTS} ${LIVE_TASKS}
do
	if [ -f /usr/share/live-helper/hooks/"${HOOK}" ]
	then
		# Copying hook
		cp /usr/share/live-helper/hooks/"${HOOK}" chroot/root

		# Making hook executable
		if [ ! -x chroot/root/"${HOOK}" ]
		then
			chmod +x chroot/root/"${HOOK}"
		fi

		# Executing hook
		Chroot "/root/${HOOK}"

		# Removing hook
		rm -f chroot/root/"${HOOK}"

		# Creating stage file
		Create_stagefile .stage/chroot_hooks
	fi
done

if [ -n "${LIVE_HOOKS}" ] && [ "${LIVE_HOOKS}" != "none" ]
then
	LIVE_DEBCONF_FRONTEND="readline" LIVE_DEBCONF_PRIORITY="low" LIVE_DEBCONF_NOWARNINGS="no" Chroot "${LIVE_HOOKS}"
fi
