#!/bin/sh

# lh_chroot_symlinks(1) - convert symlinks
# Copyright (C) 2006-2009 Daniel Baumann <daniel@debian.org>
#
# live-helper comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
# This is free software, and you are welcome to redistribute it
# under certain conditions; see COPYING for details.

set -e

# Including common functions
. "${LH_BASE:-/usr/share/live-helper}"/live-helper.sh

# Setting static variables
DESCRIPTION="$(Echo 'convert symlinks')"
HELP=""
USAGE="${PROGRAM} [--force]"

Arguments "${@}"

# Reading configuration files
Read_conffiles config/all config/common config/bootstrap config/chroot config/binary config/source
Set_defaults

if [ "${LH_SYMLINKS}" != "enabled" ]
then
	exit 0
fi

Echo_message "Begin converting symlinks..."

# Requiring stage file
Require_stagefile .stage/config .stage/bootstrap

# Checking stage file
Check_stagefile .stage/chroot_symlinks

# Checking lock file
Check_lockfile .lock

# Creating lock file
Create_lockfile .lock

# Checking depends
Check_package chroot/usr/bin/symlinks symlinks

# Installing depends
Install_package

# Converting symlinks
Chroot chroot "symlinks -c -r -s /"

# Removing depends
Remove_package

# Creating stage file
Create_stagefile .stage/chroot_symlinks
