#!/bin/sh

# lh_chroot_localincludes(1) - copy files into chroot

set -e

# Source common functions
for FUNCTION in /usr/share/live-helper/functions/*.sh
do
	. ${FUNCTION}
done

# Reading configuration files
Read_conffile config/common
Read_conffile config/chroot
Set_defaults

# Requiring stage file
Require_stagefile .stage/bootstrap

# Checking stage file
Check_stagefile .stage/chroot_localincludes

# Checking lock file
Check_lockfile .lock

# Creating lock file
Create_lockfile .lock

if ls config/chroot_localincludes/* &> /dev/null
then
	# Copying includes
	cd config/chroot_localincludes
	find . | cpio -dmpu ../../chroot
	cd "${OLDPWD}"

	# Creating stage file
	Create_stagefile .stage/chroot_localincludes
fi
