#!/bin/sh

# lh_chroot_packageslist(1) - install packages list into chroot

set -e

# Source common functions
for FUNCTION in /usr/share/live-helper/functions/*.sh
do
	. ${FUNCTION}
done

# Reading configuration files
Read_conffile config/common
Read_conffile config/chroot
Set_defaults

# Requiring stage file
Require_stagefile .stage/bootstrap

# Checking stage file
Check_stagefile .stage/chroot_packageslist

# Checking lock file
Check_lockfile .lock

# Creating lock file
Create_lockfile .lock

if [ -n "${LIVE_PACKAGES_LIST}" ]
then
	# Restore old cache
	if [ -d cache/chroot_packageslist ]
	then
		cp cache/chroot_packageslist/*.deb chroot/var/cache/apt/archives
	fi

	for LIST in ${LIVE_PACKAGES_LIST}
	do
		if [ -f /usr/share/live-helper/lists/"${LIST}" ]
		then
			# Copying package list
			grep -v "^#" /usr/share/live-helper/lists/"${LIST}" > chroot/root/"${LIST}"

			# Installing package list
			case "${LH_APT}" in
				apt|apt-get)
					Chroot "xargs --arg-file=/root/${LIST} apt-get install --yes"
					;;

				aptitude)
					Chroot "xargs --arg-file=/root/${LIST} aptitude install --assume-yes"
					;;
			esac

			# Removing package list
			rm -f chroot/root/"${LIST}"
		fi
	done

	# Saving new cache
	Chroot "apt-get autoclean"

	if ls chroot/var/cache/apt/archives/*.deb &> /dev/null
	then
		if [ ! -d cache/chroot_packageslist ]
		then
			mkdir -p cache/chroot_packageslist
		fi

		mv -f chroot/var/cache/apt/archives/*.deb cache/chroot_packageslist
	fi

	# Creating stage file
	Create_stagefile .stage/chroot_packageslist
fi
