#!/bin/sh

# lh_chroot_interactive(1) - make build interactive
# Copyright (C) 2006-2007 Daniel Baumann <daniel@debian.org>
#
# live-helper comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
# This is free software, and you are welcome to redistribute it
# under certain conditions; see COPYING for details.

set -e

# Including common functions
LH_BASE="${LH_BASE:-/usr/share/live-helper}"

for FUNCTION in "${LH_BASE}"/functions/*.sh
do
	. "${FUNCTION}"
done

# Setting static variables
DESCRIPTION="make build interactive"
HELP=""
USAGE="${PROGRAM} [--force]"

Arguments "${@}"

# Reading configuration files
Read_conffile config/common
Read_conffile config/bootstrap
Read_conffile config/chroot
Read_conffile config/binary
Read_conffile config/source
Set_defaults

if [ "${LIVE_INTERACTIVE}" = "disabled" ]
then
	exit 0
fi

Echo_message "Begin interactive build..."

# Requiring stage file
Require_stagefile .stage/bootstrap

# Checking stage file
Check_stagefile .stage/chroot_interactive

# Checking lock file
Check_lockfile .lock

# Creating lock file
Create_lockfile .lock

case "${LIVE_INTERACTIVE}" in
	enabled|shell)
		echo "Pausing build: starting interactive shell..."
			Chroot "/bin/bash --login"
		;;
		x11)
		echo "Pausing build: starting interactive X11..."
			Chroot "startx"
		;;
		xnest)
		echo "Pausing build: starting interactive Xnest..."
			#Chroot "" # FIXME
		;;
esac

# Creating stage file
Create_stagefile .stage/chroot_symlinks
