#!/bin/sh

# lh_chroot_install-packages(1) - install queued packages into chroot
# Copyright (C) 2006-2008 Daniel Baumann <daniel@debian.org>
#
# live-helper comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
# This is free software, and you are welcome to redistribute it
# under certain conditions; see COPYING for details.

set -e

# Including common functions
LH_BASE="${LH_BASE:-/usr/share/live-helper}"

for FUNCTION in "${LH_BASE}"/functions/*.sh
do
	. "${FUNCTION}"
done

# Setting static variables
DESCRIPTION="install queued packages into chroot"
HELP=""
USAGE="${PROGRAM} [--force]"

Arguments "${@}"

# Reading configuration files
Read_conffile config/all config/common config/bootstrap config/chroot config/binary config/source
Set_defaults

Echo_message "Begin installing packages..."

# Requiring stage file
Require_stagefile .stage/bootstrap

# Checking stage file
Check_stagefile .stage/chroot_install-packages

# Checking lock file
Check_lockfile .lock

# Creating lock file
Create_lockfile .lock

if [ -e chroot/root/chroot_packages ] && [ -s chroot/root/chroot_packages ]
then
	# Restoring cache
	Restore_cache cache/packages_chroot

	# Ensure chroot_local-packages override all other packages
	if [ -e chroot/etc/apt/preferences ]
	then
		cp chroot/etc/apt/preferences chroot/etc/apt/preferences.live
	fi

	cat >> chroot/etc/apt/preferences.live <<EOF
Package: *
Pin: release o=chroot_local-packages
Pin-Priority: 1001
EOF

	# Installing packages
	case "${LH_APT}" in
		apt|apt-get)
			Chroot "xargs --arg-file=/root/chroot_packages apt-get ${APT_OPTIONS} -o Dir::Etc::preferences=preferences.live install"
			;;

		aptitude)
			Chroot "xargs --arg-file=/root/chroot_packages aptitude ${APTITUDE_OPTIONS} -o Dir::Etc::preferences=preferences.live install"
			;;
	esac

	# Tidying up
	rm -f chroot/root/chroot_packages
	rm -f chroot/etc/apt/preferences.live

	# Saving cache
	Save_cache cache/packages_chroot

	# Creating stage file
	Create_stagefile .stage/chroot_install-packages
fi
