#!/bin/sh

# lh_chroot_dpkg(1) - manage /sbin/dpkg
# Copyright (C) 2006-2009 Daniel Baumann <daniel@debian.org>
#
# live-helper comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
# This is free software, and you are welcome to redistribute it
# under certain conditions; see COPYING for details.

set -e

# Including common functions
. "${LH_BASE:-/usr/share/live-helper}"/live-helper.sh

# Setting static variables
DESCRIPTION="$(Echo 'manage /sbin/dpkg')"
HELP=""
USAGE="${PROGRAM} {install|remove} [--force]"

Arguments "${@}"

# Reading configuration files
Read_conffiles config/all config/common config/bootstrap config/chroot config/binary config/source
Set_defaults

# Requiring stage file
Require_stagefile .stage/config .stage/bootstrap

case "${1}" in
	install)
		Echo_message "Configuring file /sbin/start-stop-daemon"

		# Checking stage file
		Check_stagefile .stage/chroot_dpkg

		# Checking lock file
		Check_lockfile .lock

		# Creating lock file
		Create_lockfile .lock

		# Save start-stop-daemon program
		mv chroot/sbin/start-stop-daemon chroot/sbin/start-stop-daemon.orig

		# Create start-stop-daemon program

cat > chroot/sbin/start-stop-daemon << EOF
#!/bin/sh

exit 0
EOF

		chmod 755 chroot/sbin/start-stop-daemon

		# Creating stage file
		Create_stagefile .stage/chroot_dpkg
		;;

	remove)
		Echo_message "Deconfiguring file /sbin/start-stop-daemon"

		# Checking lock file
		Check_lockfile .lock

		# Creating lock file
		Create_lockfile .lock

		# Restore start-stop-daemon program
		mv chroot/sbin/start-stop-daemon.orig chroot/sbin/start-stop-daemon

		# Removing stage file
		rm -f .stage/chroot_dpkg
		;;

	*)
		Usage
		;;
esac
