#!/bin/sh

# lh_chroot_sysfs(1) - mount /sys
# Copyright (C) 2006-2007 Daniel Baumann <daniel@debian.org>
#
# live-helper comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
# This is free software, and you are welcome to redistribute it
# under certain conditions; see COPYING for details.

set -e

# Source common functions
for FUNCTION in /usr/share/live-helper/functions/*.sh
do
	. ${FUNCTION}
done

# Set static variables
DESCRIPTION="mount /sys"
HELP=""
USAGE="${PROGRAM} {install|remove} [--force]"

Arguments "${@}"

# Ensure that a system is built as root
lh_testroot

Echo_debug "Init ${PROGRAM}"

# Reading configuration files
Read_conffile config/common
Read_conffile config/bootstrap
Read_conffile config/chroot
Read_conffile config/binary
Read_conffile config/source
Set_defaults

Breakpoint "chroot_sysfs: Init"

# Requiring stage file
Require_stagefile .stage/bootstrap

case "${1}" in
	install)
		# Checking stage file
		Check_stagefile .stage/chroot_sysfs

		# Checking lock file
		Check_lockfile .lock

		# Creating lock file
		Create_lockfile .lock

		if [ ! -d chroot/sys ]
		then
			# Create mountpoint
			mkdir -p chroot/sys
		fi

		# Mounting /sys
		${LH_ROOT_COMMAND} mount sysfs-live -t sysfs chroot/sys

		# Creating stage file
		Create_stagefile .stage/chroot_sysfs
		;;

	remove)
		# Checking lock file
		Check_lockfile .lock

		# Creating lock file
		Create_lockfile .lock

		# Unmounting /sys
		#fuser -km chroot/sys
		${LH_ROOT_COMMAND} umount chroot/sys > /dev/null 2>&1

		# Removing stage file
		rm -f .stage/chroot_sysfs
		;;

	*)
		Usage
		;;
esac
