#!/bin/sh

# lh_chroot_hostname(1) - manage /etc/hostname
# Copyright (C) 2006-2007 Daniel Baumann <daniel@debian.org>
#
# live-helper comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
# This is free software, and you are welcome to redistribute it
# under certain conditions; see COPYING for details.

set -e

# Including common functions
LH_BASE="${LH_BASE:-/usr/share/live-helper}"

for FUNCTION in "${LH_BASE}"/functions/*.sh
do
	. "${FUNCTION}"
done

# Setting static variables
DESCRIPTION="manage /etc/hostname"
HELP=""
USAGE="${PROGRAM} {install|remove} [--force]"

Arguments "${@}"

# Reading configuration files
Read_conffile config/common
Read_conffile config/bootstrap
Read_conffile config/chroot
Read_conffile config/binary
Read_conffile config/source
Set_defaults

# Requiring stage file
Require_stagefile .stage/bootstrap

case "${1}" in
	install)
		Echo_message "Configuring file /etc/hostname"

		# Checking stage file
		Check_stagefile .stage/chroot_hostname

		# Checking lock file
		Check_lockfile .lock

		# Creating lock file
		Create_lockfile .lock

		if [ -f chroot/etc/hostname ]
		then
			# Save hostname file
			mv chroot/etc/hostname chroot/etc/hostname.orig
		fi

		# Create hostname file
		echo "localhost.localdomain" > chroot/etc/hostname

		# Set hostname
		Chroot "hostname -F /etc/hostname"

		# Creating stage file
		Create_stagefile .stage/chroot_hostname
		;;

	remove)
		Echo_message "Deconfiguring file /etc/hostname"

		# Checking lock file
		Check_lockfile .lock

		# Creating lock file
		Create_lockfile .lock

		if [ -f chroot/etc/hostname.orig ]
		then
			# Restore hostname file
			mv chroot/etc/hostname.orig chroot/etc/hostname
		else
			# Remove hostname file
			rm -f chroot/etc/hostname
		fi

		# Set hostname (somehow this seems to be really needed :/)
		if [ -f /etc/hostname ]
		then
			hostname -F /etc/hostname
		fi

		# Removing stage file
		rm -f .stage/chroot_hostname
		;;

	*)
		Usage
		;;
esac
