#!/bin/sh

# lh_chroot_debianchroot(1) - manage /etc/debian_chroot

set -e

# Source common functions
for FUNCTION in /usr/share/live-helper/functions/*.sh
do
	. ${FUNCTION}
done

# Reading configuration files
Read_conffile config/common
Read_conffile config/chroot
Set_defaults

# Requiring stage file
Require_stagefile .stage/bootstrap

# Checking lock file
Check_lockfile .lock

# Creating lock file
Create_lockfile .lock

case "${1}" in
	install)
		# Checking stage file
		Check_stagefile .stage/chroot_debianchroot

		if [ -f chroot/etc/debian_chroot ]
		then
			# Save chroot file
			mv chroot/etc/debian_chroot chroot/etc/debian_chroot.orig
		fi

		# Create chroot file
		echo "live" > chroot/etc/debian_chroot

		# Creating stage file
		Create_stagefile .stage/chroot_debianchroot
		;;

	remove)
		if [ -f chroot/etc/debian_chroot.orig ]
		then
			# Restore chroot file
			mv chroot/etc/debian_chroot.orig chroot/etc/debian_chroot
		else
			# Remove chroot file
			rm -f chroot/etc/debian_chroot
		fi

		# Removing stage file
		rm -f .stage/chroot_debianchroot
		;;

	*)
		echo "Usage: ${0} {install|remove}"
		exit 1
		;;
esac
