#!/bin/sh

# lh_chroot_hacks(1) - execute hacks in chroot

set -e

# Source common functions
for FUNCTION in /usr/share/live-helper/functions/*.sh
do
	. ${FUNCTION}
done

# Reading configuration files
Read_conffile config/common
Read_conffile config/chroot
Set_defaults

# Requiring stage file
Require_stagefile .stage/bootstrap

# Checking stage file
Check_stagefile .stage/chroot_hacks

# Checking lock file
Check_lockfile .lock

# Creating lock file
Create_lockfile .lock

# Removing udev mac caching rule
rm -f chroot/etc/udev/rules.d/z25_persistent-net.rules

case "${LIVE_BINARY_IMAGE}" in
	net)
		case "${LH_APT}" in
			apt|apt-get)
				Chroot "apt-get install --yes smbfs"
				;;

			aptitude)
				Chroot "aptitude install --assume-yes smbfs"
				;;
		esac

		if [ ! -d chroot/etc/initramfs-tools ]
		then
			mkdir chroot/etc/initramfs-tools
		fi

		# Configuring initramfs for NFS
cat >> chroot/etc/initramfs-tools/initramfs.conf << EOF
MODULES=netboot
BOOT=nfs
NFSROOT=auto
EOF
		;;
esac

# Update initramfs
Chroot "update-initramfs -tu"

# Creating stage file
Create_stagefile .stage/chroot_hacks
