#!/bin/sh

# lh_clean(1) - clean up system build directories
# Copyright (C) 2006-2007 Daniel Baumann <daniel@debian.org>
#
# live-helper comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
# This is free software, and you are welcome to redistribute it
# under certain conditions; see COPYING for details.

set -e

# Source common functions
for FUNCTION in /usr/share/live-helper/functions/*.sh
do
	. ${FUNCTION}
done

# Set static variables
DESCRIPTION="clean up system build directories"
HELP=""
USAGE="${PROGRAM} [all|cache|chroot|binary|lock|purge|stage|source]"

Arguments "${@}"

Echo_debug "Init ${PROGRAM}"

# Reading configuration files
Read_conffile config/common
Read_conffile config/bootstrap
Read_conffile config/chroot
Read_conffile config/binary
Read_conffile config/source
Set_defaults

case "${1}" in
	all)
		"${0}" chroot
		"${0}" binary
		"${0}" lock
		"${0}" stage
		"${0}" source

		if [ -d chroot ]
		then
			mkdir -p .stage
			touch .stage/bootstrap
		fi
		;;

	cache)
		${LH_ROOT_COMMAND} rm -rf cache
		;;

	chroot)
		${LH_ROOT_COMMAND} umount -f chroot/sys > /dev/null 2>&1 || true
		${LH_ROOT_COMMAND} umount -f chroot/proc > /dev/null 2>&1 || true
		${LH_ROOT_COMMAND} umount -f chroot/lib/init/rw > /dev/null 2>&1 || true
		${LH_ROOT_COMMAND} umount -f chroot/dev/shm > /dev/null 2>&1 || true
		${LH_ROOT_COMMAND} umount -f chroot/dev/pts > /dev/null 2>&1 || true
		${LH_ROOT_COMMAND} umount -f chroot/dev > /dev/null 2>&1 || true

		${LH_ROOT_COMMAND} rm -rf chroot chroot.tmp

		if [ "${PURGE}" != "true" ] && [ -d cache/stages_bootstrap ]
		then
			${LH_ROOT_COMMAND} cp -a cache/stages_bootstrap chroot
			mkdir -p .stage
			touch .stage/bootstrap
		fi

		rm -f .stage/chroot*
		;;

	binary)
		rm -f binary.iso
		rm -f binary.img
		rm -f binary*.tar.gz
		rm -f packages.txt

		rm -rf binary
		rm -rf tftpboot

		rm -f .stage/binary*
		;;

	lock)
		rm -f .lock
		;;

	purge)
		PURGE="true" "${0}" all
		"${0}" cache
		;;

	stage)
		rm -rf .stage
		;;

	source)
		rm -f source.iso
		rm -f source.img
		rm -f source*.tar
		rm -f source*.tar.gz

		rm -rf source

		rm -f .stage/source*
		;;

	*)
		"${0}" all
		;;
esac
