#!/bin/sh

# lh_chroot_localpackages(1) - install local packages into chroot

set -e

# Source common functions
for FUNCTION in /usr/share/live-helper/functions/*.sh
do
	. ${FUNCTION}
done

# Reading configuration files
Read_conffile config/common
Read_conffile config/chroot
Set_defaults

# Requiring stage file
Require_stagefile .stage/bootstrap

# Checking stage file
Check_stagefile .stage/chroot_localpackages

# Checking lock file
Check_lockfile .lock

# Creating lock file
Create_lockfile .lock

if ls config/chroot_localpackages/*.deb &> /dev/null
then
	# Restore old cache
	if [ -d cache/chroot_localpackages ]
	then
		cp cache/chroot_localpackages/*.deb chroot/var/cache/apt/archives
	fi

	# Copying packages
	cp config/chroot_localpackages/*.deb chroot/root

	# Installing packages
        Chroot "find /root -name *.deb" > chroot/root/localpackages
	Chroot "xargs --arg-file=/root/localpackages dpkg -i" || true

	# Cleaning dependencies
	case "${LH_APT}" in
		apt|apt-get)
			Chroot "apt-get install -f --yes"
			;;

		aptitude)
			Chroot "aptitude install -f --assume-yes"
			;;
	esac

	# Removing package files
	rm -f chroot/root/*.deb
	rm -f chroot/root/localpackages

	# Saving new cache
	Chroot "apt-get autoclean"

	if ls chroot/var/cache/apt/archives/*.deb &> /dev/null
	then
		if [ ! -d cache/chroot_localpackages ]
		then
			mkdir -p cache/chroot_localpackages
		fi

		mv -f chroot/var/cache/apt/archives/*.deb cache/chroot_localpackages
	fi

	# Creating stage file
	Create_stagefile .stage/chroot_localpackages
fi
