#!/bin/sh

# lh_clean(1) - clean up system build directories

set -e

# Source common functions
for FUNCTION in /usr/share/live-helper/functions/*.sh
do
	. ${FUNCTION}
done

# Ensure that a system is built as root
lh_testroot

# Reading configuration files
Read_conffile config/common
Set_defaults

case "${1}" in
	all)
		"${0}" chroot
		"${0}" binary
		"${0}" stage
		"${0}" source
		;;

	cache)
		rm -rf cache
		;;

	chroot)
		umount -f chroot/sys > /dev/null 2>&1 || true
		umount -f chroot/proc > /dev/null 2>&1 || true
		umount -f chroot/lib/init/rw > /dev/null 2>&1 || true
		umount -f chroot/dev/shm > /dev/null 2>&1 || true
		umount -f chroot/dev/pts > /dev/null 2>&1 || true
		umount -f chroot/dev > /dev/null 2>&1 || true

		rm -rf chroot
		;;

	binary)
		rm -rf binary

		rm -f binary.iso
		rm -f binary.img
		rm -f binary*.tar.gz
		rm -f packages.txt

		rm -f .stage/binary*
		;;

	stage)
		rm -rf .stage
		rm -f .lock
		;;

	source)
		rm -rf source

		rm -f source.iso
		rm -f source.img
		rm -f source*.tar.gz

		rm -f .stage/source*
		;;

	*)
		"${0}" all
		;;
esac
