#!/bin/sh

# lh_chroot_localpackageslists(1) - install local packages lists into chroot
# Copyright (C) 2006-2007 Daniel Baumann <daniel@debian.org>
#
# live-helper comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
# This is free software, and you are welcome to redistribute it
# under certain conditions; see COPYING for details.

set -e

# Source common functions
for FUNCTION in /usr/share/live-helper/functions/*.sh
do
	. ${FUNCTION}
done

# Set static variables
DESCRIPTION="install local packages into chroot"
HELP=""
USAGE="${PROGRAM} [--force]"

Arguments "${@}"

# Reading configuration files
Read_conffile config/common
Read_conffile config/chroot
Set_defaults

# Requiring stage file
Require_stagefile .stage/bootstrap

# Checking stage file
Check_stagefile .stage/chroot_localpackageslists

# Checking lock file
Check_lockfile .lock

# Creating lock file
Create_lockfile .lock

if ls config/chroot_localpackageslists/* &> /dev/null
then
	# Restoring cache
	Restore_cache cache/chroot_localpackageslists

	for PACKAGESLIST in config/chroot_localpackageslists/*
	do
		# Copying package list
		grep -v "^#" "${PACKAGESLIST}" > chroot/root/"`basename ${PACKAGESLIST}`"

		# Installing package list
		case "${LH_APT}" in
			apt|apt-get)
				Chroot "xargs --arg-file=/root/`basename ${PACKAGESLIST}` apt-get install --yes"
				;;

			aptitude)
				Chroot "xargs --arg-file=/root/`basename ${PACKAGESLIST}` aptitude install --assume-yes"
				;;
		esac

		# Removing package list
		rm -f chroot/root/"`basename ${PACKAGESLIST}`"
	done

	# Saving cache
	Save_cache cache/chroot_localpackageslists

	# Creating stage file
	Create_stagefile .stage/chroot_localpackageslists
fi
