#!/bin/sh

# lh_chroot_local-packages(1) - queue install of local packages into chroot
# Copyright (C) 2006-2008 Daniel Baumann <daniel@debian.org>
#
# live-helper comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
# This is free software, and you are welcome to redistribute it
# under certain conditions; see COPYING for details.

set -e

# Including common functions
LH_BASE="${LH_BASE:-/usr/share/live-helper}"

for FUNCTION in "${LH_BASE}"/functions/*.sh
do
	. "${FUNCTION}"
done

# Setting static variables
DESCRIPTION="queue install of local packages into chroot"
HELP=""
USAGE="${PROGRAM} [--force]"

Arguments "${@}"

# Reading configuration files
Read_conffile config/all config/common config/bootstrap config/chroot config/binary config/source
Set_defaults

Echo_message "Begin queueing installation of local packages..."

# Requiring stage file
Require_stagefile .stage/bootstrap

# Checking stage file
Check_stagefile .stage/chroot_local-packages

# Checking lock file
Check_lockfile .lock

# Creating lock file
Create_lockfile .lock

if ls chroot/root/local-packages/*.deb > /dev/null 2>&1
then
	gunzip < chroot/root/local-packages/Packages.gz | awk '/^Package: / { print $2 }' \
		>> chroot/root/chroot_packages

	# Creating stage file
	Create_stagefile .stage/chroot_local-packages
fi
