#!/bin/sh

# lh_clone

# Cloning existing system configuration
if [ -d "${LIVE_CLONE}" ]
then
	# Swapping chroot directories
	LIVE_CHROOT_TMP="${LIVE_CHROOT}"
	LIVE_CHROOT="${LIVE_CLONE}"

	# Extract debconf settings
	lh_chroot "aptitude install --assume-yes debconf-utils"
	lh_chroot "debconf-get-selections" > "${LIVE_ROOT}"/preseed.cloned

	# Extract package selection
	lh_chroot "dpkg --get-selections" | grep -v deinstall | cut -f1 > "${LIVE_ROOT}"/package-list.cloned

	# Restoring chroot directories
	LIVE_CHROOT="${LIVE_CHROOT_TMP}"
	LIVE_CHROOT_TMP=""

	LIVE_PRESEED="${LIVE_ROOT}/preseed.cloned"
	LIVE_PACKAGE_LIST_CLONED="${LIVE_ROOT}/package-list.cloned"
fi
