#!/bin/sh

# lh_chroot_proc(1) - mount /proc
# Copyright (C) 2006-2007 Daniel Baumann <daniel@debian.org>
#
# live-helper comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
# This is free software, and you are welcome to redistribute it
# under certain conditions; see COPYING for details.

set -e

# Including common functions
LH_BASE="${LH_BASE:-/usr/share/live-helper}"

for FUNCTION in "${LH_BASE}"/functions/*.sh
do
	. "${FUNCTION}"
done

# Setting static variables
DESCRIPTION="mount /proc"
HELP=""
USAGE="${PROGRAM} {install|remove} [--force]"

Arguments "${@}"

# Ensure that a system is built as root
lh_testroot

# Reading configuration files
Read_conffile config/common
Read_conffile config/bootstrap
Read_conffile config/chroot
Read_conffile config/binary
Read_conffile config/source
Set_defaults

Echo_message "Begin mounting /proc..."

# Requiring stage file
Require_stagefile .stage/bootstrap

case "${1}" in
	install)
		# Checking stage file
		Check_stagefile .stage/chroot_proc

		# Checking lock file
		Check_lockfile .lock

		# Creating lock file
		Create_lockfile .lock

		# Creating mountpoint
		mkdir -p chroot/proc

		# Mounting /proc
		${LH_ROOT_COMMAND} mount proc-live -t proc chroot/proc

		# Creating stage file
		Create_stagefile .stage/chroot_proc
		;;

	remove)
		# Checking lock file
		Check_lockfile .lock

		# Creating lock file
		Create_lockfile .lock

		# Workaround binfmt-support /proc locking
		if [ -e chroot/proc/sys/fs/binfmt_misc/status ]
		then
			${LH_ROOT_COMMAND} umount chroot/proc/sys/fs/binfmt_misc
		fi

		# Unmounting /proc
		#fuser -km chroot/proc
		${LH_ROOT_COMMAND} umount chroot/proc > /dev/null 2>&1

		# Removing stage file
		rm -f .stage/chroot_proc
		;;

	*)
		Usage
		;;
esac
