#!/bin/sh

# lh_chroot_sysvinit(1) - configure sysvinit
# Copyright (C) 2006-2007 Daniel Baumann <daniel@debian.org>
#
# live-helper comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
# This is free software, and you are welcome to redistribute it
# under certain conditions; see COPYING for details.

set -e

# Source common functions
for FUNCTION in /usr/share/live-helper/functions/*.sh
do
	. ${FUNCTION}
done

# Set static variables
DESCRIPTION="configure sysvinit"
HELP=""
USAGE="${PROGRAM} [--force]"

Arguments "${@}"

Echo_debug "Init ${PROGRAM}"

# Reading configuration files
Read_conffile config/bootstrap
Read_conffile config/chroot
Read_conffile config/common
Read_conffile config/image
Set_defaults

Breakpoint "chroot_sysvinit: Init"

# Requiring stage file
Require_stagefile .stage/bootstrap

# Checking lock file
Check_lockfile .lock

# Creating lock file
Create_lockfile .lock

# Checking stage file
Check_stagefile .stage/chroot_sysvinit

if [ "${LIVE_SYSVINIT}" = "enabled" ]
then
	# Disable all
	for FILE in chroot/etc/init.d/*
	do
		Chroot "update-rc.d -f `basename ${FILE}` remove"
	done

	# Re-enable all required (taken from -f standard chroot)
	for PACKAGE in casper console-common cron dpkg ifupdown initscripts kbd klogd libc6 libdevmapper1.02 libselinux1 libsepol1 login makedev module-init-tools netbase openbsd-inetd procps sudo sysklogd udev util-linux
	do
		if [ -f chroot/var/lib/dpkg/info/${PACKAGE}.postinst ]
		then
			# Re-configure if existing
			Chroot "/var/lib/dpkg/info/${PACKAGE}.postinst configure"
		fi
	done

	# Creating stage file
	Create_stagefile .stage/chroot_sysvinit
fi
