#!/bin/sh

# lh_chroot_interactive(1) - make build interactive
# Copyright (C) 2006-2007 Daniel Baumann <daniel@debian.org>
#
# live-helper comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
# This is free software, and you are welcome to redistribute it
# under certain conditions; see COPYING for details.

set -e

# Source common functions
for FUNCTION in /usr/share/live-helper/functions/*.sh
do
	. ${FUNCTION}
done

# Set static variables
DESCRIPTION="make build interactive"
HELP=""
USAGE="${PROGRAM} [--force]"

Arguments "${@}"

# Reading configuration files
Read_conffile config/common
Read_conffile config/chroot
Set_defaults

if [ "${LIVE_INTERACTIVE}" != "disabled" ]
then
	# Requiring stage file
	Require_stagefile .stage/bootstrap

	# Checking lock file
	Check_lockfile .lock

	# Creating lock file
	Create_lockfile .lock

	# Checking stage file
	Check_stagefile .stage/chroot_interactive

	case "${LIVE_INTERACTIVE}" in
		enabled|shell)
			echo "Pausing build: starting interactive shell..."

			Chroot "/bin/bash --login"
			;;

		x11)
			echo "Pausing build: starting interactive X11..."

			Chroot "startx"
			;;

		xnest)
			echo "Pausing build: starting interactive Xnest..."

			#Chroot "" # FIXME
			;;
	esac

	# Creating stage file
	Create_stagefile .stage/chroot_symlinks
fi
