#!/bin/sh

# lh_chroot_tasks(1) - install tasks into chroot

set -e

# Source common functions
for FUNCTION in /usr/share/live-helper/functions/*.sh
do
	. ${FUNCTION}
done

# Reading configuration files
Read_conffile config/common
Read_conffile config/chroot
Set_defaults

# Requiring stage file
Require_stagefile .stage/bootstrap

# Checking stage file
Check_stagefile .stage/chroot_tasks

# Checking lock file
Check_lockfile .lock

# Creating lock file
Create_lockfile .lock

if [ -n "${LIVE_TASKS}" ] && [ "${LH_APT}" = "aptitude" ]
then
	# Restore old cache
	if [ -d cache/chroot_tasks ]
	then
		cp cache/chroot_tasks/*.deb chroot/var/cache/apt/archives
	fi

	Chroot "aptitude install --assume-yes ${LIVE_TASKS}"

	# Saving new cache
	Chroot "apt-get autoclean"

	if ls chroot/var/cache/apt/archives/*.deb &> /dev/null
	then
		if [ ! -d cache/chroot_tasks ]
		then
			mkdir -p cache/chroot_tasks
		fi

		mv -f chroot/var/cache/apt/archives/*.deb cache/chroot_tasks
	fi

	# Creating stage file
	Create_stagefile .stage/chroot_tasks
fi
