#!/bin/sh

# lh_chroot_local-includes(1) - copy local files into chroot
# Copyright (C) 2006-2007 Daniel Baumann <daniel@debian.org>
#
# live-helper comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
# This is free software, and you are welcome to redistribute it
# under certain conditions; see COPYING for details.

set -e

# Including common functions
LH_BASE="${LH_BASE:-/usr/share/live-helper}"

for FUNCTION in "${LH_BASE}"/functions/*.sh
do
	. "${FUNCTION}"
done

# Setting static variables
DESCRIPTION="copy local files into chroot"
HELP=""
USAGE="${PROGRAM} [--force]"

Arguments "${@}"

# Reading configuration files
Read_conffile config/common
Read_conffile config/bootstrap
Read_conffile config/chroot
Read_conffile config/binary
Read_conffile config/source
Read_conffile "${LH_CONFIG}"
Set_defaults

Echo_message "Begin copying chroot local includes..."

# Requiring stage file
Require_stagefile .stage/bootstrap

# Checking stage file
Check_stagefile .stage/chroot_local-includes

# Checking lock file
Check_lockfile .lock

# Creating lock file
Create_lockfile .lock

if ls config/chroot_local-includes/* > /dev/null 2>&1
then
	# Copying includes
	cd config/chroot_local-includes
	find . | cpio -dmpu "${OLDPWD}"/chroot
	cd "${OLDPWD}"

	# Creating stage file
	Create_stagefile .stage/chroot_local-includes
fi
