#!/bin/sh

# lh_chroot_tasks(1) - install tasks into chroot
# Copyright (C) 2006-2008 Daniel Baumann <daniel@debian.org>
#
# live-helper comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
# This is free software, and you are welcome to redistribute it
# under certain conditions; see COPYING for details.

set -e

# Including common functions
LH_BASE="${LH_BASE:-/usr/share/live-helper}"

for FUNCTION in "${LH_BASE}"/functions/*.sh
do
	. "${FUNCTION}"
done

# Setting static variables
DESCRIPTION="install tasks into chroot"
HELP=""
USAGE="${PROGRAM} [--force]"

Arguments "${@}"

# Reading configuration files
Read_conffile config/common
Read_conffile config/bootstrap
Read_conffile config/chroot
Read_conffile config/binary
Read_conffile config/source
Read_conffile "${LH_CONFIG}"
Set_defaults

Echo_message "Begin installing tasks..."

# Requiring stage file
Require_stagefile .stage/bootstrap

# Checking stage file
Check_stagefile .stage/chroot_tasks

# Checking lock file
Check_lockfile .lock

# Creating lock file
Create_lockfile .lock

if [ -n "${LH_TASKS}" ] && [ "${LH_TASKS}" != "none" ]
then
	# Restoring cache
	Restore_cache cache/packages_tasks

	# Checking depends
	case "${LH_TASKSEL}" in
		aptitude)
			Check_package chroot/usr/bin/aptitude aptitude
			;;

		tasksel)
			Check_package chroot/usr/bin/tasksel tasksel
			;;
	esac

	# Installing depends
	Install_package

	# Installing tasks
	case "${LH_TASKSEL}" in
		aptitude)
			Chroot "aptitude ${APTITUDE_OPTIONS} install ${LH_TASKS}"
			;;

		tasksel)
			for TASK in ${LH_TASKS}
			do
				Chroot "tasksel --debconf-apt-progress --logstderr install ${TASK}"
			done
			;;
	esac

	# Removing depends
	Remove_package

	# Saving cache
	Save_cache cache/packages_tasks

	# Creating stage file
	Create_stagefile .stage/chroot_tasks
fi
