#!/bin/sh

# lh_chroot_localpackageslist(1) - install local packages into chroot

set -e

# Source common functions
for FUNCTION in /usr/share/live-helper/functions/*.sh
do
	. ${FUNCTION}
done

# Reading configuration files
Read_conffile config/common
Read_conffile config/chroot
Set_defaults

# Requiring stage file
Require_stagefile .stage/bootstrap

# Checking stage file
Check_stagefile .stage/chroot_localpackageslist

# Checking lock file
Check_lockfile .lock

# Creating lock file
Create_lockfile .lock

if ls config/chroot_localpackageslist/* &> /dev/null
then
	# Restore old cache
	if [ -d cache/chroot_localpackageslist ]
	then
		cp cache/chroot_localpackageslist/*.deb chroot/var/cache/apt/archives
	fi

	for PACKAGESLIST in config/chroot_localpackageslist/*
	do
		# Copying package list
		grep -v "^#" "${PACKAGESLIST}" > chroot/root/"`basename ${PACKAGESLIST}`"

		# Installing package list
		case "${LH_APT}" in
			apt|apt-get)
				Chroot "xargs --arg-file=/root/`basename ${PACKAGESLIST}` apt-get install --yes"
				;;

			aptitude)
				Chroot "xargs --arg-file=/root/`basename ${PACKAGESLIST}` aptitude install --assume-yes"
				;;
		esac

		# Removing package list
		rm -f chroot/root/"`basename ${PACKAGESLIST}`"
	done

	# Saving new cache
	Chroot "apt-get autoclean"

	if ls chroot/var/cache/apt/archives/*.deb &> /dev/null
	then
		if [ ! -d cache/chroot_localpackageslist ]
		then
			mkdir -p cache/chroot_localpackageslist
		fi

		mv -f chroot/var/cache/apt/archives/*.deb cache/chroot_localpackageslist
	fi

	# Creating stage file
	Create_stagefile .stage/chroot_localpackageslist
fi
