#!/bin/sh

# lh_chroot_localincludes(1) - copy files into chroot

set -e

# Source common functions
for FUNCTION in /usr/share/live-helper/functions/*.sh
do
	. ${FUNCTION}
done

# Reading configuration files
Read_conffile config/common
Read_conffile config/chroot
Set_defaults

# Requiring stage file
Require_stagefile "${LIVE_ROOT}"/.stage/bootstrap

# Checking stage file
Check_stagefile "${LIVE_ROOT}"/.stage/chroot_localincludes

# Checking lock file
Check_lockfile "${LIVE_ROOT}"/.lock

# Creating lock file
Create_lockfile "${LIVE_ROOT}"/.lock

if ls "${LIVE_ROOT}"/config/chroot_localincludes/* &> /dev/null
then
	cd "${LIVE_ROOT}"/config/chroot_localincludes

	# Copying includes
	find . | cpio -dmpu "${LIVE_CHROOT}"

	# Creating stage file
	Create_stagefile "${LIVE_ROOT}"/.stage/chroot_localincludes
fi
