#!/bin/sh

# lh_chroot_localincludes(1) - copy local files into chroot
# Copyright (C) 2006-2007 Daniel Baumann <daniel@debian.org>
#
# live-helper comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
# This is free software, and you are welcome to redistribute it
# under certain conditions; see COPYING for details.

set -e

# Source common functions
for FUNCTION in /usr/share/live-helper/functions/*.sh
do
	. ${FUNCTION}
done

# Set static variables
DESCRIPTION="copy local files into chroot"
HELP=""
USAGE="${PROGRAM} [--force]"

Arguments "${@}"

Echo_debug "Init ${PROGRAM}"

# Reading configuration files
Read_conffile config/common
Read_conffile config/bootstrap
Read_conffile config/chroot
Read_conffile config/binary
Read_conffile config/source
Set_defaults

Breakpoint "chroot_localincludes: Init"

# Requiring stage file
Require_stagefile .stage/bootstrap

# Checking stage file
Check_stagefile .stage/chroot_localincludes

# Checking lock file
Check_lockfile .lock

# Creating lock file
Create_lockfile .lock

if ls config/chroot_localincludes/* &> /dev/null
then
	# Copying includes
	cd config/chroot_localincludes
	find . | cpio -dmpu "${OLDPWD}"/chroot
	cd "${OLDPWD}"

	# Creating stage file
	Create_stagefile .stage/chroot_localincludes
fi
