#!/bin/sh

# lh_chroot_apt(1) - manage /etc/apt/apt.conf
# Copyright (C) 2006-2009 Daniel Baumann <daniel@debian.org>
#
# live-helper comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
# This is free software, and you are welcome to redistribute it
# under certain conditions; see COPYING for details.

set -e

# Including common functions
. "${LH_BASE:-/usr/share/live-helper}"/functions.sh

# Setting static variables
DESCRIPTION="$(Echo 'manage /etc/apt/apt.conf')"
HELP=""
USAGE="${PROGRAM} {install|install-binary|remove} [--force]"

Arguments "${@}"

# Reading configuration files
Read_conffiles config/all config/common config/bootstrap config/chroot config/binary config/source
Set_defaults

# Requiring stage file
Require_stagefile .stage/config .stage/bootstrap

case "${1}" in
	install|install-binary)
		Echo_message "Configuring file /etc/apt/apt.conf"

		# Checking stage file
		Check_stagefile .stage/chroot_apt

		# Checking lock file
		Check_lockfile .lock

		# Creating lock file
		Create_lockfile .lock

		mkdir -p chroot/etc/apt/apt.conf.d

		# Configuring apt ftp proxy
		if [ -n "${LH_APT_FTP_PROXY}" ]
		then
			echo "Acquire::ftp::Proxy \"${LH_APT_FTP_PROXY}\";" > chroot/etc/apt/apt.conf.d/00ftp-proxy
		fi

		# Configuring apt http proxy
		if [ -n "${LH_APT_HTTP_PROXY}" ]
		then
			echo "Acquire::http::Proxy \"${LH_APT_HTTP_PROXY}\";" > chroot/etc/apt/apt.conf.d/00http-proxy
		fi

		# Configuring apt pdiffs
		case "${LH_APT_PDIFFS}" in
			enabled)
				echo "Acquire::PDiffs \"true\";" > chroot/etc/apt/apt.conf.d/00pdiffs
				;;

			disabled)
				echo "Acquire::PDiffs \"false\";" > chroot/etc/apt/apt.conf.d/00pdiffs
				;;
		esac

		# Configuring apt pipeline
		if [ -n "${LH_APT_PIPELINE}" ]
		then
			echo "Acquire::http::Pipeline-Depth \"${LH_APT_PIPELINE}\";" > chroot/etc/apt/apt.conf.d/00pipeline
		fi

		# Configuring apt recommends
		case "${LH_APT_RECOMMENDS}" in
			enabled)
				echo "APT::Install-Recommends \"true\";" > chroot/etc/apt/apt.conf.d/00recommends
				echo "Aptitude::Recommends-Important \"true\";" >> chroot/etc/apt/apt.conf.d/00recommends
				;;

			disabled)
				echo "APT::Install-Recommends \"false\";" > chroot/etc/apt/apt.conf.d/00recommends
				echo "Aptitude::Recommends-Important \"false\";" >> chroot/etc/apt/apt.conf.d/00recommends
				;;
		esac

		# Configuring apt secure
		case "${LH_APT_SECURE}" in
			enabled)
				echo "APT::Get::AllowUnauthenticated \"false\";" > chroot/etc/apt/apt.conf.d/00secure
				echo "Aptitude::CmdLine::Ignore-Trust-Violations \"false\";" >> chroot/etc/apt/apt.conf.d/00secure
				;;

			disabled)
				echo "APT::Get::AllowUnauthenticated \"true\";" > chroot/etc/apt/apt.conf.d/00secure
				echo "Aptitude::CmdLine::Ignore-Trust-Violations \"true\";" >> chroot/etc/apt/apt.conf.d/00secure
				;;
		esac

		# Configuring apt config
		if [ -f config/chroot_apt/apt.conf ]
		then
			if [ -f chroot/etc/apt/apt.conf ]
			then
				mv chroot/etc/apt/apt.conf chroot/etc/apt/apt.conf.orig
			fi

			cp config/chroot_apt/apt.conf chroot/etc/apt/apt.conf
		fi

		# Configuring apt preferences
		if [ -f config/chroot_apt/preferences ]
		then
			if [ -f chroot/etc/apt/preferences ]
			then
				mv chroot/etc/apt/preferences chroot/etc/apt/preferences.orig
			fi

			cp config/chroot_apt/preferences chroot/etc/apt/preferences
		fi

		if Find_files config/chroot_local-packages/*.deb
		then
			if [ ! -f config/chroot_apt/preferences ] && [ "${1}" = "install-binary" ]
			then
				rm -f chroot/etc/apt/preferences
			fi

			echo >> chroot/etc/apt/preferences
			echo "# Added by lh_chroot_apt ${@}" >> chroot/etc/apt/preferences
			echo "Package: *" >> chroot/etc/apt/preferences
			echo "Pin: release o=chroot_local-packages" >> chroot/etc/apt/preferences

			case "${1}" in
				install)
					# Ensure local packages have priority
					echo "Pin-Priority: 1001" >> chroot/etc/apt/preferences
					;;

				install-binary)
					# Ensure local packages are not re-installed during lh_binary
					echo "Pin-Priority: 99" >> chroot/etc/apt/preferences

					echo >> chroot/etc/apt/preferences
					echo "Package: *" >> chroot/etc/apt/preferences
					echo "Pin: release o=debian" >> chroot/etc/apt/preferences
					echo "Pin-Priority: 99" >> chroot/etc/apt/preferences
					;;
			esac
		fi

		# Creating stage file
		Create_stagefile .stage/chroot_apt
		;;

	remove)
		Echo_message "Deconfiguring file /etc/apt/apt.conf"

		# Checking lock file
		Check_lockfile .lock

		# Creating lock file
		Create_lockfile .lock

		# Deconfiguring aptitude ftp proxy
		rm -f chroot/etc/apt/apt.conf.d/00ftp-proxy

		# Deconfiguring aptitude http proxy
		rm -f chroot/etc/apt/apt.conf.d/00http-proxy

		# Deconfiguring aptitude pdiffs
		if [ "${LH_APT_PDIFFS}" = "enabled" ]
		then
			rm -f chroot/etc/apt/apt.conf.d/00pdiffs
		fi

		# Deconfiguring aptitude pipeline
		rm -f chroot/etc/apt/apt.conf.d/00pipeline

		# Deconfiguring aptitude recommends
		if [ "${LH_APT_RECOMMENDS}" = "enabled" ]
		then
			rm -f chroot/etc/apt/apt.conf.d/00recommends
		fi

		# Deconfiguring aptitude secure
		if [ "${LH_APT_SECURE}" = "enabled" ]
		then
			rm -f chroot/etc/apt/apt.conf.d/00secure
		fi

		# Configuring apt config
		if [ -f config/chroot_apt/apt.conf ]
		then
			if [ -f chroot/etc/apt/apt.conf ]
			then
				mv chroot/etc/apt/apt.conf chroot/etc/apt/apt.conf.orig
			fi

			cp config/chroot_apt/apt.conf chroot/etc/apt/apt.conf
		fi

		# Deconfiguring apt preferences
		if [ -f chroot/etc/apt/preferences.orig ]
		then
			mv chroot/etc/apt/preferences.orig chroot/etc/apt/preferences
		else
			rm -f chroot/etc/apt/preferences
		fi

		# Removing stage file
		rm -f .stage/chroot_apt
		;;

	*)
		Usage
		;;
esac
