#!/bin/sh

# lh_chroot_sysvrc(1) - manage /usr/sbin/policy-rc.d
# Copyright (C) 2006-2007 Daniel Baumann <daniel@debian.org>
#
# live-helper comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
# This is free software, and you are welcome to redistribute it
# under certain conditions; see COPYING for details.

set -e

# Source common functions
for FUNCTION in /usr/share/live-helper/functions/*.sh
do
	. ${FUNCTION}
done

# Set static variables
DESCRIPTION="manage /usr/sbin/policy-rc.d"
HELP=""
USAGE="${PROGRAM} {install|remove} [--force]"

Arguments "${@}"

# Reading configuration files
Read_conffile config/common
Read_conffile config/chroot
Set_defaults

# Requiring stage file
Require_stagefile .stage/bootstrap

# Checking lock file
Check_lockfile .lock

# Creating lock file
Create_lockfile .lock

case "${1}" in
	install)
		# Checking stage file
		Check_stagefile .stage/chroot_sysvrc

		if [ -f chroot/usr/sbin/policy-rc.d ]
		then
			# Save policy-rc.d file
			mv chroot/usr/sbin/policy-rc.d chroot/usr/sbin/policy-rc.d.orig
		fi

		# Create policy-rc.d file
cat  > chroot/usr/sbin/policy-rc.d << EOF
#!/bin/sh

echo
echo "Warning: invoke-rc.d policy in action. Skiping daemon starting"

exit 101
EOF

		chmod 0755 chroot/usr/sbin/policy-rc.d

		# Creating stage file
		Create_stagefile .stage/chroot_sysvrc
		;;

	remove)
		if [ -f chroot/usr/sbin/policy-rc.d.orig ]
		then
			# Restore policy-rc.d file
			mv chroot/usr/sbin/policy-rc.d.orig chroot/usr/sbin/policy-rc.d
		else
			# Remove policy-rc.d file
			rm -f chroot/usr/sbin/policy-rc.d
		fi

		# Removing stage file
		rm -f .stage/chroot_sysvrc
		;;

	*)
		Usage
		;;
esac
