#!/bin/sh

# lh_chroot_devpts(1) - mount /dev/pts
# Copyright (C) 2006-2009 Daniel Baumann <daniel@debian.org>
#
# live-helper comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
# This is free software, and you are welcome to redistribute it
# under certain conditions; see COPYING for details.

set -e

# Including common functions
. "${LH_BASE:-/usr/share/live-helper}"/live-helper.sh

# Setting static variables
DESCRIPTION="$(Echo 'mount /dev/pts')"
HELP=""
USAGE="${PROGRAM} {install|remove} [--force]"

Arguments "${@}"

# Ensure that a system is built as root
lh testroot

# Reading configuration files
Read_conffiles config/all config/common config/bootstrap config/chroot config/binary config/source
Set_defaults

# Requiring stage file
Require_stagefile .stage/config .stage/bootstrap

case "${1}" in
	install)
		Echo_message "Begin mounting /dev/pts..."

		# Checking stage file
		Check_stagefile .stage/chroot_devpts

		# Checking lock file
		Check_lockfile .lock

		# Creating lock file
		Create_lockfile .lock

		if [ "${LH_USE_FAKEROOT}" != "enabled" ]
		then
			# Creating mountpoint
			mkdir -p chroot/dev/pts

			# Mounting /dev/pts
			${LH_ROOT_COMMAND} mount devpts-live -t devpts chroot/dev/pts || true
		fi

		# Creating stage file
		Create_stagefile .stage/chroot_devpts
		;;

	remove)
		Echo_message "Begin unmounting /dev/pts..."

		# Checking lock file
		Check_lockfile .lock

		# Creating lock file
		Create_lockfile .lock

		# Unmounting /dev/pts
		if [ "${LH_USE_FAKEROOT}" != "enabled" ]
		then
			if Find_files chroot/dev/pts/*
			then
				${LH_ROOT_COMMAND} umount chroot/dev/pts
			fi
		fi

		# Removing stage file
		rm -f .stage/chroot_devpts
		;;

	*)
		Usage
		;;
esac
