#!/bin/sh

# lh_chroot_sysvinit(1) - configure sysvinit
# Copyright (C) 2006-2009 Daniel Baumann <daniel@debian.org>
#
# live-helper comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
# This is free software, and you are welcome to redistribute it
# under certain conditions; see COPYING for details.

set -e

# Including common functions
. "${LH_BASE:-/usr/share/live-helper}"/live-helper.sh

# Setting static variables
DESCRIPTION="$(Echo 'configure sysvinit')"
HELP=""
USAGE="${PROGRAM} [--force]"

Arguments "${@}"

# Reading configuration files
Read_conffiles config/all config/common config/bootstrap config/chroot config/binary config/source
Set_defaults

Echo_message "Configuring package sysvinit"

# Requiring stage file
Require_stagefile .stage/config .stage/bootstrap

# Checking stage file
Check_stagefile .stage/chroot_sysvinit

# Checking lock file
Check_lockfile .lock

# Creating lock file
Create_lockfile .lock

if [ "${LH_SYSVINIT}" = "enabled" ]
then
	# Disable all
	for FILE in chroot/etc/init.d/*
	do
		Chroot chroot "update-rc.d -f $(basename ${FILE}) remove"
	done

	# Re-enable all required (taken from -f standard chroot)
	for PACKAGE in ${LH_INITRAMFS} console-common cron dpkg ifupdown initscripts kbd klogd libc6 libdevmapper1.02 libselinux1 libsepol1 login makedev module-init-tools netbase openbsd-inetd procps sudo sysklogd udev util-linux
	do
		if [ -f chroot/var/lib/dpkg/info/${PACKAGE}.postinst ]
		then
			# Re-configure if existing
			Chroot chroot "/var/lib/dpkg/info/${PACKAGE}.postinst configure"
		fi
	done

	# Creating stage file
	Create_stagefile .stage/chroot_sysvinit
fi
