#!/bin/sh

# lh_chroot_hooks(1) - execute hooks in chroot
# Copyright (C) 2006-2007 Daniel Baumann <daniel@debian.org>
#
# live-helper comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
# This is free software, and you are welcome to redistribute it
# under certain conditions; see COPYING for details.

set -e

# Source common functions
for FUNCTION in /usr/share/live-helper/functions/*.sh
do
	. ${FUNCTION}
done

# Set static variables
DESCRIPTION="execute hooks in chroot"
HELP=""
USAGE="${PROGRAM} [--force]"

Arguments "${@}"

Echo_debug "Init ${PROGRAM}"

# Reading configuration files
Read_conffile config/bootstrap
Read_conffile config/chroot
Read_conffile config/common
Read_conffile config/image
Set_defaults

Breakpoint "chroot_hooks: Init"

# Requiring stage file
Require_stagefile .stage/bootstrap

# Checking stage file
Check_stagefile .stage/chroot_hooks

# Checking lock file
Check_lockfile .lock

# Creating lock file
Create_lockfile .lock

# Processing hooks
if [ -n "${LIVE_PACKAGES_LISTS}" ] && [ -f /usr/share/live-helper/hooks/"${LIVE_PACKAGES_LISTS}" ]
then
	# Copying hook
	cp /usr/share/live-helper/hooks/"${LIVE_PACKAGES_LISTS}" chroot/root

	# Making hook executable
	if [ ! -x chroot/root/${LIVE_PACKAGES_LISTS} ]
	then
		chmod +x chroot/root/${LIVE_PACKAGES_LISTS}
	fi

	# Executing hook
	Chroot "/root/${LIVE_PACKAGES_LISTS}"

	# Removing hook
	rm -f chroot/root/"${LIVE_PACKAGE_LIST}"

	# Creating stage file
	Create_stagefile .stage/chroot_hooks
fi
