#!/bin/sh

# lh_chroot_localhooks(1) - execute hooks in chroot

set -e

# Source common functions
for FUNCTION in /usr/share/live-helper/functions/*.sh
do
	. ${FUNCTION}
done

# Reading configuration files
Read_conffile config/common
Read_conffile config/chroot
Set_defaults

# Requiring stage file
Require_stagefile .stage/bootstrap

# Checking stage file
Check_stagefile .stage/chroot_localhooks

# Checking lock file
Check_lockfile .lock

# Creating lock file
Create_lockfile .lock

# Processing localhooks
if ls config/chroot_localhooks/* &> /dev/null
then
	for HOOK in config/chroot_localhooks/*
	do
		# Copying hook
		cp "${HOOK}" chroot/root

		# Making hook executable
		if [ ! -x chroot/root/"`basename ${HOOK}`" ]
		then
			chmod +x chroot/root/"`basename ${HOOK}`"
		fi

		# Executing hook
		Chroot "/root/`basename ${HOOK}`"

		# Removing hook
		rm -f chroot/"`basename ${HOOK}`"
	done

	# Creating stage file
	Create_stagefile .stage/chroot_localhooks
fi
