#!/bin/sh

# lh_chroot_resolv(1) - manage /etc/resolv.conf

set -e

# Source common functions
for FUNCTION in /usr/share/live-helper/functions/*.sh
do
	. ${FUNCTION}
done

# Reading configuration files
Read_conffile config/common
Read_conffile config/chroot
Set_defaults

# Requiring stage file
Require_stagefile "${LIVE_ROOT}"/.stage/bootstrap

# Checking lock file
Check_lockfile "${LIVE_ROOT}"/.lock

# Creating lock file
Create_lockfile "${LIVE_ROOT}"/.lock

case "${1}" in
	install)
		# Checking stage file
		Check_stagefile "${LIVE_ROOT}"/.stage/chroot_resolv

		if [ -f "${LIVE_CHROOT}"/etc/resolv.conf ]
		then
			# Save resolv file
			cp "${LIVE_CHROOT}"/etc/resolv.conf "${LIVE_CHROOT}"/etc/resolv.conf.orig
		fi

		if [ -f /etc/resolv.conf ]
		then
			# Copy resolv file
			cp /etc/resolv.conf "${LIVE_CHROOT}"/etc/resolv.conf
		fi

		# Creating stage file
		Create_stagefile "${LIVE_ROOT}"/.stage/chroot_resolv
		;;

	remove)
		if [ -f "${LIVE_CHROOT}"/etc/resolv.conf.orig ]
		then
			# Restore resolv file
			mv "${LIVE_CHROOT}"/etc/resolv.conf.orig "${LIVE_CHROOT}"/etc/resolv.conf
		else
			# Remove resolv file
			rm -f "${LIVE_CHROOT}"/etc/resolv.conf
		fi

		# Removing stage file
		rm -f "${LIVE_ROOT}"/.stage/chroot_resolv
		;;

	*)
		echo "Usage: ${0} {install|remove}"
		exit 1
		;;
esac
