#!/bin/sh

# lh_chroot_debianchroot(1) - manage /etc/debian_chroot
# Copyright (C) 2006-2007 Daniel Baumann <daniel@debian.org>
#
# live-helper comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
# This is free software, and you are welcome to redistribute it
# under certain conditions; see COPYING for details.

set -e

# Source common functions
for FUNCTION in /usr/share/live-helper/functions/*.sh
do
	. ${FUNCTION}
done

# Set static variables
DESCRIPTION="manage /etc/debian_chroot"
HELP=""
USAGE="${PROGRAM} {install|remove} [--force]"

Arguments "${@}"

Echo_debug "Init ${PROGRAM}"

# Reading configuration files
Read_conffile config/bootstrap
Read_conffile config/chroot
Read_conffile config/common
Read_conffile config/image
Set_defaults

Breakpoint "chroot_debianchroot: Init"

# Requiring stage file
Require_stagefile .stage/bootstrap

# Checking lock file
Check_lockfile .lock

# Creating lock file
Create_lockfile .lock

case "${1}" in
	install)
		# Checking stage file
		Check_stagefile .stage/chroot_debianchroot

		if [ -f chroot/etc/debian_chroot ]
		then
			# Save chroot file
			mv chroot/etc/debian_chroot chroot/etc/debian_chroot.orig
		fi

		# Create chroot file
		echo "live" > chroot/etc/debian_chroot

		# Creating stage file
		Create_stagefile .stage/chroot_debianchroot
		;;

	remove)
		if [ -f chroot/etc/debian_chroot.orig ]
		then
			# Restore chroot file
			mv chroot/etc/debian_chroot.orig chroot/etc/debian_chroot
		else
			# Remove chroot file
			rm -f chroot/etc/debian_chroot
		fi

		# Removing stage file
		rm -f .stage/chroot_debianchroot
		;;

	*)
		Usage
		;;
esac
