#!/bin/sh

# lh_chroot_local-packageslists(1) - queue install of local packages lists into chroot
# Copyright (C) 2006-2008 Daniel Baumann <daniel@debian.org>
#
# live-helper comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
# This is free software, and you are welcome to redistribute it
# under certain conditions; see COPYING for details.

set -e

# Including common functions
LH_BASE="${LH_BASE:-/usr/share/live-helper}"

for FUNCTION in "${LH_BASE}"/functions/*.sh
do
	. "${FUNCTION}"
done

# Setting static variables
DESCRIPTION="queue install of local packages lists into chroot"
HELP=""
USAGE="${PROGRAM} [--force]"

Arguments "${@}"

# Reading configuration files
Read_conffile config/all config/common config/bootstrap config/chroot config/binary config/source
Set_defaults

Echo_message "Begin queueing installation of local packages lists..."

# Requiring stage file
Require_stagefile .stage/bootstrap

# Checking stage file
Check_stagefile .stage/chroot_local-packageslists

# Checking lock file
Check_lockfile .lock

# Creating lock file
Create_lockfile .lock

if ls config/chroot_local-packageslists/* > /dev/null 2>&1
then
	for PACKAGES_LIST in config/chroot_local-packageslists/*
	do
		# Generate package list
		Expand_packagelist "${PACKAGES_LIST}" "config/chroot_local-packageslists" \
			>> chroot/root/chroot_packages
	done

	# Creating stage file
	Create_stagefile .stage/chroot_local-packageslists
fi
