#!/bin/sh

# lh_chroot(1) - customize the Debian system
# Copyright (C) 2006-2007 Daniel Baumann <daniel@debian.org>
#
# live-helper comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
# This is free software, and you are welcome to redistribute it
# under certain conditions; see COPYING for details.

set -e

# Source common functions
for FUNCTION in /usr/share/live-helper/functions/*.sh
do
	. ${FUNCTION}
done

# Set static variables
DESCRIPTION="customize the Debian system"
HELP=""
USAGE="${PROGRAM} [--force]"

Arguments "${@}"

if [ "${FORCE}" = "true" ]
then
	OPTIONS="${OPTIONS} --force"
fi

# Reading configuration files
Read_conffile config/common
Read_conffile config/chroot
Set_defaults

# Configuring chroot
lh_chroot_proc install "${OPTIONS}"
lh_chroot_sysfs install "${OPTIONS}"
lh_chroot_debianchroot install "${OPTIONS}"
lh_chroot_sysvrc install "${OPTIONS}"
lh_chroot_hosts install "${OPTIONS}"
lh_chroot_resolv install "${OPTIONS}"
lh_chroot_apt install "${OPTIONS}"
lh_chroot_sources install "${OPTIONS}"
lh_chroot_linuximage install "${OPTIONS}"

# Customizing chroot
lh_chroot_tasks "${OPTIONS}"
lh_chroot_packageslists "${OPTIONS}"
lh_chroot_packages "${OPTIONS}"
lh_chroot_localpackages "${OPTIONS}"
lh_chroot_localpackageslists "${OPTIONS}"
lh_chroot_localization "${OPTIONS}"
lh_chroot_hacks "${OPTIONS}"
lh_chroot_localincludes "${OPTIONS}"
lh_chroot_sysvinit "${OPTIONS}"
lh_chroot_hooks "${OPTIONS}"
lh_chroot_localhooks "${OPTIONS}"
lh_chroot_symlinks "${OPTIONS}"
lh_chroot_interactive "${OPTIONS}"

# Deconfiguring chroot
lh_chroot_linuximage remove "${OPTIONS}"
lh_chroot_sources remove "${OPTIONS}"
lh_chroot_apt remove "${OPTIONS}"
lh_chroot_resolv remove "${OPTIONS}"
lh_chroot_hosts remove "${OPTIONS}"
lh_chroot_sysvrc remove "${OPTIONS}"
lh_chroot_debianchroot remove "${OPTIONS}"
lh_chroot_sysfs remove "${OPTIONS}"
lh_chroot_proc remove "${OPTIONS}"
