#!/bin/sh

# lh_chroot_hosts(1) - manage /etc/hosts
# Copyright (C) 2006-2007 Daniel Baumann <daniel@debian.org>
#
# live-helper comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
# This is free software, and you are welcome to redistribute it
# under certain conditions; see COPYING for details.

set -e

# Including common functions
LH_BASE="${LH_BASE:-/usr/share/live-helper}"

for FUNCTION in "${LH_BASE}"/functions/*.sh
do
	. "${FUNCTION}"
done

# Setting static variables
DESCRIPTION="manage /etc/hosts"
HELP=""
USAGE="${PROGRAM} {install|remove} [--force]"

Arguments "${@}"

# Reading configuration files
Read_conffile config/common
Read_conffile config/bootstrap
Read_conffile config/chroot
Read_conffile config/binary
Read_conffile config/source
Set_defaults

# Requiring stage file
Require_stagefile .stage/bootstrap

case "${1}" in
	install)
		Echo_message "Configuring file /etc/hosts"

		# Checking stage file
		Check_stagefile .stage/chroot_hosts

		# Checking lock file
		Check_lockfile .lock

		# Creating lock file
		Create_lockfile .lock

		if [ -f chroot/etc/hosts ]
		then
			# Save hosts file
			cp chroot/etc/hosts chroot/etc/hosts.orig
		fi

		if [ -f /etc/hosts ]
		then
			# Copy hosts file
			cp /etc/hosts chroot/etc/hosts
		fi

		# Creating stage file
		Create_stagefile .stage/chroot_hosts
		;;

	remove)
		Echo_message "Deconfiguring file /etc/hosts"

		# Checking lock file
		Check_lockfile .lock

		# Creating lock file
		Create_lockfile .lock

		if [ -f chroot/etc/hosts.orig ]
		then
			# Restore hosts file
			mv chroot/etc/hosts.orig chroot/etc/hosts
		else
			# Remove hosts file
			rm -f chroot/etc/hosts
		fi

		# Removing stage file
		rm -f .stage/chroot_hosts
		;;

	*)
		Usage
		;;
esac
