#!/bin/sh

# lh_chroot_hostname(1) - manage /bin/hostname
# Copyright (C) 2006-2008 Daniel Baumann <daniel@debian.org>
#
# live-helper comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
# This is free software, and you are welcome to redistribute it
# under certain conditions; see COPYING for details.

set -e

# Including common functions
LH_BASE="${LH_BASE:-/usr/share/live-helper}"

for FUNCTION in "${LH_BASE}"/functions/*.sh
do
	. "${FUNCTION}"
done

# Setting static variables
DESCRIPTION="manage /bin/hostname"
HELP=""
USAGE="${PROGRAM} {install|remove} [--force]"

Arguments "${@}"

# Reading configuration files
Read_conffile config/common
Read_conffile config/bootstrap
Read_conffile config/chroot
Read_conffile config/binary
Read_conffile config/source
Read_conffile "${LH_CONFIG}"
Set_defaults

# Requiring stage file
Require_stagefile .stage/bootstrap

case "${1}" in
	install)
		Echo_message "Configuring file /etc/hostname"

		# Checking stage file
		Check_stagefile .stage/chroot_hostname

		# Checking lock file
		Check_lockfile .lock

		# Creating lock file
		Create_lockfile .lock

		# Save hostname
		mv chroot/bin/hostname chroot/bin/hostname.orig

		# Create hostname file
		echo "localhost.localdomain" > chroot/etc/hostname

		Echo_message "Configuring file /bin/hostname"

		# Create hostname program

cat > chroot/bin/hostname << EOF
#!/bin/sh

echo "localhost.localdomain"
EOF

		chmod 755 chroot/bin/hostname

		# Creating stage file
		Create_stagefile .stage/chroot_hostname
		;;

	remove)
		Echo_message "Deconfiguring file /etc/hostname"

		# Checking lock file
		Check_lockfile .lock

		# Creating lock file
		Create_lockfile .lock

		Echo_message "Deconfiguring file /bin/hostname"

		# Restore hostname file
		mv chroot/bin/hostname.orig chroot/bin/hostname

		# Removing stage file
		rm -f .stage/chroot_hostname
		;;

	*)
		Usage
		;;
esac
