#!/bin/sh

# lh_chroot_hacks(1) - execute hacks in chroot
# Copyright (C) 2006-2007 Daniel Baumann <daniel@debian.org>
#
# live-helper comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
# This is free software, and you are welcome to redistribute it
# under certain conditions; see COPYING for details.

set -e

# Including common functions
LH_BASE="${LH_BASE:-/usr/share/live-helper}"

for FUNCTION in "${LH_BASE}"/functions/*.sh
do
	. "${FUNCTION}"
done

# Setting static variables
DESCRIPTION="execute hacks in chroot"
HELP=""
USAGE="${PROGRAM} [--force]"

Arguments "${@}"

# Reading configuration files
Read_conffile config/common
Read_conffile config/bootstrap
Read_conffile config/chroot
Read_conffile config/binary
Read_conffile config/source
Read_conffile "${LH_CONFIG}"
Set_defaults

Echo_message "Begin executing hacks..."

# Requiring stage file
Require_stagefile .stage/bootstrap

# Checking stage file
Check_stagefile .stage/chroot_hacks

# Checking lock file
Check_lockfile .lock

# Creating lock file
Create_lockfile .lock

# Removing udev mac caching rule
Chroot "rm -f /etc/udev/rules.d/z25_persistent-net.rules"

# Blanking out fstab, so the live-initramfs will know to populate it
Chroot "rm -f /etc/fstab"
Chroot "touch /etc/fstab"

case "${LH_BINARY_IMAGES}" in
	net)
		if [ ! -f chroot/usr/bin/smbmount ]
		then
			case "${LH_APT}" in
				apt|apt-get)
					Chroot "apt-get install --yes smbfs"
					;;

				aptitude)
					Chroot "aptitude install --assume-yes smbfs"
					;;
			esac
		fi

		if [ ! -d chroot/etc/initramfs-tools ]
		then
			mkdir chroot/etc/initramfs-tools
		fi
		if [ ! "$(grep 'MODULES=netboot' chroot/etc/initramfs-tools/initramfs.conf)" ]
		then
			# Configuring initramfs for NFS
cat >> chroot/etc/initramfs-tools/initramfs.conf << EOF
MODULES=netboot
BOOT=nfs
NFSROOT=auto
EOF
		fi
		;;
esac

# Remove resume
if [ "${LH_DISTRIBUTION}" = "etch" ] && [ -e /etc/initramfs-tools/conf.d/resume ]
then
	rm -f /etc/initramfs-tools/conf.d/resume
fi

# Update initramfs
Chroot "update-initramfs -k all -t -u"

# Remove build systems clock drift
echo "0.0 0 0.0" > chroot/etc/adjtime

# Remove cruft
rm -f chroot/boot/initrd*bak*
rm -f /etc/apt/trusted.gpg~
rm -f chroot/etc/group- chroot/etc/passwd-
rm -f chroot/etc/gshadow- chroot/etc/shadow-
rm -f chroot/var/cache/debconf/*-old
rm -f chroot/var/lib/dpkg/*-old

if [ -n "${LH_ROOT_COMMAND}" ]
then
	${LH_ROOT_COMMAND} chown -R --quiet $(whoami):$(whoami) chroot
fi

if [ -d chroot/home/${LH_USERNAME} ]
then
	chown -R --quiet 999:999 chroot/home/${LH_USERNAME}
fi

if [ "${LH_EXPOSED_ROOT}" = "enabled" ]
then
	# Make sure RW dirs exist so that the initramfs script has
	# a directory in which to bind the tmpfs filesystems
	COW_DIRS='/tmp /var/tmp /var/lock /var/run /var/lib/live /var/log
		/var/spool /home /live'
	for DIR in ${COW_DIRS}; do
		mkdir -p chroot${DIR}
	done

	# Config files which need to be RW
	CONFIG_FILES='/etc/hostname /etc/hosts /etc/resolv.conf /etc/fstab
		/etc/live.conf /etc/network/interfaces /etc/X11/xorg.conf
		/etc/udev/rules.d/z25_persistent-net.rules
		/etc/udev/rules.d/z25_persistent-cd.rules'

	# Where we will store RW config files
	RW_DIR='/var/lib/live'

	for FILE_PATH in ${CONFIG_FILES}
	do
		# Touch files in case they don't yet exist
		FILE_DIR=$(dirname ${FILE_PATH})
		mkdir -p chroot${FILE_DIR}
		touch chroot${FILE_PATH}
		FILE_NAME=$(basename ${FILE_PATH})
		mkdir -p chroot${RW_DIR}${FILE_DIR}
		mv chroot${FILE_PATH} chroot${RW_DIR}${FILE_DIR}
		# Create a symbolic link to RW config file
		RELATIVE_PATH=$(echo ${FILE_DIR}|sed 's/[^\/]\+/../g; s/^\///g')
		ln -s ${RELATIVE_PATH}${RW_DIR}${FILE_PATH} chroot${FILE_PATH}
	done

	# Mount doesn't write to a symlink so use /proc/mounts instead,
	# see debian bug #154438 for more info
	rm chroot/etc/mtab
	ln -s /proc/mounts chroot/etc/mtab
fi

# Creating stage file
Create_stagefile .stage/chroot_hacks
