#!/bin/sh

# lh_chroot_local-packageslists(1) - install local packages lists into chroot
# Copyright (C) 2006-2007 Daniel Baumann <daniel@debian.org>
#
# live-helper comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
# This is free software, and you are welcome to redistribute it
# under certain conditions; see COPYING for details.

set -e

# Including common functions
LH_BASE="${LH_BASE:-/usr/share/live-helper}"

for FUNCTION in "${LH_BASE}"/functions/*.sh
do
	. "${FUNCTION}"
done

# Setting static variables
DESCRIPTION="install local packages into chroot"
HELP=""
USAGE="${PROGRAM} [--force]"

Arguments "${@}"

# Reading configuration files
Read_conffile config/common
Read_conffile config/bootstrap
Read_conffile config/chroot
Read_conffile config/binary
Read_conffile config/source
Set_defaults

Echo_message "Begin installing local packages lists..."

# Requiring stage file
Require_stagefile .stage/bootstrap

# Checking stage file
Check_stagefile .stage/chroot_local-packageslists

# Checking lock file
Check_lockfile .lock

# Creating lock file
Create_lockfile .lock

if ls config/chroot_local-packageslists/* > /dev/null 2>&1
then
	# Restoring cache
	Restore_cache cache/packages_local-packageslists

	for PACKAGESLIST in config/chroot_local-packageslists/*
	do
		# Generate package list
		Expand_packagelist "`basename ${PACKAGESLIST}`" "config/chroot_local-packageslists" "${LH_BASE:-/usr/share/live-helper/lists}/lists" > chroot/root/"`basename ${PACKAGESLIST}`"

		# Installing package list
		case "${LH_APT}" in
			apt|apt-get)
				Chroot "xargs --arg-file=/root/`basename ${PACKAGESLIST}` apt-get install --yes"
				;;

			aptitude)
				Chroot "xargs --arg-file=/root/`basename ${PACKAGESLIST}` aptitude install --assume-yes"
				;;
		esac

		# Removing package list
		rm -f chroot/root/"`basename ${PACKAGESLIST}`"
	done

	# Saving cache
	Save_cache cache/packages_local-packageslists

	# Creating stage file
	Create_stagefile .stage/chroot_local-packageslists
fi
