#!/bin/sh

# lh_chroot_sysfs(1) - mount /sys
# Copyright (C) 2006-2007 Daniel Baumann <daniel@debian.org>
#
# live-helper comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
# This is free software, and you are welcome to redistribute it
# under certain conditions; see COPYING for details.

set -e

# Including common functions
LH_BASE="${LH_BASE:-/usr/share/live-helper}"

for FUNCTION in "${LH_BASE}"/functions/*.sh
do
	. "${FUNCTION}"
done

# Setting static variables
DESCRIPTION="mount /sys"
HELP=""
USAGE="${PROGRAM} {install|remove} [--force]"

Arguments "${@}"

# Ensure that a system is built as root
lh_testroot

# Reading configuration files
Read_conffile config/common
Read_conffile config/bootstrap
Read_conffile config/chroot
Read_conffile config/binary
Read_conffile config/source
Read_conffile "${LH_CONFIG}"
Set_defaults

Echo_message "Begin mounting /sys..."

# Requiring stage file
Require_stagefile .stage/bootstrap

case "${1}" in
	install)
		# Checking stage file
		Check_stagefile .stage/chroot_sysfs

		# Checking lock file
		Check_lockfile .lock

		# Creating lock file
		Create_lockfile .lock

		if [ "${LH_USE_FAKEROOT}" != "enabled" ]
		then
			# Create mountpoint
			mkdir -p chroot/sys

			# Mounting /sys
			${LH_ROOT_COMMAND} mount sysfs-live -t sysfs chroot/sys
		else
			rm -rf chroot/sys
			ln -s /sys chroot/
		fi

		# Creating stage file
		Create_stagefile .stage/chroot_sysfs
		;;

	remove)
		# Checking lock file
		Check_lockfile .lock

		# Creating lock file
		Create_lockfile .lock

		if [ "${LH_USE_FAKEROOT}" != "enabled" ]
		then
			# Unmounting /sys
			#fuser -km chroot/sys
			${LH_ROOT_COMMAND} umount chroot/sys > /dev/null 2>&1
		else
			rm -rf chroot/sys
			mkdir -p chroot/sys
		fi

		# Removing stage file
		rm -f .stage/chroot_sysfs
		;;

	*)
		Usage
		;;
esac
