#!/bin/sh

# lh_chroot_linux-image(1) - manage /etc/kernel-img.conf
# Copyright (C) 2006-2007 Daniel Baumann <daniel@debian.org>
#
# live-helper comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
# This is free software, and you are welcome to redistribute it
# under certain conditions; see COPYING for details.

set -e

# Including common functions
LH_BASE="${LH_BASE:-/usr/share/live-helper}"

for FUNCTION in "${LH_BASE}"/functions/*.sh
do
	. "${FUNCTION}"
done

# Setting static variables
DESCRIPTION="manage /etc/kernel-img.conf"
HELP=""
USAGE="${PROGRAM} {install|remove} [--force]"

Arguments "${@}"

# Reading configuration files
Read_conffile config/common
Read_conffile config/bootstrap
Read_conffile config/chroot
Read_conffile config/binary
Read_conffile config/source
Set_defaults

# Requiring stage file
Require_stagefile .stage/bootstrap

case "${1}" in
	install)
		# Restoring cache
		Restore_cache cache/packages_linux-image

		Echo_message "Configuring file /etc/kernel-img.conf"

		# Checking stage file
		Check_stagefile .stage/chroot_linux-image

		# Checking lock file
		Check_lockfile .lock

		# Creating lock file
		Create_lockfile .lock

		if [ -f chroot/etc/kernel-img.conf ]
		then
			# Saving kernel-img.conf
			cp chroot/etc/kernel-img.conf chroot/etc/kernel-img.conf.old
		fi

		# Configuring kernel-img.conf
cat >> chroot/etc/kernel-img.conf << EOF
do_bootloader = No
do_initrd = Yes
warn_initrd = No
EOF

		# Diverting update-initramfs
		#if [ "${LH_INITRAMFS}" = "live-initramfs" ]
		#then
		#	mv chroot/usr/sbin/update-initramfs chroot/usr/sbin/update-initramfs.live-helper
		#fi

		if [ "${LH_LINUX_PACKAGES}" != "none" ]
		then
			for FLAVOUR in ${LH_LINUX_FLAVOURS}
			do
				for PACKAGE in ${LH_LINUX_PACKAGES}
				do
					PACKAGES="${PACKAGES} ${PACKAGE}-${FLAVOUR}"
				done
			done
		fi

		PACKAGES="${PACKAGES} ${LH_INITRAMFS}"

		# Installing linux-image, modules and ${LH_INITRAMFS}
		case "${LH_APT}" in
			apt|apt-get)
				Chroot "apt-get install --yes ${PACKAGES}"
				;;

			aptitude)
				Chroot "aptitude install --assume-yes ${PACKAGES}"
				;;
		esac

		# Saving cache
		Save_cache cache/packages_linux-image

		# Creating stage file
		Create_stagefile .stage/chroot_linux-image
		;;

	remove)
		Echo_message "Deconfiguring file /etc/kernel-img.conf"

		# Checking lock file
		Check_lockfile .lock

		# Creating lock file
		Create_lockfile .lock

		if [ -f chroot/etc/kernel-img.conf.old ]
		then
			# Restoring kernel-img.conf file
			mv chroot/etc/kernel-img.conf.old chroot/etc/kernel-img.conf
		else
			# Removing kernel-img.conf file
			rm -f chroot/etc/kernel-img.conf
		fi

		# Removing stage file
		rm -f .stage/chroot_linux-image
		;;

	*)
		Usage
		;;
esac
