#!/bin/sh

# lh_chroot_packageslists(1) - install packages lists into chroot
# Copyright (C) 2006-2007 Daniel Baumann <daniel@debian.org>
#
# live-helper comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
# This is free software, and you are welcome to redistribute it
# under certain conditions; see COPYING for details.

set -e

# Source common functions
for FUNCTION in /usr/share/live-helper/functions/*.sh
do
	. ${FUNCTION}
done

# Set static variables
DESCRIPTION="install packages lists into chroot"
HELP=""
USAGE="${PROGRAM} [--force]"

Arguments "${@}"

Echo_debug "Init ${PROGRAM}"

# Reading configuration files
Read_conffile config/bootstrap
Read_conffile config/chroot
Read_conffile config/common
Read_conffile config/image
Set_defaults

Breakpoint "chroot_packageslists: Init"

# Requiring stage file
Require_stagefile .stage/bootstrap

# Checking stage file
Check_stagefile .stage/chroot_packageslists

# Checking lock file
Check_lockfile .lock

# Creating lock file
Create_lockfile .lock

if [ -n "${LIVE_PACKAGES_LISTS}" ]
then
	# Restoring cache
	Restore_cache cache/chroot_packageslists

	for LIST in ${LIVE_PACKAGES_LISTS}
	do
		if [ -f /usr/share/live-helper/lists/"${LIST}" ]
		then
			# Copying package list
			grep -v "^#" /usr/share/live-helper/lists/"${LIST}" > chroot/root/"${LIST}"

			# Installing package list
			case "${LH_APT}" in
				apt|apt-get)
					Chroot "xargs --arg-file=/root/${LIST} apt-get install --yes"
					;;

				aptitude)
					Chroot "xargs --arg-file=/root/${LIST} aptitude install --assume-yes"
					;;
			esac

			# Removing package list
			rm -f chroot/root/"${LIST}"
		fi
	done

	# Saving cache
	Save_cache cache/chroot_packageslists

	# Creating stage file
	Create_stagefile .stage/chroot_packageslists
fi
