#!/bin/sh

# lh_chroot(1) - customize the Debian system
# Copyright (C) 2006-2007 Daniel Baumann <daniel@debian.org>
#
# live-helper comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
# This is free software, and you are welcome to redistribute it
# under certain conditions; see COPYING for details.

set -e

# Including common functions
LH_BASE="${LH_BASE:-/usr/share/live-helper}"

for FUNCTION in "${LH_BASE}"/functions/*.sh
do
	. "${FUNCTION}"
done

# Setting static variables
DESCRIPTION="customize the Debian system"
HELP=""
USAGE="${PROGRAM} [--force]"

Arguments "${@}"

# Reading configuration files
Read_conffile config/common
Read_conffile config/bootstrap
Read_conffile config/chroot
Read_conffile config/binary
Read_conffile config/source
Read_conffile "${LH_CONFIG}"
Set_defaults

# Configuring chroot
lh_chroot_cache restore ${*}
lh_chroot_proc install ${*}
lh_chroot_sysfs install ${*}
lh_chroot_debianchroot install ${*}
lh_chroot_dpkg install ${*}
lh_chroot_sysv-rc install ${*}
lh_chroot_hosts install ${*}
lh_chroot_resolv install ${*}
lh_chroot_hostname install ${*}
lh_chroot_apt install ${*}
lh_chroot_sources install ${*}
lh_chroot_linux-image install ${*}

# Customizing chroot
lh_chroot_preseed ${*}
lh_chroot_local-preseed ${*}
lh_chroot_tasks ${*}
lh_chroot_packageslists ${*}
lh_chroot_packages ${*}
lh_chroot_local-packageslists ${*}
lh_chroot_local-packages ${*}
lh_chroot_localization ${*}
lh_chroot_local-includes ${*}
lh_chroot_sysvinit ${*}
lh_chroot_hooks ${*}
lh_chroot_local-hooks ${*}
lh_chroot_symlinks ${*}
lh_chroot_hacks ${*}
lh_chroot_interactive ${*}

# Deconfiguring chroot
lh_chroot_linux-image remove ${*}
lh_chroot_sources remove ${*}
lh_chroot_apt remove ${*}
lh_chroot_hostname remove ${*}
lh_chroot_resolv remove ${*}
lh_chroot_hosts remove ${*}
lh_chroot_sysv-rc remove ${*}
lh_chroot_dpkg remove ${*}
lh_chroot_debianchroot remove ${*}
lh_chroot_sysfs remove ${*}
lh_chroot_proc remove ${*}
lh_chroot_cache save ${*}
