#!/bin/sh

# lh_chroot_localpackages(1) - install local packages into chroot

set -e

# Source common functions
for FUNCTION in /usr/share/live-helper/functions/*.sh
do
	. ${FUNCTION}
done

# Reading configuration files
Read_conffile config/common
Read_conffile config/chroot
Set_defaults

# Requiring stage file
Require_stagefile "${LIVE_ROOT}"/.stage/bootstrap

# Checking stage file
Check_stagefile "${LIVE_ROOT}"/.stage/chroot_localpackages

# Checking lock file
Check_lockfile "${LIVE_ROOT}"/.lock

# Creating lock file
Create_lockfile "${LIVE_ROOT}"/.lock

if ls "${LIVE_ROOT}"/config/chroot_localpackages/*.deb &> /dev/null
then
	# Restore old cache
	if [ -d "${LIVE_ROOT}"/cache/chroot_localpackages ]
	then
		cp "${LIVE_ROOT}"/cache/chroot_localpackages/*.deb "${LIVE_CHROOT}"/var/cache/apt/archives
	fi

	# Copying packages
	cp "${LIVE_ROOT}"/config/chroot_localpackages/*.deb "${LIVE_CHROOT}"/root

	# Installing packages
        Chroot "find /root -name *.deb" > "${LIVE_CHROOT}"/root/localpackages
	Chroot "xargs --arg-file=/root/localpackages dpkg -i" || true

	# Cleaning dependencies
	case "${LH_APT}" in
		apt)
			Chroot "apt-get install -f --yes"
			;;

		aptitude)
			Chroot "aptitude install -f --assume-yes"
			;;
	esac

	# Removing package files
	rm -f "${LIVE_CHROOT}"/root/*.deb
	rm -f "${LIVE_CHROOT}"/root/localpackages

	# Saving new cache
	Chroot "apt-get autoclean"

	if ls "${LIVE_CHROOT}"/var/cache/apt/archives/*.deb &> /dev/null
	then
		if [ ! -d "${LIVE_ROOT}"/cache/chroot_localpackages ]
		then
			mkdir -p "${LIVE_ROOT}"/cache/chroot_localpackages
		fi

		mv -f "${LIVE_CHROOT}"/var/cache/apt/archives/*.deb "${LIVE_ROOT}"/cache/chroot_localpackages
	fi

	# Creating stage file
	Create_stagefile "${LIVE_ROOT}"/.stage/chroot_localpackages
fi
