#!/bin/sh

# lh_chroot_resolv(1) - manage /etc/resolv.conf

set -e

# Source common functions
for FUNCTION in /usr/share/live-helper/functions/*.sh
do
	. ${FUNCTION}
done

# Reading configuration files
Read_conffile config/common
Read_conffile config/chroot
Set_defaults

# Requiring stage file
Require_stagefile .stage/bootstrap

# Checking lock file
Check_lockfile .lock

# Creating lock file
Create_lockfile .lock

case "${1}" in
	install)
		# Checking stage file
		Check_stagefile .stage/chroot_resolv

		if [ -f chroot/etc/resolv.conf ]
		then
			# Save resolv file
			cp chroot/etc/resolv.conf chroot/etc/resolv.conf.orig
		fi

		if [ -f /etc/resolv.conf ]
		then
			# Copy resolv file
			cp /etc/resolv.conf chroot/etc/resolv.conf
		fi

		# Creating stage file
		Create_stagefile .stage/chroot_resolv
		;;

	remove)
		if [ -f chroot/etc/resolv.conf.orig ]
		then
			# Restore resolv file
			mv chroot/etc/resolv.conf.orig chroot/etc/resolv.conf
		else
			# Remove resolv file
			rm -f chroot/etc/resolv.conf
		fi

		# Removing stage file
		rm -f .stage/chroot_resolv
		;;

	*)
		echo "Usage: ${0} {install|remove}"
		exit 1
		;;
esac
