#!/bin/sh

# lh_chroot_resolv(1) - manage /etc/resolv.conf
# Copyright (C) 2006-2008 Daniel Baumann <daniel@debian.org>
#
# live-helper comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
# This is free software, and you are welcome to redistribute it
# under certain conditions; see COPYING for details.

set -e

# Including common functions
LH_BASE="${LH_BASE:-/usr/share/live-helper}"

for FUNCTION in "${LH_BASE}"/functions/*.sh
do
	. "${FUNCTION}"
done

# Setting static variables
DESCRIPTION="manage /etc/resolv.conf"
HELP=""
USAGE="${PROGRAM} {install|remove} [--force]"

Arguments "${@}"

# Reading configuration files
Read_conffile config/common
Read_conffile config/bootstrap
Read_conffile config/chroot
Read_conffile config/binary
Read_conffile config/source
Read_conffile "${LH_CONFIG}"
Set_defaults

# Requiring stage file
Require_stagefile .stage/bootstrap

case "${1}" in
	install)
		Echo_message "Configuring file /etc/resolv.conf"

		# Checking stage file
		Check_stagefile .stage/chroot_resolv

		# Checking lock file
		Check_lockfile .lock

		# Creating lock file
		Create_lockfile .lock

		if [ -e chroot/etc/resolv.conf ]
		then
			# Save resolv file or symlink
			mv chroot/etc/resolv.conf chroot/etc/resolv.conf.orig
		fi

		if [ -f /etc/resolv.conf ]
		then
			# Copy resolv file
			cp /etc/resolv.conf chroot/etc/resolv.conf
		fi

		# Creating stage file
		Create_stagefile .stage/chroot_resolv
		;;

	remove)
		Echo_message "Deconfiguring file /etc/resolv.conf"

		# Checking lock file
		Check_lockfile .lock

		# Creating lock file
		Create_lockfile .lock

		if [ -e chroot/etc/resolv.conf.orig ]
		then
			# Restoring resolv file or symlink
			mv chroot/etc/resolv.conf.orig chroot/etc/resolv.conf
		else
			# Truncating resolv file
			Truncate chroot/etc/resolv.conf
		fi

		# Removing stage file
		rm -f .stage/chroot_resolv
		;;

	*)
		Usage
		;;
esac
