#!/bin/sh

# lh_chroot_packages(1) - install packages into chroot
# Copyright (C) 2006-2007 Daniel Baumann <daniel@debian.org>
#
# live-helper comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
# This is free software, and you are welcome to redistribute it
# under certain conditions; see COPYING for details.

set -e

# Including common functions
LH_BASE="${LH_BASE:-/usr/share/live-helper}"

for FUNCTION in "${LH_BASE}"/functions/*.sh
do
	. "${FUNCTION}"
done

# Setting static variables
DESCRIPTION="install packages into chroot"
HELP=""
USAGE="${PROGRAM} [--force]"

Arguments "${@}"

# Reading configuration files
Read_conffile config/common
Read_conffile config/bootstrap
Read_conffile config/chroot
Read_conffile config/binary
Read_conffile config/source
Set_defaults

Echo_message "Begin installing packages..."

# Requiring stage file
Require_stagefile .stage/bootstrap

# Checking stage file
Check_stagefile .stage/chroot_packages

# Checking lock file
Check_lockfile .lock

# Creating lock file
Create_lockfile .lock

if [ -n "${LIVE_PACKAGES}" ] && [ "${LIVE_PACKAGES}" != "none" ]
then
	# Restoring cache
	Restore_cache cache/packages_packages

	# Installing packages
	case "${LH_APT}" in
		apt|apt-get)
			Chroot "apt-get install --yes ${LIVE_PACKAGES}"
			;;

		aptitude)
			Chroot "aptitude install --assume-yes ${LIVE_PACKAGES}"
			;;
	esac

	# Saving cache
	Save_cache cache/packages_packages

	# Creating stage file
	Create_stagefile .stage/chroot_packages
fi
