#!/bin/sh

# lh_chroot_hosts(1) - manage /etc/hosts

set -e

# Source common functions
for FUNCTION in /usr/share/live-helper/functions/*.sh
do
	. ${FUNCTION}
done

# Reading configuration files
Read_conffile config/common
Read_conffile config/chroot
Set_defaults

# Requiring stage file
Require_stagefile .stage/bootstrap

# Checking lock file
Check_lockfile .lock

# Creating lock file
Create_lockfile .lock

case "${1}" in
	install)
		# Checking stage file
		Check_stagefile .stage/chroot_hosts

		if [ -f chroot/etc/hosts ]
		then
			# Save hosts file
			cp chroot/etc/hosts chroot/etc/hosts.orig
		fi

		if [ -f /etc/hosts ]
		then
			# Copy hosts file
			cp /etc/hosts chroot/etc/hosts
		fi

		# Creating stage file
		Create_stagefile .stage/chroot_hosts
		;;

	remove)
		if [ -f chroot/etc/hosts.orig ]
		then
			# Restore hosts file
			mv chroot/etc/hosts.orig chroot/etc/hosts
		else
			# Remove hosts file
			rm -f chroot/etc/hosts
		fi

		# Removing stage file
		rm -f .stage/chroot_hosts
		;;

	*)
		echo "Usage: ${0} {install|remove}"
		exit 1
		;;
esac
