#!/bin/sh

if [ ! -f "${LIVE_ROOT}"/.stage/bootstrap ]
then
	# Create chroot directory
	if [ ! -d "${LIVE_CHROOT}" ]
	then
		mkdir -p "${LIVE_CHROOT}"
	fi

	debootstrap --arch="${LIVE_ARCHITECTURE}" --variant=buildd "${LIVE_DISTRIBUTION}" "${LIVE_CHROOT}" "${LIVE_MIRROR}"

	# Touching stage file
	if [ ! -d "${LIVE_ROOT}"/.stage ]
	then
		mkdir "${LIVE_ROOT}"/.stage
	fi

	touch "${LIVE_ROOT}"/.stage/bootstrap
fi
