#!/bin/sh

# lh_installinux <type>

# Removing initrd backup files
rm -f "${LIVE_CHROOT}"/boot/initrd*bak*

# Setting destination directory
case "${1}" in
	iso)
		DESTDIR="${LIVE_ROOT}/binary/isolinux"
		;;

	net)
		DESTDIR="${LIVE_ROOT}/tftpboot"
		;;

	usb)
		DESTDIR="${LIVE_ROOT}/binary"
		;;
esac

# Installing linux image
if [ "${LIVE_FLAVOUR}" = "minimal" ] || [ "${LIVE_FLAVOUR}" = "mini" ]
then
	mv "${LIVE_CHROOT}"/boot/vmlinuz* "${DESTDIR}"/vmlinuz
	mv "${LIVE_CHROOT}"/boot/initrd.img* "${DESTDIR}"/initrd.gz
	rm -f "${LIVE_CHROOT}"/vmlinuz "${LIVE_CHROOT}"/initrd.img
else
	cp "${LIVE_CHROOT}"/boot/vmlinuz* "${DESTDIR}"/vmlinuz
	cp "${LIVE_CHROOT}"/boot/initrd.img* "${DESTDIR}"/initrd.gz
fi
