#!/bin/sh

# lh_installapt

# Install aptitude
lh_chroot "apt-get install --yes --force-yes aptitude"

# Install secure apt
if [ "${LIVE_DISTRIBUTION}" = "unstable" ] || [ "${LIVE_DISTRIBUTION}" = "${CODENAME_UNSTABLE}" ] || \
[ "${LIVE_DISTRIBUTION}" = "testing" ] || [ "${LIVE_DISTRIBUTION}" = "${CODENAME_TESTING}" ]
then
	if [ "${LIVE_FLAVOUR}" != "minimal" ] || [ "${LIVE_FLAVOUR}" != "mini" ]
	then
		lh_chroot "apt-get install --yes --force-yes ${LIVE_REPOSITORY_KEYRING}"

		for NAME in ${LIVE_REPOSITORIES}
		do
			eval REPOSITORY_KEY="$`echo LIVE_REPOSITORY_KEY_$NAME`"
			eval REPOSITORY_KEYRING="$`echo LIVE_REPOSITORY_KEYRING_$NAME`"

			if [ -n "${REPOSITORY_KEYRING}" ]
			then
				lh_chroot "aptiude install ${REPOSITORY_KEYRING}"
			elif [ -n "${REPOSITORY_KEY}" ]
			then
				lh_chroot "wget ${REPOSITORY_KEY}"
				lh_chroot "apt-key add `basename ${REPOSITORY_KEY}`"
				lh_chroot "rm -f `basename ${REPOSITORY_KEY}`"
			fi
		done
	fi
fi
