#!/bin/sh

# lh_installinux <type>

# Removing initrd backup files
rm -f "${LIVE_CHROOT}"/boot/initrd*bak*

# Setting destination directory
case "${1}" in
	iso)
		DESTDIR="${LIVE_ROOT}/binary/isolinux"
		;;

	net)
		DESTDIR="${LIVE_ROOT}/tftpboot"
		;;

	usb)
		DESTDIR="${LIVE_ROOT}/binary"
		;;
esac

# Installing linux image
cp "${LIVE_CHROOT}"/boot/vmlinuz* "${DESTDIR}"/vmlinuz
cp "${LIVE_CHROOT}"/boot/initrd.img* "${DESTDIR}"/initrd.gz
