#!/bin/sh

# lh_installpackagelists

# Install packages list
if [ -n "${LIVE_PACKAGE_LIST}" ]
then
	if [ "${LIVE_PACKAGE_LIST}" = "everything" ]
	then
		#for FILE in "${LIVE_CHROOT}"/var/lib/apt/lists/*_Packages
		#do
		#	awk '/Package: / { print $2 }' "${FILE}" | grep -v ".*-dbg$" >> "${LIVE_CHROOT}"/root/everything
		#done

		#lh_chroot "xargs --arg-file=/root/everything aptitude install --assume-yes"
		#rm -f "${LIVE_CHROOT}"/root/everything

		# FIXME

		for SECTION in admin base comm devel doc editors electronics embedded games gnome graphics hamradio interpreters kde libs libdevel mail math misc net news oldlibs otherosfs perl python science shells sound tex text utils web x11
		do
			lh_chroot "aptitude install --assume-yes ~s${SECTION}"
		done
	else
		grep -v "^#" "${LIVE_PACKAGE_LIST}" > "${LIVE_CHROOT}"/root/"`basename ${LIVE_PACKAGE_LIST}`"
		lh_chroot "xargs --arg-file=/root/`basename ${LIVE_PACKAGE_LIST}` aptitude install --assume-yes"
		rm -f "${LIVE_CHROOT}"/root/"`basename ${LIVE_PACKAGE_LIST}`"
	fi
fi
