#!/bin/sh

# lh_local(1) - use a local live-helper version
# Copyright (C) 2006-2009 Daniel Baumann <daniel@debian.org>
#
# live-helper comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
# This is free software, and you are welcome to redistribute it
# under certain conditions; see COPYING for details.

LH_BASE="${PWD}/live-helper"
PATH="${LH_BASE}/helpers:${PATH}"

export LH_BASE PATH

if [ ! -z "${1}" ]
then
	exec lh "${@}"
fi
