#!/bin/sh

# lh_losetup - wrapper around losetup
# Copyright (C) 2006-2007 Daniel Baumann <daniel@debian.org>
#
# live-helper comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
# This is free software, and you are welcome to redistribute it
# under certain conditions; see COPYING for details.

set -e

# Source common functions
for FUNCTION in /usr/share/live-helper/functions/*.sh
do
	. ${FUNCTION}
done

# Set static variables
DESCRIPTION="wrapper around losetup"
HELP=""
USAGE="${PROGRAM} <device> <file> <partition>"

Arguments "${@}"

# Reading configuration files
Read_conffile config/common
Set_defaults

if [ -z "${1}" ]
then
	DEVICE="`${LH_LOSETUP} -f`"
else
	DEVICE="${1}"
fi

FILE="${2}"
PARTITION="${3}"

${LH_LOSETUP} "${DEVICE}" "${FILE}"
FDISK_OUT="`fdisk -l -u ${DEVICE} 2>&1`"
${LH_LOSETUP} -d "${DEVICE}"

LOOPDEVICE="`echo ${DEVICE}p${PARTITION:=1}`"
CYL=`echo "$FDISK_OUT" | sed -ne "s_^$LOOPDEVICE[ *]*\([0-9]*\).*_\1_p"`
#OFFSET="`expr 512 '*' ${CYL}`"
OFFSET="$((CYL*512))"

echo loop $DEVICE at offset $OFFSET

if [ "${PARTITION}" = "0" ]
then
	${LH_LOSETUP} "${DEVICE}" "${FILE}"
else
	${LH_LOSETUP} -o "${OFFSET}" "${DEVICE}" "${FILE}"
fi
