#!/bin/sh

# lh_localdeb

if [ `ls "${LIVE_ROOT}"/localdeb/*.deb` ]
then
	cp "${LIVE_ROOT}"/localdeb/*.deb "${LIVE_CHROOT}"/root
	lh_chroot "dpkg -i /root/*.deb"
	rm -f "${LIVE_CHROOT}"/root/*.deb
fi
