#!/bin/sh

# lh_manifest

# Add filesystem.manifest
lh_chroot "dpkg --get-selections" | awk '{ print $1 }' | sort -u > "${LIVE_ROOT}"/filesystem.manifest

if [ -n "${LIVE_MANIFEST}" ]
then
	# FIXME; what should that be good for anyway?
	lh_chroot "aptitude install --assume-yes ${LIVE_MANIFEST}"
	lh_chroot "dpkg-query -W \*" | awk '$2 ~ /./ {print $1 " " $2 }' > "${LIVE_ROOT}"/filesystem.manifest-desktop
fi
