#!/bin/sh

# lh_patchnetwork.sh <action>

# Packages which are manually installed inside the chroot are installed
# from the network. Therefore, we need to be able to resolv hosts.

case "${1}" in
	apply)
		lh_confignetwork apply-hosts
		lh_confignetwork apply-resolv
		;;

	deapply)
		lh_confignetwork deapply-hosts
		lh_confignetwork deapply-resolv
		;;
esac
