#!/bin/sh

# lh_patchrunlevel.sh <action>

# Disabling all init scripts with a blocking policy as in
# /usr/share/doc/sysv-rc/README.policy-rc.d.gz.

case "${1}" in
	apply)
		# Create init policy
		cat  > "${LIVE_CHROOT}"/usr/sbin/policy-rc.d << EOF
#!/bin/sh

echo
echo "Warning: invoke-rc.d policy in action. Skiping daemon starting"

exit 101
EOF

		chmod 0755 "${LIVE_CHROOT}"/usr/sbin/policy-rc.d
		;;

	deapply)
		# Removing init policy
		rm -f "${LIVE_CHROOT}"/usr/sbin/policy-rc.d
		;;
esac
