#!/bin/sh

# lh_source_iso(1) - build source iso image
# Copyright (C) 2006-2007 Daniel Baumann <daniel@debian.org>
#
# live-helper comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
# This is free software, and you are welcome to redistribute it
# under certain conditions; see COPYING for details.

set -e

# Source common functions
for FUNCTION in /usr/share/live-helper/functions/*.sh
do
	. ${FUNCTION}
done

# Set static variables
DESCRIPTION="build source iso image"
HELP=""
USAGE="${PROGRAM} [--force]"

Arguments "${@}"

Echo_debug "Init ${PROGRAM}"

# Reading configuration files
Read_conffile config/common
Read_conffile config/bootstrap
Read_conffile config/chroot
Read_conffile config/binary
Read_conffile config/source
Set_defaults

if [ "${LIVE_SOURCE}" != "enabled" ]
then
	exit 0
fi

for IMAGE in ${LIVE_SOURCE_IMAGES}
do
	if [ "${IMAGE}" = "iso" ]
	then
		Breakpoint "source_iso: Init"

		# Requiring stage file
		Require_stagefile .stage/source_debian

		# Checking stage file
		Check_stagefile .stage/source_iso

		# Checking lock file
		Check_lockfile .lock

		# Creating lock file
		Create_lockfile .lock

		# Checking depends
		Check_package chroot/usr/bin/"${LH_GENISOIMAGE}" ${LH_GENISOIMAGE}

		# Installing depends
		Install_package

		# Remove old source
		if [ -f source.iso ]
		then
			rm -f source.iso
		fi

		if [ "${LH_VERBOSE}" = "enabled" ]
		then
			GENISOIMAGE_OPTIONS="${GENISOIMAGE_OPTIONS} -v"
		fi

		# Moving image
		mv source chroot

cat >> chroot/source.sh << EOF
${LH_GENISOIMAGE} ${GENISOIMAGE_OPTIONS} -A "Debian Live" -p "Debian Live; http://debian-live.alioth.debian.org/; debian-live-devel@lists.alioth.debian.org" -publisher "Debian Live; http://debian-live.alioth.debian.org/; debian-live-devel@lists.alioth.debian.org" -V "${LIVE_ISO_VOLUME}" -o source.iso -r -J -l -cache-inodes source
EOF

		Chroot "sh source.sh"

		# Move image
		mv chroot/source chroot/source.iso ./
		rm -f chroot/source.sh

		# Removing depends
		Remove_package

		# Creating stage file
		Create_stagefile .stage/source_iso
	fi
done
