#!/bin/sh

# lh_source_debian(1) - download sources
# Copyright (C) 2006-2007 Daniel Baumann <daniel@debian.org>
#
# live-helper comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
# This is free software, and you are welcome to redistribute it
# under certain conditions; see COPYING for details.

set -e

# Including common functions
LH_BASE="${LH_BASE:-/usr/share/live-helper}"

for FUNCTION in "${LH_BASE}"/functions/*.sh
do
	. "${FUNCTION}"
done

# Setting static variables
DESCRIPTION="debian sources"
HELP=""
USAGE="${PROGRAM} [--force]"

Arguments "${@}"

# Reading configuration files
Read_conffile config/common
Read_conffile config/bootstrap
Read_conffile config/chroot
Read_conffile config/binary
Read_conffile config/source
Read_conffile "${LH_CONFIG}"
Set_defaults

if [ "${LH_SOURCE}" != "enabled" ]
then
	exit 0
fi

Echo_message "Begin downloading sources..."

# Requiring stage file
Require_stagefile .stage/bootstrap

# Checking stage file
Check_stagefile .stage/source_debian

# Checking lock file
Check_lockfile .lock

# Creating lock file
Create_lockfile .lock

# Remove old sources
if [ -d source/debian ]
then
	rm -rf source/debian
fi

# Download sources
Chroot "dpkg --get-selections" | awk '{ print $1 }' > chroot/root/dpkg-selection.txt

cat >> chroot/root/dpkg-selection.txt << EOF
${LH_BOOTLOADER}
live-helper
${LH_INITRAMFS}
dosfstools
genisoimage
parted
squashfs-tools
genext2fs
mtd-tools
EOF

case "${LH_ARCHITECTURE}" in
	amd64|i386)

cat >> chroot/root/dpkg-selection.txt << EOF
mtools
syslinux
grub
EOF

if [ "${LH_MEMTEST}" != "disabled" ] && [ "${LH_MEMTEST}" != "none" ]
then
	echo "${LH_MEMTEST}" >> chroot/root/dpkg-selection.txt
fi
		;;

	powerpc)
		echo "yaboot" >> chroot/root/dpkg-selection.txt
		;;
esac

Chroot "xargs --arg-file=/root/dpkg-selection.txt apt-get ${APT_OPTIONS} --download-only source"
rm -f chroot/root/dpkg-selection.txt

# Sort sources
for DSC in chroot/*.dsc
do
	SOURCE="$(sed  -n 's|^Source: ||p' ${DSC})"

	case "${SOURCE}" in
		lib?*)
			LETTER="$(echo ${SOURCE} | sed 's|\(....\).*|\1|')"
			;;

		*)
			LETTER="$(echo ${SOURCE} | sed 's|\(.\).*|\1|')"
			;;
	esac

	# Install directory
	mkdir -p source/debian/"${LETTER}"/"${SOURCE}"

	# Move files
	mv chroot/"${SOURCE}"_* source/debian/"${LETTER}"/"${SOURCE}"
done

# Creating stage file
Create_stagefile .stage/source_debian
