#!/bin/sh

# lh_source_usb(1) - build source image
# Copyright (C) 2006-2007 Daniel Baumann <daniel@debian.org>
#
# live-helper comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
# This is free software, and you are welcome to redistribute it
# under certain conditions; see COPYING for details.

set -e

# Source common functions
for FUNCTION in /usr/share/live-helper/functions/*.sh
do
	. ${FUNCTION}
done

# Set static variables
DESCRIPTION="build source image"
HELP=""
USAGE="${PROGRAM} [--force]"

Arguments "${@}"

Echo_debug "Init ${PROGRAM}"

# Reading configuration files
Read_conffile config/bootstrap
Read_conffile config/chroot
Read_conffile config/common
Read_conffile config/image
Set_defaults

Breakpoint "source_usb: Init"

if [ "${LIVE_SOURCE}" != "enabled" ]
then
	exit 0
fi

for IMAGE in ${LIVE_SOURCE_IMAGE}
do
	if [ "${IMAGE}" = "usb" ]
	then
		# Requiring stage file
		Require_stagefile .stage/source_download

		# Checking stage file
		Check_stagefile .stage/source_usb

		# Checking lock file
		Check_lockfile .lock

		# Creating lock file
		Create_lockfile .lock

		if [ ! -f chroot/sbin/mkdosfs ]
		then
			PACKAGES="${PACKAGES} dosfstools"
		fi

		if [ ! -f chroot/sbin/parted ]
		then
			PACKAGES="${PACKAGES} parted"
		fi

		if [ -n "${PACKAGES}" ]
		then
			# Installing packages
			case "${LH_APT}" in
				apt|apt-get)
					Chroot "apt-get install --yes ${PACKAGES}"
					;;

				aptitude)
					Chroot "aptitude install --assume-yes ${PACKAGES}"
					;;
			esac
		fi

		# Remove old source
		if [ -f source.img ]
		then
			rm -f source.img
		fi

		# Everything which comes here needs to be cleaned up,
		DU_DIM="`du -ms source | cut -f1`"
		REAL_DIM="`expr ${DU_DIM} + ${DU_DIM} / 20`" # Just 5% more to be sure, need something more sophistcated here...
		dd if=/dev/zero of=source.img bs=1024k count=${REAL_DIM}
		FREELO="`${LH_LOSETUP} -f`"
		if [ ! -b chroot/${FREELO} ]
		then
			MAKEDEV="true"

			mv chroot/dev chroot/dev.tmp
			find /dev | cpio -dmpu chroot
		fi

		echo "!!! The following error/warning messages can be ignored !!!"
		lh_losetup $FREELO source.img 0
		Chroot "parted -s ${FREELO} mklabel msdos" || true
		Chroot "parted -s ${FREELO} mkpartfs primary fat16 0.0 100%" || true
		Chroot "parted -s ${FREELO} set 1 lba off" || true
		${LH_LOSETUP} -d ${FREELO}

		lh_losetup $FREELO source.img 1
		Chroot "mkfs.msdos -n DEBIAN_LIVE ${FREELO}"
		mkdir -p source.tmp
		mount ${FREELO} source.tmp
		cp -r source/* source.tmp
		umount source.tmp
		rmdir source.tmp
		${LH_LOSETUP} -d ${FREELO}
		echo "!!! The above error/warning messages can be ignored !!!"

		if [ -n "${MAKEDEV}" ]
		then
			rm -f chroot/dev
			mv chroot/dev.tmp chroot/dev
		fi

		if [ -n "${PACKAGES}" ]
		then
			# Removing packages
			case "${LH_APT}" in
				apt|apt-get)
					Chroot "apt-get remove --purge --yes ${PACKAGES}"
					;;

				aptitude)
					Chroot "aptitude purge --assume-yes ${PACKAGES}"
					;;
			esac
		fi

		# Creating stage file
		Create_stagefile .stage/source_usb
	fi
done
