#!/bin/sh

# lh_source_debian-live(1) - copy debian-live config into source
# Copyright (C) 2006-2008 Daniel Baumann <daniel@debian.org>
#
# live-helper comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
# This is free software, and you are welcome to redistribute it
# under certain conditions; see COPYING for details.

set -e

# Including common functions
LH_BASE="${LH_BASE:-/usr/share/live-helper}"

for FUNCTION in "${LH_BASE}"/functions/*.sh
do
	. "${FUNCTION}"
done

# Setting static variables
DESCRIPTION="copy debian-live config into source"
HELP=""
USAGE="${PROGRAM} [--force]"

Arguments "${@}"

# Reading configuration files
Read_conffile config/all config/common config/bootstrap config/chroot config/binary config/source
Set_defaults

if [ "${LH_SOURCE}" != "enabled" ]
then
	exit 0
fi

Echo_message "Begin copying live-helper configuration..."

# Requiring stage file
Require_stagefile .stage/bootstrap

# Checking stage file
Check_stagefile .stage/source_debian-live

# Checking lock file
Check_lockfile .lock

# Creating lock file
Create_lockfile .lock

# Remove old sources
if [ -d source/debian-live ]
then
	rm -rf source/debian-live
fi

# Copy system configuration
mkdir -p source/debian-live
cp -a config source/debian-live

# Create tarball
cd source

if gzip --help | grep -q '\-\-rsyncable'
then
	tar cf debian-live-config_$(date +%Y%m%d.%s).tar debian-live
	gzip --rsyncable --best debian-live-config_$(date +%Y%m%d.%s).tar
else
	tar cfz debian-live-config_$(date +%Y%m%d.%s).tar.gz debian-live
fi

cd "${OLDPWD}"

rm -rf source/debian-live/config
mv source/debian-live-config_*.tar.gz source/debian-live

# Creating stage file
Create_stagefile .stage/source_debian-live
