#!/bin/sh

# lh_source_disk (1) - install disk information into source
# Copyright (C) 2006-2009 Daniel Baumann <daniel@debian.org>
#
# live-helper comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
# This is free software, and you are welcome to redistribute it
# under certain conditions; see COPYING for details.

set -e

# Including common functions
. "${LH_BASE:-/usr/share/live-helper}"/functions.sh

# Setting static variables
DESCRIPTION="$(Echo 'install disk information into source')"
HELP=""
USAGE="${PROGRAM} [--force]"

Arguments "${@}"

# Reading configuration files
Read_conffiles config/all config/common config/bootstrap config/chroot config/binary config/source
Set_defaults

if [ "${LH_SOURCE_IMAGES}" != "iso" ]
then
	exit 0
fi

Echo_message "Begin installing disk information..."

# Requiring stage file
Require_stagefile .stage/config .stage/bootstrap

# Checking stage file
Check_stagefile .stage/source_disk

# Checking lock file
Check_lockfile .lock

# Creating lock file
Create_lockfile .lock

mkdir -p source/.disk

TITLE="Debian GNU/Linux"
DISTRIBUTION="$(echo ${LH_DISTRIBUTION} | cut -b 1 | tr '[a-z]' '[A-Z]')"
DISTRIBUTION="${DISTRIBUTION}$(echo ${LH_DISTRIBUTION} | cut -b 2-)"
eval VERSION="$`echo RELEASE_${LH_DISTRIBUTION}`"

case "${LH_MODE}" in
	debian)
		STRING="Official Snapshot ${ARCHITECTURE}"
		;;

	debian-release)
		STRING="Official ${ARCHITECTURE}"
		;;

	ubuntu)
		TITLE="Ubuntu GNU/Linux"
		STRING="Build ${ARCHITECTURE}"
		;;

	*)
		STRING="Snapshot ${ARCHITECTURE}"
		;;
esac

case "${LH_DEBIAN_INSTALLER}" in
	cdrom)
		echo "${TITLE} ${VERSION} \"${DISTRIBUTION}\" - ${STRING} LIVE/CD Source $(date +%Y%m%d-%H:%M)" > source/.disk/info
		;;

	enabled|netinst)
		echo "${TITLE} ${VERSION} \"${DISTRIBUTION}\" - ${STRING} LIVE/NETINST Source $(date +%Y%m%d-%H:%M)" > source/.disk/info
		;;

	live)
		echo "${TITLE} ${VERSION} \"${DISTRIBUTION}\" - ${STRING} LIVE/INSTALL Source $(date +%Y%m%d-%H:%M)" > source/.disk/info
		;;

	businesscard)
		echo "${TITLE} ${VERSION} \"${DISTRIBUTION}\" - ${STRING} LIVE/BC Source $(date +%Y%m%d-%H:%M)" > source/.disk/info
		;;

	disabled)
		echo "${TITLE} ${VERSION} \"${DISTRIBUTION}\" - ${STRING} LIVE Source $(date +%Y%m%d-%H:%M)" > source/.disk/info
		;;
esac

# Creating stage file
Create_stagefile .stage/source_disk
