#!/bin/sh

# lh_source_debian-live(1) - copy debian-live config into source
# Copyright (C) 2006-2009 Daniel Baumann <daniel@debian.org>
#
# live-helper comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
# This is free software, and you are welcome to redistribute it
# under certain conditions; see COPYING for details.

set -e

# Including common functions
. "${LH_BASE:-/usr/share/live-helper}"/live-helper.sh

# Setting static variables
DESCRIPTION="$(Echo 'copy debian-live config into source')"
HELP=""
USAGE="${PROGRAM} [--force]"

Arguments "${@}"

# Reading configuration files
Read_conffiles config/all config/common config/bootstrap config/chroot config/binary config/source
Set_defaults

if [ "${LH_SOURCE}" != "enabled" ]
then
	exit 0
fi

Echo_message "Begin copying live-helper configuration..."

# Requiring stage file
Require_stagefile .stage/config .stage/bootstrap

# Checking stage file
Check_stagefile .stage/source_debian-live

# Checking lock file
Check_lockfile .lock

# Creating lock file
Create_lockfile .lock

# Remove old sources
if [ -d source/debian-live ]
then
	rm -rf source/debian-live
fi

# Copy system configuration
mkdir -p source/debian-live
cp -a config source/debian-live

if Find_files scripts/*
then
	cp -a scripts source/debian-live
fi

# Create tarball
cd source

SUFFIX="$(date +%Y%m%d.%s)"

tar cf debian-live-config_${SUFFIX}.tar debian-live
gzip ${GZIP_OPTIONS} debian-live-config_${SUFFIX}.tar

cd "${OLDPWD}"

rm -rf source/debian-live/config
mv source/debian-live-config_${SUFFIX}.tar.gz source/debian-live

# Creating stage file
Create_stagefile .stage/source_debian-live
