#!/bin/sh

# lh_source(1) - build source images
# Copyright (C) 2006-2007 Daniel Baumann <daniel@debian.org>
#
# live-helper comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
# This is free software, and you are welcome to redistribute it
# under certain conditions; see COPYING for details.

set -e

# Including common functions
LH_BASE="${LH_BASE:-/usr/share/live-helper}"

for FUNCTION in "${LH_BASE}"/functions/*.sh
do
	. "${FUNCTION}"
done

# Setting static variables
DESCRIPTION="build source images"
HELP=""
USAGE="${PROGRAM} [--force]"

Arguments "${@}"

# Reading configuration files
Read_conffile config/common
Read_conffile config/bootstrap
Read_conffile config/chroot
Read_conffile config/binary
Read_conffile config/source
Set_defaults

# Enabling network in chroot
lh_chroot_hosts install ${*}
lh_chroot_resolv install ${*}
lh_chroot_sources install ${*}

# Preparing images
lh_source_debian-live ${*}
lh_source_debian ${*}
lh_source_md5sum ${*}

# Building images
lh_source_iso ${*}
lh_source_net ${*}
lh_source_tar ${*}
lh_source_usb-hdd ${*}

# Deconfiguring chroot
rm -f .stage/chroot_sources
lh_chroot_resolv remove ${*}
lh_chroot_hosts remove ${*}
