#!/bin/sh

# lh_source(1) - build source images
# Copyright (C) 2006-2007 Daniel Baumann <daniel@debian.org>
#
# live-helper comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
# This is free software, and you are welcome to redistribute it
# under certain conditions; see COPYING for details.

set -e

# Source common functions
for FUNCTION in /usr/share/live-helper/functions/*.sh
do
	. ${FUNCTION}
done

# Set static variables
DESCRIPTION="build source images"
HELP=""
USAGE="${PROGRAM} [--force]"

Arguments "${@}"

if [ "${FORCE}" = "true" ]
then
	OPTIONS="${OPTIONS} --force"
fi

# Reading configuration files
Read_conffile config/common
Read_conffile config/image
Set_defaults

# Enabling network in chroot
lh_chroot_hosts install "${OPTIONS}"
lh_chroot_resolv install "${OPTIONS}"
lh_chroot_sources install "${OPTIONS}"

# Preparing images
lh_source_config "${OPTIONS}"
lh_source_download "${OPTIONS}"
lh_source_md5sum "${OPTIONS}"

# Building images
lh_source_generic "${OPTIONS}"
lh_source_iso "${OPTIONS}"
lh_source_net "${OPTIONS}"
lh_source_usb "${OPTIONS}"

# Deconfiguring chroot
rm -f .stage/chroot_sources
lh_chroot_resolv remove "${OPTIONS}"
lh_chroot_hosts remove "${OPTIONS}"
