#!/bin/sh

# lh_source_hdd(1) - build source harddisk image
# Copyright (C) 2006-2007 Daniel Baumann <daniel@debian.org>
#
# live-helper comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
# This is free software, and you are welcome to redistribute it
# under certain conditions; see COPYING for details.

set -e

# Source common functions
for FUNCTION in /usr/share/live-helper/functions/*.sh
do
	. ${FUNCTION}
done

# Set static variables
DESCRIPTION="build source harddisk image"
HELP=""
USAGE="${PROGRAM} [--force]"

Arguments "${@}"

Echo_debug "Init ${PROGRAM}"

# Reading configuration files
Read_conffile config/bootstrap
Read_conffile config/chroot
Read_conffile config/common
Read_conffile config/image
Set_defaults

Breakpoint "source_hdd: Init"

if [ "${LIVE_SOURCE}" != "enabled" ]
then
	exit 0
fi

for IMAGE in ${LIVE_SOURCE_IMAGE}
do
	if [ "${IMAGE}" = "hdd" ]
	then
		# Requiring stage file
		Require_stagefile .stage/source_download

		# Checking stage file
		Check_stagefile .stage/source_hdd

		# Checking lock file
		Check_lockfile .lock

		# Creating lock file
		Create_lockfile .lock

		# Remove old source
		if [ -f source-hdd.tar.gz ]
		then
			rm -f source-hdd.tar.gz
		fi

		# Create tarball
		tar cfz source-hdd.tar.gz source

		# Creating stage file
		Create_stagefile .stage/source_hdd
	fi
done
