#!/bin/sh

# lh_source_generic(1) - build source generic image
# Copyright (C) 2006-2007 Daniel Baumann <daniel@debian.org>
#
# live-helper comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
# This is free software, and you are welcome to redistribute it
# under certain conditions; see COPYING for details.

set -e

# Including common functions
LH_BASE="${LH_BASE:-/usr/share/live-helper}"

for FUNCTION in "${LH_BASE}"/functions/*.sh
do
	. "${FUNCTION}"
done

# Setting static variables
DESCRIPTION="build source generic image"
HELP=""
USAGE="${PROGRAM} [--force]"

Arguments "${@}"

# Reading configuration files
Read_conffile config/common
Read_conffile config/bootstrap
Read_conffile config/chroot
Read_conffile config/binary
Read_conffile config/source
Set_defaults

if [ "${LIVE_SOURCE}" != "enabled" ]
then
	exit 0
fi

if ! echo "${LIVE_SOURCE_IMAGES}" | grep -qs generic
then
        exit 0
fi

Echo_message "Begin building source generic image..."
Echo_message "This may take a while."

# Requiring stage file
Require_stagefile .stage/source_debian

# Checking stage file
Check_stagefile .stage/source_generic

# Checking lock file
Check_lockfile .lock

# Creating lock file
Create_lockfile .lock

# Remove old source
if [ -f source.tar ]
then
	rm -f source.tar
fi

# Create tarball
tar cf source.tar source

# Creating stage file
Create_stagefile .stage/source_generic
