#!/bin/sh

# lh_source_md5sum(1) - create source md5sums
# Copyright (C) 2006-2007 Daniel Baumann <daniel@debian.org>
#
# live-helper comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
# This is free software, and you are welcome to redistribute it
# under certain conditions; see COPYING for details.

set -e

# Including common functions
LH_BASE="${LH_BASE:-/usr/share/live-helper}"

for FUNCTION in "${LH_BASE}"/functions/*.sh
do
	. "${FUNCTION}"
done

# Setting static variables
DESCRIPTION="create source md5sums"
HELP=""
USAGE="${PROGRAM} [--force]"

Arguments "${@}"

# Reading configuration files
Read_conffile config/common
Read_conffile config/bootstrap
Read_conffile config/chroot
Read_conffile config/binary
Read_conffile config/source
Read_conffile "${LH_CONFIG}"
Set_defaults

if [ "${LH_SOURCE}" != "enabled" ]
then
	exit 0
fi

if [ "${LH_CHECKSUMS}" != "enabled" ]
then
	exit 0
fi

Echo_message "Begin creating source md5sum.txt..."

# Requiring stage file
Require_stagefile .stage/source_debian

# Checking stage file
Check_stagefile .stage/source_md5sum

# Checking lock file
Check_lockfile .lock

# Creating lock file
Create_lockfile .lock

# Remove old md5sums
if [ -f source/md5sum.txt ]
then
	rm -f source/md5sum.txt
fi

# Calculating md5sums
cd source
find . -type f | sort | xargs md5sum > ../md5sum.txt

cat > md5sum.txt << EOF
This file contains the list of md5 checksums of all files on this medium.

You can verify them automatically with the 'integrity-check' boot parameter,
or, manually with: 'md5sum -c md5sum.txt'.


EOF

cat ../md5sum.txt >> md5sum.txt
rm -f ../md5sum.txt

cd "${OLDPWD}"

# Creating stage file
Create_stagefile .stage/source_md5sum
