#!/bin/sh

# lh_source_net(1) - build source net image

set -e

# Source common functions
for FUNCTION in /usr/share/live-helper/functions/*.sh
do
	. ${FUNCTION}
done

# Reading configuration files
Read_conffile config/common
Read_conffile config/image
Set_defaults

if [ "${LIVE_SOURCE}" = "disabled" ]
then
	echo "W: source images disabled (FIXME)"
	exit 0
fi

for IMAGE in ${LIVE_SOURCE_IMAGE}
do
	if [ "${IMAGE}" = "net" ]
	then
		# Requiring stage file
		Require_stagefile "${LIVE_ROOT}"/.stage/source_download

		# Checking lock file
		Check_lockfile "${LIVE_ROOT}"/.lock

		# Creating lock file
		Create_lockfile "${LIVE_ROOT}"/.lock

		# Checking stage file
		Check_stagefile "${LIVE_ROOT}"/.stage/source_net

		# Remove old source
		if [ -f "${LIVE_ROOT}"/source.tar.gz ]
		then
			rm -f "${LIVE_ROOT}"/source.tar.gz
		fi

		# Create tarball
		cd "${LIVE_ROOT}" &&
		tar cfz source.tar.gz source

		# Creating stage file
		Create_stagefile "${LIVE_ROOT}"/.stage/source_net
	fi
done
