#!/bin/sh

# lh_source(1) - build source images
# Copyright (C) 2006-2007 Daniel Baumann <daniel@debian.org>
#
# live-helper comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
# This is free software, and you are welcome to redistribute it
# under certain conditions; see COPYING for details.

set -e

# Source common functions
for FUNCTION in /usr/share/live-helper/functions/*.sh
do
	. ${FUNCTION}
done

# Set static variables
DESCRIPTION="build source images"
HELP=""
USAGE="${PROGRAM} [--force]"

Arguments "${@}"

Echo_debug "Init ${PROGRAM}"

# Reading configuration files
Read_conffile config/bootstrap
Read_conffile config/chroot
Read_conffile config/common
Read_conffile config/image
Set_defaults

Breakpoint "source: Init"

# Enabling network in chroot
lh_chroot_hosts install "${@}"
lh_chroot_resolv install "${@}"
lh_chroot_sources install "${@}"

# Preparing images
lh_source_config "${@}"
lh_source_download "${@}"
lh_source_md5sum "${@}"

# Building images
lh_source_generic "${@}"
lh_source_hdd "${@}"
lh_source_iso "${@}"
lh_source_net "${@}"
lh_source_usb "${@}"

# Deconfiguring chroot
rm -f .stage/chroot_sources
lh_chroot_resolv remove "${@}"
lh_chroot_hosts remove "${@}"
