#!/bin/sh

# lh_source_hdd(1) - build source harddisk image

set -e

# Source common functions
for FUNCTION in /usr/share/live-helper/functions/*.sh
do
	. ${FUNCTION}
done

# Reading configuration files
Read_conffile config/common
Read_conffile config/image
Set_defaults

if [ "${LIVE_SOURCE}" = "disabled" ]
then
	exit 0
fi

for IMAGE in ${LIVE_SOURCE_IMAGE}
do
	if [ "${IMAGE}" = "hdd" ]
	then
		# Requiring stage file
		Require_stagefile .stage/source_download

		# Checking lock file
		Check_lockfile .lock

		# Creating lock file
		Create_lockfile .lock

		# Checking stage file
		Check_stagefile .stage/source_hdd

		# Remove old source
		if [ -f source-hdd.tar.gz ]
		then
			rm -f source-hdd.tar.gz
		fi

		# Create tarball
		tar cfz source-hdd.tar.gz source

		# Creating stage file
		Create_stagefile .stage/source_hdd
	fi
done
