#!/bin/sh

# lh_source_config(1) - copy debian-live config into source
# Copyright (C) 2006-2007 Daniel Baumann <daniel@debian.org>
#
# live-helper comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
# This is free software, and you are welcome to redistribute it
# under certain conditions; see COPYING for details.

set -e

# Source common functions
for FUNCTION in /usr/share/live-helper/functions/*.sh
do
	. ${FUNCTION}
done

# Set static variables
DESCRIPTION="copy debian-live config into source"
HELP=""
USAGE="${PROGRAM} [--force]"

Arguments "${@}"

Echo_debug "Init ${PROGRAM}"

# Reading configuration files
Read_conffile config/bootstrap
Read_conffile config/chroot
Read_conffile config/common
Read_conffile config/image
Set_defaults

Breakpoint "source_config: Init"

if [ "${LIVE_SOURCE}" = "enabled" ]
then
	# Requiring stage file
	Require_stagefile .stage/bootstrap

	# Checking lock file
	Check_lockfile .lock

	# Creating lock file
	Create_lockfile .lock

	# Checking stage file
	Check_stagefile .stage/source_config

	# Remove old sources
	if [ -d source/debian-live ]
	then
		rm -rf source/debian-live
	fi

	# Copy system configuration
	mkdir -p source/debian-live
	cp -a config source/debian-live

	# Create tarball
	cd source
	tar cfz debian-live-config_`date +%Y%m%d.%s`.tar.gz debian-live
	cd "${OLDPWD}"

	rm -rf source/debian-live/config
	mv source/debian-live-config_*.tar.gz source/debian-live

	# Creating stage file
	Create_stagefile .stage/source_config
fi
