#!/bin/sh

# lh_source_tar(1) - build source tarball
# Copyright (C) 2006-2009 Daniel Baumann <daniel@debian.org>
#
# live-helper comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
# This is free software, and you are welcome to redistribute it
# under certain conditions; see COPYING for details.

set -e

# Including common functions
. "${LH_BASE:-/usr/share/live-helper}"/live-helper.sh

# Setting static variables
DESCRIPTION="$(Echo 'build source tarball')"
HELP=""
USAGE="${PROGRAM} [--force]"

Arguments "${@}"

# Reading configuration files
Read_conffiles config/all config/common config/bootstrap config/chroot config/binary config/source
Set_defaults

if [ "${LH_SOURCE}" != "enabled" ]
then
	exit 0
fi

if ! In_list tar "${LH_SOURCE_IMAGES}"
then
	exit 0
fi

Echo_message "Begin building source tarball..."
Echo_message "This may take a while."

# Requiring stage file
Require_stagefile .stage/config .stage/source_debian

# Checking stage file
Check_stagefile .stage/source_tar

# Checking lock file
Check_lockfile .lock

# Creating lock file
Create_lockfile .lock

# Remove old source
if [ -f source.tar.gz ]
then
	rm -f source.tar.gz
fi

# Create tarball
tar cf source.tar source
gzip ${GZIP_OPTIONS} source.tar

# Creating stage file
Create_stagefile .stage/source_tar
