#!/bin/sh

# lh_source_download(1) - download sources
# Copyright (C) 2006-2007 Daniel Baumann <daniel@debian.org>
#
# live-helper comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
# This is free software, and you are welcome to redistribute it
# under certain conditions; see COPYING for details.

set -e

# Source common functions
for FUNCTION in /usr/share/live-helper/functions/*.sh
do
	. ${FUNCTION}
done

# Set static variables
DESCRIPTION="download sources"
HELP=""
USAGE="${PROGRAM} [--force]"

Arguments "${@}"

Echo_debug "Init ${PROGRAM}"

# Reading configuration files
Read_conffile config/bootstrap
Read_conffile config/chroot
Read_conffile config/common
Read_conffile config/image
Set_defaults

Breakpoint "source_download: Init"

if [ "${LIVE_SOURCE}" = "enabled" ]
then
	# Requiring stage file
	Require_stagefile .stage/bootstrap

	# Checking lock file
	Check_lockfile .lock

	# Creating lock file
	Create_lockfile .lock

	# Checking stage file
	Check_stagefile .stage/source_download

	# Remove old sources
	if [ -d source/debian ]
	then
		rm -rf source/debian
	fi

	# Download sources
	Chroot "dpkg --get-selections" | awk '{ print $1 }' > chroot/root/dpkg-selection.txt
	#echo "live-helper" >> chroot/root/dpkg-selection.txt
	Chroot "xargs --arg-file=/root/dpkg-selection.txt apt-get source --download-only"
	rm -f chroot/root/dpkg-selection.txt

	# Sort sources
	for DSC in chroot/*.dsc
	do
		SOURCE="`awk '/Source:/ { print $2; }' ${DSC}`"

		if [ "`echo ${SOURCE} | cut -b 1-3`" == "lib" ]
		then
			LETTER="`echo ${SOURCE} | cut -b 1-4`"
		else
			LETTER="`echo ${SOURCE} | cut -b 1`"
		fi

		# Install directory
		install -d -m 0755 source/debian/"${LETTER}"/"${SOURCE}"

		# Move files
		mv chroot/"${SOURCE}"_* source/debian/"${LETTER}"/"${SOURCE}"
	done

	# Creating stage file
	Create_stagefile .stage/source_download
fi
