#!/bin/sh

# lh_source_net(1) - build source net image
# Copyright (C) 2006-2008 Daniel Baumann <daniel@debian.org>
#
# live-helper comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
# This is free software, and you are welcome to redistribute it
# under certain conditions; see COPYING for details.

set -e

# Including common functions
LH_BASE="${LH_BASE:-/usr/share/live-helper}"

for FUNCTION in "${LH_BASE}"/functions/*.sh
do
	. "${FUNCTION}"
done

# Setting static variables
DESCRIPTION="build source net image"
HELP=""
USAGE="${PROGRAM} [--force]"

Arguments "${@}"

# Reading configuration files
Read_conffile config/common
Read_conffile config/bootstrap
Read_conffile config/chroot
Read_conffile config/binary
Read_conffile config/source
Read_conffile "${LH_CONFIG}"
Set_defaults

if [ "${LH_SOURCE}" != "enabled" ]
then
	exit 0
fi

if ! echo "${LH_SOURCE_IMAGES}" | grep -qs net
then
        exit 0
fi

Echo_message "Begin building source netboot image..."

# Requiring stage file
Require_stagefile .stage/source_debian

# Checking stage file
Check_stagefile .stage/source_net

# Checking lock file
Check_lockfile .lock

# Creating lock file
Create_lockfile .lock

# Remove old source
if [ -f source-net.tar.gz ]
then
	rm -f source-net.tar.gz
fi

# Create tarball
tar cfz source-net.tar.gz source

# Creating stage file
Create_stagefile .stage/source_net
