#!/bin/sh

# live-helper(7) - the Debian Live tool suite
# Copyright (C) 2006-2009 Daniel Baumann <daniel@debian.org>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
# On Debian systems, the complete text of the GNU General Public License
# can be found in /usr/share/common-licenses/GPL-3 file.

set -e

# Including common functions
. "${LH_BASE:-/usr/share/live-helper}"/live-helper.sh

if [ -x "$(which man 2>/dev/null)" ]
then
	man live-helper
	exit 0
else
	Echo "live-helper is a set of scripts to build Debian Live system images."
	echo
	Echo "The idea behind live-helper is a framework that uses a configuration directory to completely automate and customize all aspects of building a Live image."
	echo
	Echo "An introduction to live-helper can be found in the live-helper(7) manpage."
	exit 0
fi
