#!/bin/sh

# make-live(1) - utility to build Debian Live systems
# Copyright (C) 2006-2007 Daniel Baumann <daniel@debian.org>
#
# live-helper comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
# This is free software, and you are welcome to redistribute it
# under certain conditions; see COPYING for details.

set -e

echo "make-live is obsolete."
echo "Use lh_config and lh_build instead."

exit 1
