                  0fBenvingut a Debian GNU/Linux!07                               09F107

Aix• ‚s un Debian {$LB_DISTRIBUTION} combinat live i d'instalúlaci¢ dins un {$LB_MEDIA}.
Fet el {$LB_DATE}.

0fMEN£ DE LES AJUDES07

0fTECLA    TEMA07

<09F107>   Aquesta p…gina, l'¡ndex.
<09F207>   Prerequisits per instalúlar Debian.
<09F307>   MŠtodes d'arrencada per a usos especials d'aquest {$LB_MEDIA}.
<09F407>   MŠtodes addicionals d'arrencada; mode de rescat.
<09F507>   Rep…s dels par…metres especials d'arrencada.
<09F607>   Par…metres especials per algunes m…quines.
<09F707>   Par…metres especials per certes controladores de discs.
<09F807>   Par…metres especials pel sistema d'instalúlaci¢.
<09F907>   Com obtenir ajuda.
<09F1007>  Copyrights i garanties.

Per a F1-F9 premeu control amb F i llavors el nombre 1-9
Per a F10 premeu control amb F i llavors el nombre 0



Premeu F2 a F10 per m‚s detalls, o INTRO per fer el 