0fPREREQUISITS PER A USAR DEBIAN07                                                09F207

Heu de tenir un m¡nim de 64MB de RAM per usar aquest sistema Debian Live.

Vegeu el Manual Live o el PUF (FAQ) per a m‚s informarci¢; tot dos disponibles
a la web de Debian Live, 0fhttp://live.debian.net/07


Heu de tenir al manco 32 megabytes de RAM per a usar el instalúlador de Debian.

Heu de tenir espai en el disc dur per a crear una nova partici¢ de disc
de al manco 256 megabytes per a instalúlar el sistema base. Necessitar… m‚s
espai de disc per a instalúlar paquets addicionals, depenent de quŠ desitgi fer
amb el seu sistema Debian.

Vegeu el manual d'instalúlaci¢ o les PUF per a m‚s informaci¢; tot dos documents
estan a la seva disposici¢ a la web de Debian, 0fhttp://www.debian.org/07

Gr…cies per seleccionar Debian!




Preneu F1control i F i llavors 1 per veure  el men£ d'ajuda, o ENTER per a 