0fMODE DE RESCAT07                                                                09F407

0fTriau un d'aquests mŠtodes d'arrencada per recuperar una instalúlaci¢ existent07

0frescue07
  Inicia en el mode de rescat.

0fmemtest07
  Inicia el test de mem•ria per escanejar la RAM cercant errors.
0ffloppy07, 0fdisk107 o 0fdisk207
  Inicia des de el disquet, primer o segon disc dur.



Per usar un d'aquests mŠtodes d'arrencada, escriviu-lo a l'indicador d'ordres, 
seguit opcionalment dels par…metres que convinguin. Per exemple:

  boot: rescue acpi=off





Preneu F1control i F, i llavors 1 per veure el men£ d'ajuda, o ENTER per a 