0fOBTENCI¢ D'AJUDA07                                                              09F907

Si no podeu intalúlar aquest Debian, no desespereu! L'equip de Debian
est… preparat per ajudar-vos! Ens interesa especialment trobar problemes de
instalaci¢, perquŠ generalment no afecten nom‚s a 0funa07 persona.
O b‚ ja haurem sentit a parlar del vostre problema i us podrem oferir una 
r…pida soluci¢, o b‚ ens plaur… que ens l'expliqui i provar d'esmenar-lo
plegats, i aix¡ el proper usuari que tingui el mateix problema podr…
beneficiar-se de la vostra experiŠncia!

Vegeu el manual de instalúlaci¢ o les PMF (FAQ) per a m‚s informaci¢; 
Aquests documents estan disponibles al lloc web de Debian:
0fhttp://www.debian.org/07

Si no pot executar el sistema Debian Live, vegeu el manual de instalúlaci¢
o les PMF (FAQ) per a m‚s informaci¢. Aquests documents estan disponibles
en la web de Debian, 0fhttp://live.debian.net/07






Premeu F1control i F seguit de 1 per el men£ d'ajuda, o INTRO per fer el 