.TH LH 1 "2008\-08\-11" "1.0" "live\-helper"

.SH NAME
live\-helper \- generic live\-helper wrapper

.SH SYNOPSIS
\fBlh\fR COMMAND [COMMAND_OPTIONS] [\fIlive\-helper options\fR]

.SH DESCRIPTION
lh is a generic wrapper for live\-helper programs. Instead of calling
"lh_command", it can also called through lh as "lh command", where command is a
name of a live\-helper program. See the man page of live\-helper for a list of
all available programs and the man page of lh_command for the documentation of
the actual helper.

.SH SEE ALSO
\fIlive\-helper\fR(7)
.PP
This program is part of live\-helper.

.SH BUGS
Report bugs against live\-helper
<\fIhttp://packages.qa.debian.org/live\-helper\fR>.

.SH HOMEPAGE
More information about the Debian Live project can be found at
<\fIhttp://debian\-live.alioth.debian.org/\fR> and
<\fIhttp://wiki.debian.org/DebianLive/\fR>.

.SH AUTHOR
live\-helper was written by Daniel Baumann <\fIdaniel@debian.org\fR> for the
Debian project.
