.TH LH_BUILD 1 "2007\-10\-15" "1.0~a32" "live\-helper"

.SH NAME
lh_build \- building a live system

.SH SYNOPSIS
.B lh_build [\fIlive\-helper\ options\fR\|]

.SH DESCRIPTION
lh_build is a helper script. It calls all required meta\-helper scripts to successfully build a live system.

.SH META\-HELPERS
Here is the complete list of available meta\-helper commands. See their man pages for additional documentation.
.IP "\fIlh_binary\fR(1)" 4
builds a binary image.
.IP "\fIlh_bootstrap\fR(1)" 4
bootstraps a system.
.IP "\fIlh_chroot\fR(1)" 4
customizes a chroot.
.IP "\fIlh_source\fR(1)" 4
builds a source image.

.SH SEE ALSO
\fIlive\-helper\fR(7)
.PP
This program is a part of live\-helper.

.SH BUGS
Report bugs against live\-helper <\fIhttp://packages.qa.debian.org/live\-helper\fR>.

.SH HOMEPAGE
More information about the Debian Live project can be found at <\fIhttp://debian\-live.alioth.debian.org/\fR> and <\fIhttp://wiki.debian.org/DebianLive/\fR>.

.SH AUTHOR
live\-helper was written by Daniel Baumann <\fIdaniel@debian.org\fR> for the Debian project.
