.TH LH_BOOTSTRAP_CDEBOOTSTRAP 1 "2007\-11\-05" "1.0~a35" "live\-helper"

.SH NAME
lh_bootstrap_cdebootstrap \- bootstrap a Debian system with \fIcdebootstrap\fR(1)

.SH SYNOPSIS
.B lh_bootstrap_cdebootstrap [\fIlive\-helper\ options\fR\|]

.SH DESCRIPTION
lh_bootstrap_cdebootstrap uses \fIcdebootstrap\fR(1) to create a Debian base system from scratch.

.SH CONFIGURATION FILE
lh_bootstrap_cdebootstrap reads config/common and config/bootstrap if available. See ENVIRONMENT for the correct environment variables to use.

.SH ENVIRONMENT
lh_bootstrap_cdebootstrap respects the following environment variables if available, otherwise uses default values for it.
.IP "\fI$LH_BOOTSTRAP\fR" 4
control the bootstrap program to be used (Default: cdebootstrap)
.IP "\fI$LH_CACHE\fR" 4
control if downloaded packages should be cached (Default: enabled)
.PP
.IP "\fI$LH_ARCHITECTURE\fR" 4
select the chroot architecture (Default: autodetected)
.IP "\fI$LH_BOOTSTRAP_CONFIG\fR" 4
set distribution config directory (Default: empty)
.IP "\fI$LH_BOOTSTRAP_FLAVOUR\fR" 4
select the flavour to use (Default: standard)
.IP "\fI$LH_DISTRIBUTION\fR" 4
select the distribution to use (Default: sid)
.IP "\fI$LH_MIRROR_BUILD\fR" 4
set the mirror to use (Default: http://ftp.debian.org/debian/)

.SH SEE ALSO
\fIcdebootstrap\fR(1)
.PP
\fIlive\-helper\fR(7)
.PP
This program is a part of live\-helper.

.SH BUGS
Report bugs against live\-helper <\fIhttp://packages.qa.debian.org/live\-helper\fR>.

.SH HOMEPAGE
More information about the Debian Live project can be found at <\fIhttp://debian\-live.alioth.debian.org/\fR> and <\fIhttp://wiki.debian.org/DebianLive/\fR>.

.SH AUTHOR
live\-helper was written by Daniel Baumann <\fIdaniel@debian.org\fR> for the Debian project.
