.TH LH_BOOTSTRAP 1 "2007\-11\-26" "1.0~a38" "live\-helper"

.SH NAME
lh_bootstrap \- meta\-helper for lh_bootstrap_*

.SH SYNOPSIS
\fBlh_bootstrap\fR [\fIlive\-helper options\fR]

.SH DESCRIPTION
lh_bootstrap is a meta\-helper. It calls all necessary live\-helper programs in
the correct order to complete the bootstrap stage.

.SH SEE ALSO
\fIlive\-helper\fR(7)
.PP
This program is part of live\-helper.

.SH BUGS
Report bugs against live\-helper
<\fIhttp://packages.qa.debian.org/live\-helper\fR>.

.SH HOMEPAGE
More information about the Debian Live project can be found at
<\fIhttp://debian\-live.alioth.debian.org/\fR> and
<\fIhttp://wiki.debian.org/DebianLive/\fR>.

.SH AUTHOR
live\-helper was written by Daniel Baumann <\fIdaniel@debian.org\fR> for the
Debian project.
