.TH LH_BUILD 1 "2007\-11\-26" "1.0~a38" "live\-helper"

.SH NAME
lh_build \- meta\-helper for lh_bootstrap, lh_chroot, lh_binary, and lh_source

.SH SYNOPSIS
\fBlh_build\fR [\fIlive\-helper options\fR]

.SH DESCRIPTION
lh_build is a meta\-helper. It calls all necessary live\-helper programs in the
correct order to complete the bootstrap, chroot, binary, and source stage.

.SH SEE ALSO
\fIlive\-helper\fR(7)
.PP
This program is part of live\-helper.

.SH BUGS
Report bugs against live\-helper
<\fIhttp://packages.qa.debian.org/live\-helper\fR>.

.SH HOMEPAGE
More information about the Debian Live project can be found at
<\fIhttp://debian\-live.alioth.debian.org/\fR> and
<\fIhttp://wiki.debian.org/DebianLive/\fR>.

.SH AUTHOR
live\-helper was written by Daniel Baumann <\fIdaniel@debian.org\fR> for the
Debian project.
