.TH LH_CHROOT_COPY 1 "2009\-02\-14" "1.0.4" "live\-helper"

.SH NAME
lh_chroot_packages \- queue install of packages into chroot

.SH SYNOPSIS
\fBlh_chroot_packages\fR [\fIlive\-helper options\fR]

.SH DESCRIPTION
lh_chroot_packages is a low\-level command (plumbing) of live\-helper, the Debian Live tool suite. It queues installation of packages into chroot.

.SH OPTIONS
lh_chroot_packages has no specific options but understands all generic live\-helper options. See \fIlive\-helper\fR(7) for a complete list of all generic live\-helper options.

.SH SEE ALSO
\fIlh_chroot\fR(1)
.br
\fIlive\-helper\fR(7)
.PP
This program is a part of live\-helper.

.SH HOMEPAGE
More information about live\-helper and the Debian Live project can be found in the homepage at <\fIhttp://debian\-live.alioth.debian.org/\fR> and in the manual at <\fIhttp://live.debian.net/manual/\fR>.

.SH BUGS
Report bugs by submitting a bugreport for the live\-helper package in the Debian Bug Tracking System at <\fIhttp://bugs.debian.org/\fR> or write a mail to the mailinglist at <\fIdebian-live@lists.debian.org\fR>.

.SH AUTHOR
live\-helper was written by Daniel Baumann <\fIdaniel@debian.org\fR> for the Debian project.
