.TH LH_CLEAN 1 "2007\-03\-19" "1.0~a2" "live\-helper"

.SH NAME
lh_clean \- clean up system build directories

.SH SYNOPSIS
.B lh_clean [\fIlive\-helper\ options\fR\|]

.SH DESCRIPTION
lh_clean is a live\-helper program that is responsible for cleaning up after a system is built. It removes the system build directories, and removes some other files including stage files, and any detritus left behind by other live\-helper commands.

.SH OPTIONS
lh_clean has no options (FIXME).

.SH SEE ALSO
\fIlive\-helper\fR(7)
.PP
This program is a part of live-helper.

.SH BUGS
Report bugs against live\-helper <\fIhttp://packages.qa.debian.org/live\-helper/\fR>.

.SH HOMEPAGE
More information about the Debian Live project can be found at <\fIhttp://debian\-live.alioth.debian.org/\fR> and <\fIhttp://wiki.debian.org/DebianLive/\fR>.

.SH AUTHOR
live\-helper was written by Daniel Baumann <\fIdaniel@debian.org\fR> and Marco Amadori <\fImarco.amadori@gmail.com\fR>, for the Debian project.
