.TH LH_SOURCE 1 "2007\-11\-19" "1.0~a37" "live\-helper"

.SH NAME
lh_source \- meta\-helper for lh_source_*

.SH SYNOPSIS
\fBlh_source\fR [\fIlive\-helper options\fR]

.SH DESCRIPTION
lh_source is a meta\-helper. It calls all necessary live\-helper programs in the
correct order to complete the source stage.

.SH SEE ALSO
\fIlive\-helper\fR(7)
.PP
This program is part of live\-helper.

.SH BUGS
Report bugs against live\-helper
<\fIhttp://packages.qa.debian.org/live\-helper\fR>.

.SH HOMEPAGE
More information about the Debian Live project can be found at
<\fIhttp://debian\-live.alioth.debian.org/\fR> and
<\fIhttp://wiki.debian.org/DebianLive/\fR>.

.SH AUTHOR
live\-helper was written by Daniel Baumann <\fIdaniel@debian.org\fR> for the
Debian project.
