.TH LIVE\-HELPER 7 "2007\-06\-04" "1.0~a13" "live\-helper"

.SH NAME
live\-helper \- Debian Live helper programs

.SH SYNOPSIS
.B lh_* [\fIlive\-helper\ options\fR\|]

.SH DESCRIPTION
Live\-helper is a collection of programs that can be used to build Debian Live system images. The philosophy behind live\-helper is to provide a collection of small, simple, and easily understood tools that can be used in your own program to automate building of a Live system.
.PP
A typical program that uses live\-helper will call several live\-helper commands in sequence. Live\-helper commands are all named with a "lh_" prefix. Examples of such a program that uses live\-helper is \fImake\-live\fR(1).

.\" .SH CONFIGURATION FILE
.\" live\-helper reads debian\-live/config/live\-helper if available. See ENVIRONMENT for the correct environment variables to use.

.\" .SH ENVIRONMENT
.\" Every live\-helper command respects the following environment variables if available.
.\" .IP "\fI$LH_DEBUG\fR" 4
.\" enables debug (Default: false)
.\" .IP "\fI$LH_QUIET\fR" 4
.\" be quiet (Default: false)
.\" .IP "\fI$LH_VERBOSE\fR" 4
.\" be verbose (Default: false)

.SH LIVE\-HELPER COMMANDS
Here is the complete list of available live\-helper commands. See their man pages for additional documentation.
.IP "\fIlh_binary\fR(1)" 4
meta\-helper for lh_binary_*.
.IP "\fIlh_binary_chroot\fR(1)" 4
copies chroot into chroot.
.IP "\fIlh_binary_debian\-installer\fR(1)" 4
copies debian-installer into the binary image.
.IP "\fIlh_binary_encryption\fR(1)" 4
encrypts the root filesystem.
.IP "\fIlh_binary_grub\fR(1)" 4
copies grub into the binary image.
.IP "\fIlh_binary_hdd\fR(1)" 4
creates the harddisk binary tarball.
.IP "\fIlh_binary_includes\fR(1)" 4
copies files into the binary image.
.IP "\fIlh_binary_iso\fR(1)" 4
creates the CD/DVD binary image.
.IP "\fIlh_binary_linux-image\fR(1)" 4
copies linux\-image into the binary image.
.IP "\fIlh_binary_local-includes\fR(1)" 4
copies local files into the binary image.
.IP "\fIlh_binary_manifest\fR(1)" 4
creates the package list of the root filesystem.
.IP "\fIlh_binary_md5sum\fR(1)" 4
creates md5sum.txt in the binary image.
.IP "\fIlh_binary_memtest\fR(1)" 4
copies a memtest into the binary image.
.IP "\fIlh_binary_net\fR(1)" 4
creates the netboot binary tarball.
.IP "\fIlh_binary_rootfs\fR(1)" 4
creates the root filesystem.
.IP "\fIlh_binary_syslinux\fR(1)" 4
copies syslinux into the binary image.
.IP "\fIlh_binary_usb-hdd\fR(1)" 4
creates the USB-hdd binary image.
.IP "\fIlh_binary_yaboot\fR(1)" 4
copies yaboot into the binary image.
.IP "\fIlh_bootstrap\fR(1)" 4
meta\-helper for lh_bootstrap_*.
.IP "\fIlh_bootstrap_cdebootstrap\fR(1)" 4
bootstraps system with cdebootstrap.
.IP "\fIlh_bootstrap_debootstrap\fR(1)" 4
bootstraps system with debootstrap.
.IP "\fIlh_build\fR(1)" 4
meta\-helper for lh_bootstrap, lh_chroot, lh_binary and lh_source.
.IP "\fIlh_chroot\fR(1)" 4
meta\-helper for lh_chroot_*.
.IP "\fIlh_chroot_apt\fR(1)" 4
configures /etc/apt/apt.conf in chroot.
.IP "\fIlh_chroot_debianchroot\fR(1)" 4
configures /etc/debian_chroot in chroot.
.IP "\fIlh_chroot_hacks\fR(1)" 4
does evil (temporary) hacks in the chroot.
.IP "\fIlh_chroot_hooks\fR(1)" 4
executes additional commands in the chroot.
.IP "\fIlh_chroot_hosts\fR(1)" 4
configures /etc/hosts in the chroot.
.IP "\fIlh_chroot_interactive\fR(1)" 4
makes build interactive.
.IP "\fIlh_chroot_linux-image\fR(1)" 4
configures /etc/kernel\-img.conf in the chroot.
.IP "\fIlh_chroot_local-hooks\fR(1)" 4
executes additional local commands in the chroot.
.IP "\fIlh_chroot_local-includes\fR(1)" 4
copies local files into the binary image.
.IP "\fIlh_chroot_localization\fR(1)" 4
installs localization packages in the chroot.
.IP "\fIlh_chroot_local-packages\fR(1)" 4
installs local packages in the chroot.
.IP "\fIlh_chroot_local-packageslists\fR(1)" 4
installs local packages lists in the chroot.
.IP "\fIlh_chroot_packages\fR(1)" 4
installs packages in the chroot.
.IP "\fIlh_chroot_packageslists\fR(1)" 4
installs packages lists in the chroot.
.IP "\fIlh_chroot_proc\fR(1)" 4
mounts /proc in the chroot.
.IP "\fIlh_chroot_resolv\fR(1)" 4
configures /etc/resolf.conf in the chroot.
.IP "\fIlh_chroot_sources\fR(1)" 4
configures /etc/apt/sources.list in the chroot.
.IP "\fIlh_chroot_symlinks\fR(1)" 4
converts symlinks in the chroot.
.IP "\fIlh_chroot_sysfs\fR(1)" 4
mounts /sys in the chroot.
.IP "\fIlh_chroot_sysvinit\fR(1)" 4
minimizes daemon startup in the chroot.
.IP "\fIlh_chroot_sysvrc\fR(1)" 4
installs policy\-id hack in the chroot.
.IP "\fIlh_chroot_tasks\fR(1)" 4
installs packages tasks in the chroot.
.IP "\fIlh_clean\fR(1)" 4
cleans up build directory.
.IP "\fIlh_config\fR(1)" 4
creates sample configuration.
.IP "\fIlh_losetup\fR(1)" 4
manages loop device handling
.IP "\fIlh_source\fR(1)" 4
meta\-helper for lh_source_*.
.IP "\fIlh_source_debian-live\fR(1)" 4
copies config into source directory.
.IP "\fIlh_source_debian\fR(1)" 4
downloads source packages.
.IP "\fIlh_source_generic\fR(1)" 4
creates generic source tarball.
.IP "\fIlh_source_hdd\fR(1)" 4
creates harddisk source tarball.
.IP "\fIlh_source_iso\fR(1)" 4
creates CD/DVD source image.
.IP "\fIlh_source_net\fR(1)" 4
creates netboot source tarball.
.IP "\fIlh_source_usb-hdd\fR(1)" 4
creates USB-hdd source image.
.IP "\fIlh_testroot\fR(1)" 4
checks for root privileges.

.SH LIVE\-HELPER OPTIONS
The following command line options are supported by all live\-helper programs.
.IP "\fB\-\-breakpoints\fR" 4
run with breakpoints
.IP "\fB\-\-conffile\fR" 4
use custom configuration file
.IP "\fB\-\-debug\fR" 4
show debug information
.IP "\fB\-\-force\fR" 4
force helper execution, even if stage file exists.
.IP "\fB\-h, \-\-help\fR" 4
display help and exit
.IP "\fB\-\-logfile\fR" 4
use custom log file
.IP "\fB\-\-quiet\fR" 4
be quiet
.IP "\fB\-u, \-\-usage\fR" 4
show usage and exit
.IP "\fB\-\-verbose\fR" 4
be verbose
.IP "\fB\-v, \-\-version\fR" 4
output version information and exit

.SH SEE ALSO
\fIlive\-initramfs\fR(7)
.PP
\fIlive\-sysvinit\fR(7)
.PP
\fIlive\-webhelper\fR(7)

.SH BUGS
Report bugs against live\-helper <\fIhttp://packages.qa.debian.org/live\-helper/\fR>.

.SH HOMEPAGE
More information about the Debian Live project can be found at <\fIhttp://debian\-live.alioth.debian.org/\fR> and <\fIhttp://wiki.debian.org/DebianLive/\fR>.

.SH AUTHOR
live\-helper was written by Daniel Baumann <\fIdaniel@debian.org\fR> for the Debian project.
