.TH MAKE-LIVE.CONF 8 "Jul, 17 2006 "0.99" "make-live configuration"

.SH NAME
make-live.conf \- make-live configuration file.

.SH DESCRIPTION
The Debian Live framework lets you automagically create live system images.
.PP

.SH ENVIRONMENT
Note that environment variables are overwritten, if they are set in the
configuration file at /etc/make-live.conf.
.TP
.B LIVE_ARCHITECTURE
specifies the build root (Default: `pwd`/live).
.TP
.B LIVE_BOOTAPPEND
specifies additional bootparameters to the kernel (Default: none).
.TP
.B LIVE_CONFFILE
specifies alternative configuration file.
.TP
.B LIVE_CLONE
.TP
.B LIVE_DISTRIBUTION
specifies which distribution will be used (Default: unstable).
.TP
.B LIVE_DEBUG
enables debug output.
.TP
.B LIVE_FILESYSTEM
specifies the filesystem to be used for the root filesystem image
(Default: squashfs).
.TP
.B LIVE_FLAVOUR
specifies the bootstrap flavour, either standard (default) or minimal.
.TP
.B LIVE_FTPPROXY
specifies your ftp_proxy you want to use inside the chroot (Default: none).
.TP
.B LIVE_HOOK
specifies a command to be executed inside the chroot before mastering the
image (Default: none).
.TP
.B LIVE_HTTPPROXY
specifies your http_proxy you want to use inside the chroot (Default: none).
.TP
.B LIVE_INCLUDE_IMAGE
specifies a file or directory which should be copied into the image
(Default: none).
.TP
.B LIVE_INCLUDE_ROOTFS
specifies a file or directory which should be copied into the to root filesystem
(Default: none).
.TP
.B LIVE_LINUX_FLAVOUR
specifies the linux-image flavour.
.TP
.B LIVE_LOGFILE
specifies the location of the logfile (Default: $LIVE_ROOT/make-live.log).
.TP
.B LIVE_MIRROR
specifies the used Debian mirror (Default: http://ftp.debian.org/debian).
.TP
.B LIVE_MIRROR_KEY
specifies the public key of the used Debian mirror (Default: none).
.TP
.B LIVE_PACKAGE_LIST
specifies a file which contains a list of packages to install, separated by
newlines, if LIVE_PACKAGE_LIST exists, default LIST option will be ignored.
.TP
.B LIVE_PACKAGES
specifies additional packages to install (Default: none).
.TP
.B LIVE_PRESEED
specifies a preseed file useful for configuring packages
(Default: none).
.TP
.B LIVE_REPOSITORY
specifies another repository used (Default: none).
.TP
.B LIVE_REPOSITORY_KEY
speficies the public key of the other repository (Default: none).
.TP
.B LIVE_SECTIONS
specifies which sections will be available (Default: main).
.TP
.B LIVE_SERVER_ADDRESS
specifies the IP address or hostname of the netboot server (Default: none).
.TP
.B LIVE_SERVER_PATH
specifies the directory of the chroot on the netboot server (Default: none).
.TP
.B LIVE_SPLASHY
specifies that splashy should be installed and initramfs patched
(Default: no).
.TP
.B LIVE_SPLASHY_THEME
if LIVE_SPLASHY exists this could be used to select a theme as the default 
splashy theme, could also install external .tar.gz splashy themes specified
with file name without extension and in the current directory.
(Default: none).
.TP
.B LIVE_TEMPLATES
specifies a directory to be used for templates instead of the default one.
(Default: "/usr/share/make-live/templates")

.SH BUGS
.B make-live
works fully on amd64 and i386, partially on alpha, hppa, ia64, mips, mipsel,
powerpc, s390 and sparc. Other architectures, such as arm and m68k, as well as
non-linux ports of Debian, like hurd-i386, are currently not supported.

.SH HOMEPAGE
Debian Live project <http://live.debian.net/>

.SH AUTHOR
make-live was written by Daniel Baumann <daniel@debian.org> and Marco Amadori
<marco.amadori@gmail.com>.
