Welcome to Debian GNU/Linux

This is an Debian Live CDROM,
built on LIVE_DATE.

The default option is 'live'.

If the system fails to boot at all (the typical
symptom is a white screen which doesn't go away),
use 'live video=ofonly'.

Press the tab key for a list of options, or type
'help' for help.

************************************
If in doubt, just press Enter, and if that
doesn't work, type 'live video=ofonly'.
************************************
