0fPRÉ-REQUISITOS PARA USAR O DEBIAN07                                                09F207

Você deve possuir pelo menos 64 megabytes de memória física (RAM) para rodar
este sistema Debian Live.

Veja o Manual do Debian Live ou as Perguntas Mais Frequentes (FAQ) para mais
informações; ambos os documentos estão disponíveis no sítio web do Debian Live,
0fhttp://live.debian.net/07


Você deve possuir no mínimo 44 megabytes de memória física (RAM) para usar o
Debian Installer.

Você deve possuir espaço no seu disco rígido para criar uma nova partição de no
mínimo 500 megabytes para instalar o sistema básico. Você necessitará mais
espaço para instalar pacotes adicionais, dependendo do que você queira fazer
com o seu novo sistema Debian.

Veja o Guia de Instalação ou as Perguntas Mais Frequentes (FAQ) para mais
informações. Ambos os documentos estão disponíveis no sítio web do Debian,
0fhttp://www.debian.org/07

Obrigado por escolher o Debian!




Pressione F1control e F seguido de 1 para o índice de ajuda, ou ENTER para 
