0fPARÂMETROS ESPECIAIS DE INICIALIZAÇÃO - SISTEMA DE INSTALAÇÃO07                                 09F807

Você pode utilizar os seguintes parâmetros de inicialização no prompt
0fboot:07, em combinação com o método de inicialização (veja <09F307>).
Estes parâmetros controlam o funcionamento do instalador.

0f
RESULTADO                               PARÂMETRO07
Nível de depuração                      0fDEBCONF_DEBUG=507
Depuração de sequência de incialização  0fBOOT_DEBUG=2|307
Desabilita framebuffer                  0ffb=false07
Não incializa PCMCIA                    0fhw-detect/start_pcmcia=false07
Força configuração estática de rede     0fnetcfg/disable_dhcp=true07
Seta mapa de teclado                    0fbootkbd=es07
Usa tty Braille                         0fbrltty=driver,device,texttable07
Usa um tema de alto contraste para acessibilidade   0ftheme=dark07
Usa tarefas (tasks) específicas         0ftasks="kde-desktop, standard"07



Por exemplo:
  boot: install fb=false

Pressione F1control e F seguido de 1 para o índice de ajuda, ou ENTER para 
