0fOBTENDO AJUDA07                                                                  09F907

Se você não conseguir instalar o Debian, não se desespere! O time do Debian
está pronto para te ajudar! Nós estamos especialmente interessados em conhecer
os problemas de instalação, porque em geral eles não ocorrem para apenas
0fone07 pessoa.

Ou nós já temos conhecimento sobre seu problema em particular e podemos
oferecer uma solução rápida, ou nós gostaríamos de ouvír sobre ele e trabalhar
nele com você, de forma que o próximo usuário que tiver o mesmo problema seja
beneficiado com esta sua experiência.

Veja o Guia de Instalação ou as Perguntas Mais Frequentes (FAQ) para mais
informações; ambos documentos estão disponíveis no sítio web do Debian,
0fhttp://www.debian.org/07

Se você não consegue rodar o sistema Debian Live, veja o manual ou as Perguntas
Mais Frequentes (FAQ) para mais informações; ambos os documentos estão
disponíveis no sítio web do Debian Live, 0fhttp://live.debian.net/07







Pressione F1control e F seguido de 1 para o índice de ajuda, ou ENTER para 
