#!/bin/sh

set -e

_DIRECTORY="/srv/debian.net/live-manual"

case "${1}" in
	remove)
		if [ -d "${_DIRECTORY}" ]
		then
			rmdir --ignore-fail-on-non-empty "${_DIRECTORY}" || true
		fi
		;;

	purge)
		#rm -rf "${_DIRECTORY}"
		;;

	upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)

		;;

	*)
		echo "postrm called with unknown argument \`${1}'" >&2
		exit 1
		;;
esac

#DEBHELPER#

exit 0
