#!/bin/sh

set -e

case "${1}" in
	remove)
		for FILE in /usr/share/man/man7/casper.7.gz /usr/share/man/man1/casper-snapshot.1.gz
		do
			dpkg-divert --package live-helper --remove --rename --divert ${FILE}.casper ${FILE}
		done
		;;

	purge|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)

		;;

	*)
		echo "postrm called with unknown argument \`${1}'" >&2
		exit 1
		;;
esac

#DEBHELPER#

exit 0
