#!/bin/sh

set -e

case "${1}" in
	configure)
		update-alternatives --install /usr/share/live-helper/templates \
			live-helper_templates \
			/usr/share/live-helper/templates.debian 100

		update-alternatives --install /usr/share/live-helper/includes \
			live-helper_includes \
			/usr/share/live-helper/includes.debian 100
		;;

	abort-upgrade|abort-remove|abort-deconfigure)

		;;

	*)
		echo "postinst called with unknown argument \`${1}'" >&2
		exit 1
		;;
esac

#DEBHELPER#

exit 0
