#!/bin/sh

set -e

case "${1}" in
	remove|upgrade|deconfigure)
		update-alternatives --remove live-helper_includes /usr/share/live-helper/includes.debian
		update-alternatives --remove live-helper_templates /usr/share/live-helper/templates.debian
		;;

	failed-upgrade)

		;;

	*)
		echo "prerm called with unknown argument \`${1}'" >&2
		exit 1
		;;
esac

#DEBHELPER#

exit 0
