#!/bin/sh

# /usr/share/live-helper/hooks/kde-desktop - hook list for live-helper(7)
# Copyright (C) 2006-2007 Daniel Baumann <daniel@debian.org>
#
# live-helper comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
# This is free software, and you are welcome to redistribute it
# under certain conditions; see COPYING for details.

set -e

apt-get remove --purge --yes gdm
update-alternatives --set x-session-manager /usr/bin/startkde
dpkg-reconfigure kdm
