#!/bin/sh

# /usr/share/live-helper/hooks/minimal - hook list for live-helper(7)
# Copyright (C) 2006-2007 Daniel Baumann <daniel@debian.org>
#
# live-helper comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
# This is free software, and you are welcome to redistribute it
# under certain conditions; see COPYING for details.

set -e

# Removing unused packages
for PACKAGE in apt-utils aptitude man-db manpages info ssl wget
do
	if ! apt-get remove --purge --yes "${PACKAGE}"
	then
		echo "WARNING: ${PACKAGE} isn't installed"
	fi
done

apt-get autoremove || true

# Removing unused files
find . -name *~ | xargs rm -f

rm -rf /var/cache/man/*

# Cleaning apt
rm -rf /var/lib/apt/lists
mkdir -p /var/lib/apt/lists/partial

# Truncating logs
for FILE in $(find /var/log/ -type f)
do
	cat < /dev/null > $FILE
done
