#!/bin/sh

# /usr/share/live-helper/hooks/minimal - hook list for live-helper(7)
# Copyright (C) 2006-2008 Daniel Baumann <daniel@debian.org>
#
# live-helper comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
# This is free software, and you are welcome to redistribute it
# under certain conditions; see COPYING for details.

set -e

Purge() {
	PACKAGE="${1}"

	if ! apt-get remove --purge --yes "${PACKAGE}"
	then
		echo "WARNING: ${PACKAGE} isn't installed"
	fi
}

# Removing unused packages
for PACKAGE in aptitude man-db manpages info wget
do
	Purge ${PACKAGE}
done

# Remove apt-utils if we do not require it for lh_chroot_sources
if [ ! -e chroot/root/local-packages/Packages.gz ]
then
	Purge apt-utils
fi

apt-get autoremove --yes || true

# Removing unused files
find . -name *~ -print0 | xargs -0 rm -f

rm -rf /var/cache/man/*

# Cleaning apt lists
rm -rf /var/lib/apt/lists
mkdir -p /var/lib/apt/lists/partial

# Cleaning apt cache
rm -rf /var/cache/apt
mkdir -p /var/cache/apt/archives/partial

# Truncating logs
for FILE in $(find /var/log/ -type f)
do
	: > ${FILE}
done
