#!/bin/sh

# /usr/share/live-helper/hooks/mini - hook list for live-helper(7)
# Copyright (C) 2006-2007 Daniel Baumann <daniel@debian.org>
#
# live-helper comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
# This is free software, and you are welcome to redistribute it
# under certain conditions; see COPYING for details.

set -e

# Removing unused packages
apt-get remove --purge --yes apt-utils aptitude
apt-get remove --purge --yes man-db manpages info
apt-get remove --purge --yes ssl wget

# Removing unused files
find . -name *~ | xargs rm -f

rm -rf /usr/include/*
#rm -rf /usr/share/groff/*
rm -rf /usr/share/doc/*
rm -rf /usr/share/locale/*
rm -rf /usr/share/man/*
rm -rf /usr/share/i18n/*
rm -rf /usr/share/info/*
rm -rf /usr/share/zoneinfo/*
rm -rf /var/cache/man/*

# Cleaning apt
rm -rf /var/lib/apt/lists
mkdir -p /var/lib/apt/lists/partial

# Truncating logs
for FILE in `find /var/log/ -type f`
do
	cat < /dev/null > $FILE
done
