                  0f­Bienvenido a Debian GNU/Linux!07                             09F107

Esto es una Debian {$LB_DISTRIBUTION} combinada live e instalaci¢n de {$LB_MEDIA}.
Fue construida el {$LB_DATE}.

0fMEN£ DE AYUDA07

0fTECLA    TEMA07

<09F107>   Esta p gina, el ¡ndice.
<09F207>   Prerrequisitos para instalar Debian.
<09F307>   M‚todos de arranques especiales usando este {$LB_MEDIA}
<09F407>   M‚todos adicionales de arranque; modo de rescate.
<09F507>   Repaso de los par metros especiales de arranque.
<09F607>   Par metros especiales para algunas m quinas especiales.
<09F707>   Par metros especiales para ciertas controladoras de disco.
<09F807>   Par metros especiales del sistema de instalaci¢n.
<09F907>   C¢mo obtener ayuda.
<09F1007>  Copyrights y garant¡as.

Para las teclas F1-F9 pulse control y F y despu‚s el d¡gito 1-9
Para F10 pulse control y F y el d¡gito 0



Pulse de F2 a F10 para obtener m s detalles, o INTRO para 