0fPRERREQUISITOS PARA USAR DEBIAN07                                               09F207

Debe tener al menos 64 megabytes de RAM para ejecutar este sistema Debian Live.

Lea el manual Live o el FAQ para m s informaci¢n; ambos documentos est n
disponibles en la web de Debian, 0fhttp://live.debian.net/07


Debe tener al menos 32 megabytes de RAM para usar el instalador de Debian.

Debe tener espacio en el disco duro para crear una nueva partici¢n de disco
de al menos 256 megabytes para instalar el sistema base. Necesitar  m s
espacio de disco para instalar paquetes adicionales, dependiendo de que desee
hacer con su sistema Debian.

Lea el manual de instalaci¢n o el FAQ para m s informaci¢n; ambos
documentos est n disponibles en la web de Debian, 0fhttp://www.debian.org/07

­Gracias por elegir Debian!




Pulse F1control y F y entonces 1 para el men£ de ayuda, o INTRO para 