0fM‚TODOS DE ARRANQUE07                                                           09F307

0fM‚todos de arranque disponibles:07

0flive07
  Inicia el sistema live -- ‚ste es el sistema en {$LB_MEDIA} predeterminado.
0flivefailsafe07
  Inicia el sistema live en modo a prueba de fallos.
0finstall07
  Inicia la instalaci¢n.
0fexpert07
  Inicia la instalaci¢n en modo experto, para maximizar el control.

Para usar uno de estos m‚todos, teclee uno en el indicador de ¢rdenes,
seguido opcionalmente por uno de los par metros de arranque. Por ejemplo:
  boot: install acpi=off

Si duda, deber¡a usar el m‚todo predeterminado, sin ning£n par metro 
especial, pulsando simplemente la tecla INTRO en el indicador de ¢rdenes.

Excepto en el modo experto, no se mostrar n los mensajes no cr¡ticos.


Pulse F1control y F, y luego 1 para ver el men£ de ayuda, o INTRO para 
