0fPAR METROS ESPECIALES DE ARRANQUE - SISTEMA DE INSTALACI¢N07                    09F807

Puede usar los siguientes par metros de arranque en el indicador 0fboot:07, 
en combinaci¢n con los m‚todos de arranque (vea <09F307>). Estos
par metros controlan el trabajo del instalador.
0f
RESULTADO                                     PAR METRO07
Depuraci¢n abundante                          0fDEBCONF_DEBUG=507
Depuraci¢n de la secuencia de arranque        0fBOOT_DEBUG=2|307
Desactiva el "framebuffer"                    0ffb=false07
No inicia el sistema PCMCIA                   0fhw-detect/start_pcmcia=false07
Fuerza una configuraci¢n de red est tica      0fnetcfg/disable_dhcp=true07
Escoge el mapa de teclado                     0fbootkbd=es07
Usa tty en braille                            0fbrltty=driver,device,texttable07
Da accesibilidad con tema de alto contraste   0ftheme=dark07
Determina tareas especiales                   0ftasks="kde-desktop, standard"07



Por ejemplo:
  boot: install fb=false


Pulse F1control y F, y entonces 1 para ver el men£ de ayuda, o INTRO para el