0fOBTENCI¢N DE AYUDA07                                                            09F907

Si no puede instalar este Debian, ­no se desespere! ­El equipo de Debian 
est  preparado para ayudarle! Nos interesaa especialmente encontrar problemas
de instalaci¢n, porque en general no ocurren solamente a 0funa07 persona.
O bien ya habremos oido hablar de su problema y le podemos ofrecer una 
r pida soluci¢n, o bien nos gustar  que nos lo explique e intentar arreglarlo
juntos, ­y as¡ el proximo usuario que tenga el mismo problema podr  
beneficiarse de su esperi‚ncia!

Vea el manual de instalaci¢n o las PUF (FAQ) para obtener m s informaci¢n;
estos documentos est n disponibles en la web de Debian:
0fhttp://www.debian.org/07

Si no puede executar el sistema Debian Live, vea el manual de instalaci¢n o
las PUF (FAQ) para m s informaci¢n; estos documentos est n disponibles en 
la web de Debian, 0fhttp://live.debian.net/07






Pulse F1control y F, y entonces 1 para ver el men£ de ayuda, o INTRO para el