.\" live-build(7) - System Build Scripts
.\" Copyright (C) 2006-2014 Daniel Baumann <mail@daniel-baumann.ch>
.\"
.\" This program comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
.\" This is free software, and you are welcome to redistribute it
.\" under certain conditions; see COPYING for details.
.\"
.\"
.TH LIVE\-BUILD 1 2014\-06\-25 4.0~alpha38-1 "Live Systems Project"

.SH NAME
\fBlive\-build\fR \- Live System Build Components

.SH SYNOPSIS
\fBlb binary\-hooks\fR [\-\-verbose]
.PP
\fBlb binary\-hooks\fR [\-\-help]
.br
\fBlb binary\-hooks\fR [\-\-version]
.
.SH DESCRIPTION
live\-build contains the components to build a live system from a configuration directory.
.PP
The \fBlb binary\-hooks\fR command executes hook files after the binary stage.

.SH SPECIFICATION
\fBlb binary\-hooks\fR executes any hook files found in the \fBconfig/hooks\fR directory within the configuration directory.
.PP
Hook files do not require to have a specific owner nor specific permissions. They are marked executable by \fBlb binary\-hooks\fR automatically when they are executed.
.PP
Hook files must either have the suffix \fB*.hook\fR or \fB*.hook.binary\fR.
.PP
Hook files with the suffix \fB*.hook\fR are executed first, hook files with the suffix \fB*.hook.binary\fR are executed second.
.PP
Hook files are executed in alphanumberical order by \fBlb binary\-hooks\fR. If one hook file depends on being run after another, best practise is to use number prefixes (nnnn, starting with 0001) to ensure the order of execution.
.PP
Hook files are copied into the \fBbinary/live-build\fR directory by \fBlb binary\-hooks\fR. They are executed from within the binary directory and can read the configuration directory in \fBlive-build/config\fR within the binary directory.
.PP
\fBWarning:\fR hook files are not executed within a chroot but within the context of the host system in the binary directory. They have root privileges and access to the all host system resources (devices, filesystems, network, etc.).

.SH OPTIONS
.IP "\fB\-\-verbose\fR" 4
sets verbose option (default: False).
.IP "\fB\-h, \-\-help\fR" 4
show help message and exit.
.IP "\fB\-\-version\fR" 4
show program's version number and exit.

.SH FILES
.IP "\fBconfig/hooks/*.hook\fR:" 4
generic hook files.
.IP "\fBconfig/hooks/*.hook.binary\fR:" 4
hook files specific for the binary stage.
.IP "\fBbinary\fR:" 4
directory in which the hook files are executed.
.IP "\fBbinary/live-build/config\fR:" 4
bind mounted configuration directory within the binary directory to be read by hook files.
.IP "\fBbinary/live-build\fR:" 4
directory in which hook files are copied.

.SH SEE ALSO
.IP "\fIlb\-bootstrap\-hooks\fR(1)" 4
.IP "\fIlb\-chroot\-hooks\fR(1)" 4
.IP "\fIlb\-source\-hooks\fR(1)" 4

.SH HOMEPAGE
More information about live\-build and the Live Systems project can be found on the homepage at <\fIhttp://live-systems.org/\fR> and in the manual at <\fIhttp://live-systems.org/manual/\fR>.

.SH BUGS
Bugs can be reported by submitting a bugreport for the live\-build package in the Bug Tracking System at <\fIhttp://bugs.debian.org/\fR> or by writing a mail to the Live Systems mailing list at <\fIdebian\-live@lists.debian.org\fR>.

.SH AUTHOR
live\-build was written by Daniel Baumann <\fImail@daniel-baumann.ch\fR>.
