.\" live-build(7) - System Build Scripts
.\" Copyright (C) 2006-2013 Daniel Baumann <mail@daniel-baumann.ch>
.\"
.\" This program comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
.\" This is free software, and you are welcome to redistribute it
.\" under certain conditions; see COPYING for details.
.\"
.\"
.TH LIVE\-BUILD 1 2013\-11\-10 4.0~alpha30-1 "Live Systems Project"

.SH NAME
\fBlive\-build\fR \- Live System Build Components

.SH SYNOPSIS
\fBlb init\fR [\-\-distribution \fIDISTRIBUTION\fR] [\-\-project \fIPROJECT\fR] [\-\-verbose]
.PP
\fBlb init\fR [\-\-help]
.br
\fBlb init\fR [\-\-version]
.
.SH DESCRIPTION
live\-build contains the components to build a live system from a configuration directory.
.PP
The \fBlb init\fR command creates an empty configuration directory or reinitialize an existing one.

.SH OPTIONS
.IP "\fB\-\-distribution\fR" 4
set the default distribution.
.IP "\fB\-\-project\fR" 4
set the project to derive internal defaults from. Currently valid projects are 'debian' and 'progress-linux' (default: debian).
.IP "\fB\-\-verbose\fR" 4
sets verbose option (default: False).
.IP "\fB\-h, \-\-help\fR" 4
show help message and exit.
.IP "\fB\-\-version\fR" 4
show program's version number and exit.

.SH FILES
.IP "\fBconfig\fR:" 4
configuration directory.
.IP "\fB.build\fR:" 4
configuration directory for meta-information.

.SH SEE ALSO
.\" FIXME

.SH HOMEPAGE
More information about live\-build and the Live Systems project can be found on the homepage at <\fIhttp://live-systems.org/\fR> and in the manual at <\fIhttp://live-systems.org/manual/\fR>.

.SH BUGS
Bugs can be reported by submitting a bugreport for the live\-build package in the Bug Tracking System at <\fIhttp://bugs.debian.org/\fR> or by writing a mail to the Live Systems mailing list at <\fIdebian\-live@lists.debian.org\fR>.

.SH AUTHOR
live\-build was written by Daniel Baumann <\fImail@daniel-baumann.ch\fR>.
