.\" live-build(7) - System Build Scripts
.\" Copyright (C) 2006-2013 Daniel Baumann <mail@daniel-baumann.ch>
.\"
.\" This program comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
.\" This is free software, and you are welcome to redistribute it
.\" under certain conditions; see COPYING for details.
.\"
.\"
.TH LIVE\-BUILD 1 2013\-11\-10 4.0~alpha30-1 "Live Systems Project"

.SH NAME
\fBlive\-build\fR \- Live System Build Components

.SH SYNOPSIS
\fBlb source\-includes\fR [\-\-verbose]
.PP
\fBlb source\-includes\fR [\-\-help]
.br
\fBlb source\-includes\fR [\-\-version]
.
.SH DESCRIPTION
live\-build contains the components to build a live system from a configuration directory.
.PP
The \fBlb source\-includes\fR command copies include files into the source stage.

.SH SPECIFICATION
\fBlb source\-includes\fR copies any include files found in the \fBconfig/includes\fR and \fBconfig/includes.source\fR directories within the configuration directory.
.PP
Include files do not require to have a specific owner nor specific permissions. The files are set to be owned by root by \fBlb source\-includes\fR automatically when they are copied, original permissions of the files are preserved. Specific owners can be set with a corresponding hook file, see \fIlb-source-hooks\fR(1) for more information about hooks.
.PP
Include files in the \fBconfig/includes\fR directory are copied first, include files in the \fBconfig/includes.source\fR directory are copied second. Files present in the source and either of the include directories are silently overwritten, the later file replaces the earlier.

.SH OPTIONS
.IP "\fB\-\-verbose\fR" 4
sets verbose option (default: False).
.IP "\fB\-h, \-\-help\fR" 4
show help message and exit.
.IP "\fB\-\-version\fR" 4
show program's version number and exit.

.SH FILES
.IP "\fBconfig/includes\fR:" 4
generic include files.
.IP "\fBconfig/includes.source\fR:" 4
include files specific for the source stage.
.IP "\fBsource\fR:" 4
directory in which the include files are copied into.

.SH SEE ALSO
.IP "\fIlb\-bootstrap\-includes\fR(1)" 4
.IP "\fIlb\-chroot\-includes\fR(1)" 4
.IP "\fIlb\-binary\-includes\fR(1)" 4

.SH HOMEPAGE
More information about live\-build and the Live Systems project can be found on the homepage at <\fIhttp://live-systems.org/\fR> and in the manual at <\fIhttp://live-systems.org/manual/\fR>.

.SH BUGS
Bugs can be reported by submitting a bugreport for the live\-build package in the Bug Tracking System at <\fIhttp://bugs.debian.org/\fR> or by writing a mail to the Live Systems mailing list at <\fIdebian\-live@lists.debian.org\fR>.

.SH AUTHOR
live\-build was written by Daniel Baumann <\fImail@daniel-baumann.ch\fR>.
