.\" live-build(7) - System Build Scripts
.\" Copyright (C) 2006-2013 Daniel Baumann <mail@daniel-baumann.ch>
.\"
.\" This program comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
.\" This is free software, and you are welcome to redistribute it
.\" under certain conditions; see COPYING for details.
.\"
.\"
.TH LIVE\-BUILD 1 2013\-11\-04 4.0~alpha29-1 "Live Systems Project"

.SH NAME
\fBlive\-build\fR \- Live System Build Components

.SH SYNOPSIS
\fBlb bootstrap_hooks\fR [\-\-verbose]
.PP
\fBlb bootstrap_hooks\fR [\-\-help]
.br
\fBlb bootstrap_hooks\fR [\-\-version]
.
.SH DESCRIPTION
live\-build contains the components to build a live system from a configuration directory.
.PP
The \fBlb bootstrap_hooks\fR command executes hook files after the bootstrap stage.

.SH SPECIFICATION
\fBlb bootstrap_hooks\fR executes any hook files found in the \fBconfig/hooks\fR directory within the configuration directory.
.PP
Hook files do not require to have a specific owner nor specific permissions. They are marked executable by \fBlb bootstrap_hooks\fR automatically when they are executed.
.PP
Hook files must either have the suffix \fB*.hook\fR or \fB*.hook.bootstrap\fR.
.PP
Hook files with the suffix \fB*.hook\fR are executed first, hook files with the suffix \fB*.hook.bootstrap\fR are executed second.
.PP
Hook files are executed in alphanumberical order by \fBlb bootstrap_hooks\fR. If one hook file depends on being run after another, best practise is to use number prefixes (nnnn, starting with 0001) to ensure the order of execution.
.PP
Hook files are copied into the \fBchroot/live-build\fR directory by \fBlb bootstrap_hooks\fR. They are executed from within the chroot directory (chrooted) and can read the configuration directory in \fB/live-build/config\fR within the chroot directory.

.SH OPTIONS
.IP "\fB\-\-verbose\fR" 4
sets verbose option (default: False).
.IP "\fB\-h, \-\-help\fR" 4
show help message and exit.
.IP "\fB\-\-version\fR" 4
show program's version number and exit.

.SH FILES
.IP "\fBconfig/build\fR:" 4
generic configuration file.
.IP "\fBconfig/hooks/*.hook\fR:" 4
generic hook files.
.IP "\fBconfig/hooks/*.hook.bootstrap\fR:" 4
hook files specific for the bootstrap stage.
.IP "\fBchroot\fR:" 4
directory in which the hook files are executed.
.IP "\fBchroot/live-build/config\fR:" 4
bind mounted configuration directory within the chroot directory to be read by hook files.
.IP "\fBchroot/live-build\fR:" 4
directory in which hook files are copied.

.SH SEE ALSO
.IP "\fIlb_bootstrap_hooks\fR(1)" 4
.IP "\fIlb_binary_hooks\fR(1)" 4
.IP "\fIlb_source_hooks\fR(1)" 4

.SH HOMEPAGE
More information about live\-build and the Live Systems project can be found on the homepage at <\fIhttp://live-systems.org/\fR> and in the manual at <\fIhttp://live-systems.org/manual/\fR>.

.SH BUGS
Bugs can be reported by submitting a bugreport for the live\-build package in the Bug Tracking System at <\fIhttp://bugs.debian.org/\fR> or by writing a mail to the Live Systems mailing list at <\fIdebian\-live@lists.debian.org\fR>.

.SH AUTHOR
live\-build was written by Daniel Baumann <\fImail@daniel-baumann.ch\fR>.
