.\" live-build(7) - System Build Scripts
.\" Copyright (C) 2006-2013 Daniel Baumann <mail@daniel-baumann.ch>
.\"
.\" This program comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
.\" This is free software, and you are welcome to redistribute it
.\" under certain conditions; see COPYING for details.
.\"
.\"
.TH LIVE\-BUILD 1 2013\-11\-04 4.0~alpha28-1 "Live Systems Project"

.SH NAME
\fBlive\-build\fR \- Live System Build Components

.SH SYNOPSIS
\fBlb bootstrap_cdebootstrap\fR [\-\-cdebootstrap\-options=\fICDEBOOTSTRAP_OPTIONS\fR] [\-\-verbose]
.PP
\fBlb bootstrap_cdebootstrap\fR [\-\-help]
.br
\fBlb bootstrap_cdebootstrap\fR [\-\-version]
.
.SH DESCRIPTION
live\-build contains the components to build a live system from a configuration directory.
.PP
The \fBlb bootstrap_cdebootstrap\fR command bootstraps the chroot system with \fIcdebootstrap\fR(1).

.SH OPTIONS
.IP "\-\-cdebootstrap\-options=\fICDEBOOTSTRAP_OPTIONS\fR" 4
set \fIcdebootstrap\fR(1) options (default: None), see \fIcdebootstrap\fR(1) for more information about cdebootstrap.
.IP "\-\-verbose" 4
sets verbose option (default: False).
.IP "\-h, \-\-help" 4
show help message and exit.
.IP "\-v, \-\-version" 4
show program's version number and exit.

.SH FILES
.IP "\fBconfig/build\fR" 4
.IP "\fBcache/bootstrap\fR" 4
.IP "\fBcache/packages.bootstrap\fR" 4
.IP "\fBchroot\fR" 4
.IP "\fB.build/bootstrap\fR" 4

.SH SEE ALSO
\fIcdebootstrap\fR(1)

.SH HOMEPAGE
More information about live\-build and the Live Systems project can be found on the homepage at <\fIhttp://live-systems.org/\fR> and in the manual at <\fIhttp://live-systems.org/manual/\fR>.

.SH BUGS
Bugs can be reported by submitting a bugreport for the live\-build package in the Bug Tracking System at <\fIhttp://bugs.debian.org/\fR> or by writing a mail to the Live Systems mailing list at <\fIdebian\-live@lists.debian.org\fR>.

.SH AUTHOR
live\-build was written by Daniel Baumann <\fImail@daniel-baumann.ch\fR>.
