.TH LIVE\-HELPER 1 2010\-07\-10 2.0~a18 "Debian Live Project"

.SH NAME
\fBlh binary_grub\fR \- Complete the binary stage

.SH SYNOPSIS
\fBlh binary_grub\fR [\fIlive\-helper options\fR]

.SH DESCRIPTION
\fBlh binary_grub\fR is a low\-level command (plumbing) of \fIlive\-helper\fR(7), the Debian Live tool suite.
.PP
.\" FIXME

.SH OPTIONS
\fBlh binary_grub\fR has no specific options but understands all generic live\-helper options. See \fIlive\-helper\fR(7) for a complete list of all generic live\-helper options.

.SH FILES
.\" FIXME
.IP "\fBn/a\fR" 4

.SH SEE ALSO
\fIlive\-helper\fR(7)
.PP
This program is a part of live\-helper.

.SH HOMEPAGE
More information about live\-helper and the Debian Live project can be found on the homepage at <\fIhttp://live.debian.net/\fR> and in the manual at <\fIhttp://live.debian.net/manual/\fR>.

.SH BUGS
Bugs can be reported by submitting a bugreport for the live\-helper package in the Debian Bug Tracking System at <\fIhttp://bugs.debian.org/\fR> or by writing a mail to the Debian Live mailing list at <\fIdebian-live@lists.debian.org\fR>.

.SH AUTHOR
live\-helper was written by Daniel Baumann <\fIdaniel@debian.org\fR> for the Debian project.
